apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-allow-soi-client
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-network-soi-client: 'true'
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-soi-ns: 'true'
      ports:
        - protocol: TCP
          port: 2010
        - protocol: TCP
          port: 1049
    - to:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-soi-fedfactory: 'true'
      ports:
        - protocol: TCP
          port: 24000
    - to:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-soi-server: 'true'
