apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-cpx-http
  labels:
    run: eric-bss-eb-cpx-http
    app:  eb-java-cpx
    chart: {{ template "eric-bss-eb-cpx.chart" . }}
    {{- include "eric-bss-eb-cpx.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-cpx.productInfo" . | indent 4 }}
    {{ if .Values.tomcat.secretName }}
    projectcontour.io/upstream-protocol.tls: "8443,cpx-http"
    {{ end }}
    projectcontour.io/max-connections: "{{ .Values.ingress.max_connections }}"
    projectcontour.io/max-pending-requests: "{{ .Values.ingress.max_pending_requests }}"
    projectcontour.io/max-requests: "{{ .Values.ingress.max_requests }}"
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http-cpx
      protocol: TCP
      name: cpx-http
  selector:
    app:  eb-java-cpx
    app.kubernetes.io/instance: {{ .Release.Name }}
