# Default values for bsh Chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Allowed values: 0,1
replicaCount: 1

imageCredentials:
  eric-bss-eb-bsh:
    repoPath:
    pullPolicy:
    registry:
      url:
  init-wait-for-data-bsh:
    repoPath:
    pullPolicy:
    registry:
      url:
  init-wait-for-xrefs-bsh:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  eric-bss-eb-bsh:
    name: "eric-bss-eb-bsh"
    tag: "22.15.12"
  init-wait-for-data-bsh:
    name: "eric-bss-eb-wait-for-condition"
    tag: "22.15.12"
  init-wait-for-xrefs-bsh:
    name: "eric-bss-eb-wait-for-condition"
    tag: "22.15.12"

restartPolicy: Always

metadataName: eric-bss-eb-bsh

# Parameters for deploying BSH
bshDeployments:
  #  - name: "f1-2"
  #    startParameters: "-rst 5 -rto 600 -n"
  #    # Parameter "segmentationParameters" will be added to command line when bsh is started.
  #    segmentationParameters: "-f 1,2"
  - name: "all"
    startParameters: "-rst 5 -rto 600 -n"
    # Parameter "segmentationParameters" will be added to command line when bsh is started.
    segmentationParameters:
    # To generate trace files, it is necessary set the trace file name in the variables below.
    # These files will be stored in the log PVC.
    tracingAndLogging:
      bscsErrorTimestamp: ""
      # dtaTracefile: "dta.bsh-all.trc"
      dtaTracefile: ""
      # dxlTracefile: "dxl.bsh-all.trc"
      dxlTracefile: ""
      # udrTracefile: "udr.bsh-all.trc"
      udrTracefile: ""

# Grace period for pod termination, which is used to shut down BSH gracefully.
# By default, k8s allows a graceful application shutdown within 30s.
# But for BSH a larger value is needed in some cases, e.g. if a large
# transaction size is used (for better performance).
terminationGracePeriodSeconds: 300

#DATA_RETRY_TIME, DATA_RETRY_TIME_MAX
#By default, there is no definition for a time interval in which applications try to reconnect to DaTA.
#If you set the environment variable, the value represents the time interval an application waits
#until it tries to reconnect to DaTA.
#Subsequent connection retries are performed under the following conditions:
# - A double time interval has elapsed and has exceeded a maximum of 60 seconds.
# - A double time interval has elapsed and the value specified by DATA_RETRY_TIME_MAX has been exceeded.
dataRetry:
  dataRetryTime:
  dataRetryTimeMax:

bshRacSetup:
  waitTime: 500
  totalWaitTime: 30
  numAttempts: 60

tnsnames:
  bscsdb: '{{ tpl .Values.global.tnsnames.bscsdb . }}'

sqlnet:
  ora: '{{ tpl .Values.global.sqlnet.ora . }}'

envVariables:
  bshUpdateArraySize:
  bshDxlTracing:

resources:
  limits:
    cpu: 1000m
    memory: 10Gi
  requests:
    cpu: 100m
    memory: 256Mi

#A local nodeSelector definition has priority over the global definition.
nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b


#Example:
#nodeSelector:
#  kubernetes.io/hostname: "<hostname>"


suffix:
