apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-ff-registry-ff.xml
data:
  Registry_FF.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >
    <ComponentRegistry>
        <Node name="FF">
            <KeyValue key="FEDFACTORY_NAME" type="String" value="fedfactory1" comment="null"/>
            <KeyValue key="REFRESH_PERIOD" type="String" value="10" comment="null"/>
            <KeyValue key="FED_FACTORY_USER" type="String" value="SOIUSER" comment="null"/>
            <KeyValue key="SET_SOCKET_TIMEOUTS" type="String" value="true" comment="Enable socket timeout on socket level for establishing and requests via all outgoing CORBA connections"/>
            <KeyValue key="SOCKET_TIMEOUT" type="String" value="15" comment="Socket timeout in minutes used for calls on all outgoing CORBA connections in seconds, a value of 0 means no timeout"/>
            <KeyValue key="SOCKET_CONNECTION_TIMEOUT" type="String" value="5" comment="Socket timeout in seconds used for establishing all outgoing CORBA connections in seconds, a value of 0 means no timeout"/>
            <KeyValue key="SERVICE_FACTORY_TIMEOUT" type="String" value="60" comment="Idle time in minutes of service factories representing a user session before automatic disposal"/>
            <KeyValue key="SERVICE_FACTORY_TIMEOUT_NO_CALLBACK" type="String" value="120" comment="Service factories timeout in minutes in case no callback object is detected. The service factories will be automatically disposed of when it reaches SERVICE_FACTORY_TIMEOUT_NO_CALLBACK. The value must be equal or bigger than SERVICE_FACTORY_TIMEOUT."/>
            <KeyValue key="NAME_SERVICE.LIST" type="String" value={{ .Values.global.k8sNamingServiceList | quote }} comment="Comma separated list of naming services to be crawled additionally to the one specified in orb.properties. NOTE: When using multiple NamingServices the name of the federated factory has to be unique across all naming NamingServices"/>
            <!-- KeyValue key="NAME_SERVICE_FILTER.LIST" type="String" value="com/lhs/private/soi" comment="Comma separated list of paths, that are crawled. If the value is empty the whole naming service is crawled."/ -->
            <KeyValue key="NAME_SERVICE_EXCLUDE_FILTER" type="String" value="/com/lhs/public/soi" comment="A path in the naming service that should not be crawled. This value must be set to the path where the fedfactory is registered!"/>
            <KeyValue key="REMOVE_INVALID_REFERENCES" type="String" value="true" comment="Flag for removing invalid reference from the naming services."/>
            <KeyValue key="SECURITY" type="String" value="true" comment="null"/>
            <KeyValue key="AUTHENTICATION_METHOD" type="String" value="SECURITY_SERVER" comment="null"/>
            <KeyValue key="QUARANTINE_PERIOD" type="Integer" value="65000" comment="Quarantine period after that terminated SOI server will be unregistered. The value is in msec."/>
            <!-- KeyValue key="AUTHENTICATION_METHOD" type="String" value="DB" comment="null"/ -->
            <!-- KeyValue key="AUTHENTICATION_JDBC_URL" type="String" value="jdbc:oracle:thin:@<dbhost>:<port>:<sid>" comment="null"/ -->
            <!-- KeyValue key="AUTHENTICATION_JDBC_DRIVER" type="String" value="oracle.jdbc.driver.OracleDriver" comment="null"/ -->
        </Node>
    </ComponentRegistry>
