apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-ff-orb
  labels:
    run: eric-bss-eb-ff-orb
    app: eb-java-ff
    chart: {{ template "eric-bss-eb-ff.chart" . }}
    {{- include "eric-bss-eb-ff.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-ff.productInfo" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: orb
      protocol: TCP
      port: 24000
  selector:
    app: eb-java-ff
    app.kubernetes.io/instance: {{ .Release.Name }}
