apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cx-integration.xml
data:
  CX_Integration.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <!-- Customer CX / BSCS iX -->

    <ComponentRegistry>
    <Node name="FUNC_WCLT">

        <!-- PrintoutFormat for contracts
             possible values:    "pdf" for PDF output
                                "rtf" for RTF output
        -->
        <KeyValue key="PrintoutFormat" value="pdf" />


        <!-- Specifies the class for PDF/RTF generation.Possible values are -->

        <!-- com.lhs.ccb.cfw.wcs.printhandler.PDFPrintAdapterXEP for PDF generation with XEP (RenderX) -->
        <!-- com.lhs.ccb.cfw.wcs.printhandler.PDFPrintAdapterFOP for PDF generation with FOP (Apache)  -->


        <KeyValue key="PdfPrintAdapterClass" value="com.lhs.ccb.cfw.wcs.printadapter.PDFPrintAdapterFOP" comment="Class for the file type" />


        <!-- If set to true , the internal XML representation will be written to the users home directory (the user who started the webserver) -->

        <KeyValue key="GenerateXMLOutputForPrintContract" value="true" comment="Class for the file type" />

        <!-- Specifies the root path where configuration and license files are located.Needed for XEP     -->
        <!-- for example \\193.101.146.73\XEP\ -->
        <!-- or C:\XEP\ -->
    <!--     <KeyValue key="PdfPrintAdapterConfigPath" value="\\193.101.146.73\XEP\" comment="Config path " />-->


        <!-- net.sf.saxon.TransformerFactoryImpl -->

        <KeyValue key="TransformerFactory" value="net.sf.saxon.TransformerFactoryImpl" comment="Transformer factory for XSLT" />

        <!-- The name of the Stylesheet for contract printouts is not configurable anymore. The name of this .xsl file has to be "bscs_Printout_PDF_Def".
        The reason is: The branding for contract printout is now supported. The functionality that selects the business unit specific style sheet (CX_Registry)
        requires a defined default style sheet name to determine the key.
        -->
        <!--  the path of the PDF stylesheet -->
        <KeyValue key="PDFStylesheetPath" value="com/lhs/ccb/rapidactivation/resource/" comment="The path for the PDFStyleesheet" />


        <!-- Jaas context -->
        <KeyValue key="JaasContext" value="BSCSContext" comment="JAAS context to be used"/>

        <!-- Location of AboutPageBundle.xml -->
        <KeyValue key="AboutPageBundle" value="com.lhs.ccb.util.resource.AboutPageBundle" comment="About bundle file path"/>

        <!-- Location of LoginPageBundle.xml -->
        <KeyValue key="LoginPageBundle" value="com.lhs.ccb.util.resource.LoginPageBundle" comment="About bundle file path"/>

        <!--  Option, whether the legal notice and privacy policy should be displayed before login -->
        <KeyValue key="EnablePrivacyLegalNotice" type="Boolean" value="{{ .Values.cxIntegration.EnablePrivacyLegalNotice }}" comment=""/>

        <!--  URI to privacy policy
            The custom URI to the complete privacy policy page.
            If not set, the system default is used: privacyPolicy.
        -->
        <KeyValue key="PrivacyPolicy_Uri" type="String" value="{{ .Values.cxIntegration.PrivacyPolicy_Uri }}" comment=""/>

        <!--
          - Error dictionary options:
            - client: translate server error messages with the ClientErrorDictionary
            - server (default): display the server error messages on screen
            - none: don't translate the error messages, display a generic error message
                    as defined in the ClientErrorDictionary (GlobalErrorMessage)
        -->
        <KeyValue key="UseErrorDictionary" value="client" />

        <!-- Client specific error dictionary -->
        <KeyValue key="ClientErrorDictionary" value="com/lhs/ccb/util/resource/CX_ErrorDictionary" />

        <!--
          - Security check options (they don't affect the login mechanism, login will always be performed):
            - true: turns security checks on
            - false: turns security checks off
        -->
        <KeyValue key="UseSecurity" type="Boolean" value="true" />

        <!--
          - URL of the 'Home' link in the horizental navigation bar (used in HNavBar.jsp)
            - example: if the "Home_Url" key value is "Home.su" and if the base link is "http://localhost:8080/CMS",
                       then the URL that is opened is "http://localhost:8080/CMS/Home.su"
            - to construct the home URL without considering the base link, add "//" just before the constant
        -->
        <KeyValue key="Home_Url" value="Home.su" />

        <!--
          - Localization options:
            - server: USER.READ command is used to get the user locale
            - browser (default): web browser locale is used
        -->
        <KeyValue key="Localization" value="Browser" />

        <!-- Cached reference data refresh settings -->
        <Node name="RefreshReferenceDataCache">

            <!-- the settings are valid for all cached reference data -->
            <KeyValue key="ABSOLUTE" type="Boolean" value="true" />

            <!-- refresh period in milliseconds, default is set to 24h (1000 * 60 * 60 * 24) -->
            <!-- <KeyValue key="PERIOD" type="Integer" value="90000" /> -->

            <!-- TODO: clarify description
               - milliseconds on which a refresh is initiated. In case ABSOLUTE flag is set, the next refresh is set on next
                 midnight plus this value, otherwise on server start plus this value
            -->
            <!-- refresh 5 minutes after midnight (1000 * 60 * 5)-->
            <KeyValue key="START" type="Integer" value="300000" />

        </Node>

        <!--
          - Duplicate customer check options:
            - true: customer duplicate check will be performed during customer creation
            - false: no duplicate check
        -->
        <KeyValue key="performCustomerDuplicateCheck" value="true"/>

        <!--
          - CDR call anonymization options (this value must match the server configuration):
            - true: CDR call anonymization is used
            - false: no CDR call anonymization
        -->
        <KeyValue key="CDRCallAnonymization" value="false"/>

        <!--
          - Configuration for each contract status: which status the directory numbers should have to be displayed in
            ContractOverview and Service Details screen.
          - directory_number statuses:
            - f : free
            - r : reserved
            - a : active
            - d : deassigned
            - i : ported in
            - o : ported out
            - s : snap-back out
            - t : snapped back out reserved
            - c : ported in and contracted
            An empty value means no display at all.
        -->
        <KeyValue key="Contract_Onhold_VisibleDirnumStati" value="fraiostcr"/>
        <KeyValue key="Contract_Active_VisibleDirnumStati" value="aicr"/>
        <KeyValue key="Contract_Supended_VisibleDirnumStati" value="aicr"/>
        <KeyValue key="Contract_Deactive_VisibleDirnumStati" value="frdostcr"/>

        <!-- Default market for contract creation (use market prefix) -->
        <KeyValue key="DefaultCreateContractMarket" value="GSM" />

        <!-- Comma separated list of markets that use CIBER for roaming (use market prefixes) -->
        <KeyValue key="CIBERMarkets" value="AMP" />

        <!-- Payment method used for customer templates - Cash -->
        <KeyValue key="CustTemplPayMeth" value="-1" />

        <!-- Option that specifies if the prepaid lifecycle is automatically started
             when performing a first time prepaid activation (can be true or false) -->
        <KeyValue key="PrepaidActivationStartLifecycle" type="Boolean" value="true" />

        <!-- Option that specifies if the pre-activated subsciber contracts (NOPAS)
             can be modified (can be true or false) -->
        <KeyValue key="ModifyPreactivatedContracts" type="Boolean" value="true" />

        <!-- The following setting specifies, whether payment arrangements can be document type specific or not.  -->
        <KeyValue key="DocumentTypeSpecificPaymentArrangement" type="Boolean" value="true" comment="Specifies, whether payment arrangements can be document type specific."/>

        <!-- Sets the maximum number of lines in a table screen for paging functionality -->
        <KeyValue key="TableResultSize"   value="20"/>

        <!-- Sets the maximum number of lines in a promotions package table screen for paging functionality -->
        <KeyValue key="PromotionsPackageTableResultSize" value="3"/>

        <!-- Sets the value of the INCLUDE_SUBNODES parameter in the CUSTOMER_PROMOTIONS.SEARCH
            and CUSTOMER_PROMOTIONS.READ commands called from the Customer Overview screen
            to populate the promotions table -->
        <KeyValue key="IncludeSubnodes" value="true"/>

        <!-- Sets the maximum number of lines in a parameter value change table screen for paging functionality -->
        <KeyValue key="ParameterValueChangeTableResultSize" value="300"/>

        <!--
          - Auto assign(prepare)  a directory number:
            - true: the system will be auto assign (automatically prepare) a new directory number.
            - false: not auto assign (automatically prepare) a new directory number.
        -->
        <KeyValue key="AutoAssignDirectoryNumber" type="Boolean" value="true" comment="Auto assign a directory number"/>
            <!-- PN 00381402 -->
        <!-- Configuration of the initial status of a new hierarchy member/sales member (root and lower levels)
             INTERESTED_STATE = 'i';
             ACTIVE_STATE = 'a';
             DEACTIVE_STATE = 'd';
             The value for InitialHierarchyMemberStatusReason has to be suitable for the configured status, see table
             REASONSTATUS_ALL.
        -->
        <KeyValue key="InitialHierarchyMemberStatus" value="a" comment="initial status of a new hierarchy member" />
        <KeyValue key="InitialHierarchyMemberStatusReason" type="Integer" value="1" comment="initial reason for the status of a new hierarchy member" />

        <KeyValue key="ClientValidation" value="com/lhs/ccb/util/resource/ClientValidation.xml" comment="Validation on the client side" />

        <!--
           - Specifies the URL to the CX web application.
           - The URL is required on Order/Collectible overview.
        -->
        {{- if and .Values.tomcat.secretName }}
        <KeyValue key="CX_URL"   value="https://{{.Values.global.ingress.fqdn.TRF}}/custcare_cu/"/>
        {{ else }}
        <KeyValue key="CX_URL"   value="http://{{.Values.global.ingress.fqdn.TRF}}/custcare_cu/"/>
        {{ end }}

        <KeyValue key="CX_DocumentRootPath" value="${DOCIMAGES_ROOTDIR}" comment="Root directory for document references."/>

        {{- if and .Values.tomcat.secretName }}
        <KeyValue key="DCX_URL" value="https://{{.Values.global.ingress.fqdn.TRF}}/dcx/" comment="URL to the DCX application in case iX Collection is installed." />
        {{ else }}
        <KeyValue key="DCX_URL" value="http://{{.Values.global.ingress.fqdn.TRF}}/dcx/" comment="URL to the DCX application in case iX Collection is installed." />
        {{ end }}

        <!-- Default value for maximum events search results in the solution unit EventViewSU -->
        <KeyValue key="DefaultLimitForEventSearch" type="Integer" value="50" />

        {{- if and .Values.tomcat.secretName }}
        <KeyValue key="PAYMENT_PROCESSOR_URL" value="https://{{.Values.global.ingress.fqdn.TRF}}/{{.Values.cxIntegration.paymentProcessorLink}}" comment="External payment processor URL"/>
        {{ else }}
        <KeyValue key="PAYMENT_PROCESSOR_URL" value="http://{{.Values.global.ingress.fqdn.TRF}}/{{.Values.cxIntegration.paymentProcessorLink}}" comment="External payment processor URL"/>
        {{ end }}

    </Node>
    </ComponentRegistry>
