apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cx-jacorb.properties
data:
  jacorb.properties: |

    ###################################
    #                                 #
    #  ORB Connection Configuration   #
    #                                 #
    ###################################

    # number of retries if connection cannot directly be established
    jacorb.retries={{ int64 .Values.jacorb.orbConnection.retries }}

    # how many msecs. do we wait between retries
    jacorb.retry_interval={{ int64 .Values.jacorb.orbConnection.retryInterval }}

    # Initial timeout for establishing a connection.
    jacorb.connection.client.connect_timeout={{ int64 .Values.jacorb.orbConnection.clientConnectTimeout }}
