apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-cx-http
  labels:
    run: eric-bss-eb-cx-http
    app: eb-java-cx
    chart: {{ template "eric-bss-eb-cx.chart" . }}
    {{- include "eric-bss-eb-cx.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-cx.productInfo" . | indent 4 }}
    {{ if .Values.tomcat.secretName }}
    projectcontour.io/upstream-protocol.tls: "8443,cx-http"
    {{ end }}
    projectcontour.io/max-connections: "{{ .Values.ingress.max_connections }}"
    projectcontour.io/max-pending-requests: "{{ .Values.ingress.max_pending_requests }}"
    projectcontour.io/max-requests: "{{ .Values.ingress.max_requests }}"
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http-cx
      protocol: TCP
      name: cx-http
  selector:
    app: eb-java-cx
    app.kubernetes.io/instance: {{ .Release.Name }}
