apiVersion: batch/v1
kind: Job
metadata:
  name: eric-bss-eb-ns-pre-install-hook
  labels:
    app: eb-java-nsjob
    chart: {{ template "eric-bss-eb-ns.chart" . }}
    {{- include "eric-bss-eb-ns.kubernetesIoInfo" $ | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-ns.productInfo" $ | indent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: eb-java-nsjob
        chart: {{ template "eric-bss-eb-ns.chart" . }}
        {{- include "eric-bss-eb-ns.kubernetesIoInfo" $ | nindent 8 }}
        heritage: {{ .Release.Service }}
      annotations:
      {{- include "eric-bss-eb-ns.productInfo" $ | indent 8 }}
    spec:
      securityContext:
        {{- include "eric-bss-eb-ns.checkPodUserLoginData" $ | nindent 8 }}
      {{- if .Values.global.rbac.sa_roles_create }}
      serviceAccountName: {{ .Chart.Name }}-sa
      {{- end }}
      restartPolicy: Never
      {{- if $.Values.global.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.global.imageCredentials.pullSecret }}
      {{- end }}
      containers:
        - name: nsjob
          # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
          {{ $templDict := dict "Values" .Values "containerKey" "nsjob" }}
          image: "{{ template "eric-bss-eb-ns.registryUrl" $templDict }}/{{ template "eric-bss-eb-ns.repoPath" $templDict }}{{ index .Values "images" $templDict.containerKey "name" }}:{{ index .Values "images" $templDict.containerKey "tag" }}"
          imagePullPolicy: {{ template "eric-bss-eb-ns.pullPolicy" $templDict }}
          command: ["/bin/sh", "-c", "rm -rf /workdir/NS_Share/*"]
          volumeMounts:
            - name: naming-service-volume
              mountPath: "/workdir/NS_Share"
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector: {{ toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.affinity }}
      affinity: {{ toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      volumes:
        - name: naming-service-volume
          persistentVolumeClaim:
            claimName: eric-bss-eb-pvc-ns-share
