# A service is launched for each of the items in the tuple below.
# Every occurance of namingservice variable is replaced during each range loop by the current item.
{{- range $namingservice := (split " " (include "eric-bss-eb-ns.namingservicelist" .)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $namingservice }}
  labels:
    run: {{ $namingservice }}
    app: {{ template "eric-bss-eb-ns.name" $ }}
    chart: {{ template "eric-bss-eb-ns.chart" $ }}
    {{- include "eric-bss-eb-ns.kubernetesIoInfo" $ | nindent 4 }}
    heritage: {{ $.Release.Service }}
  annotations:
  {{- include "eric-bss-eb-ns.productInfo" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.service.port }}
      protocol: TCP
      targetPort: 2010
  selector:
    app: {{ $namingservice }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{- end }}
