apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-ax-registry.xml
data:
  AX_Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <!-- AX / BSCS iX -->

    <ComponentRegistry>
    <Node name="FUNC_WCLT">

        <!--
          - Application name used for window titles.
            - This value is directly accessible through method ApplicationSettings.getApplicationName()
            - This key is also used as parent permission key for initialization of the PermissionChecker
        -->
        <KeyValue key="ApplicationName" type="String" value="AX" comment="The name of the web client application"/>

        <!-- Application version TODO: used anywhere? -->
        <KeyValue key="ApplicationVersion" type="String" value="1.0" comment="The version of the web client application"/>

        <!-- Application name as defined in APP_MODULES -->
        <KeyValue key="ModuleName" type="String" value="AX" comment="The module name as defined in APP_MODULES"/>

        <!-- Deployment scope. Available values are BSCS and CBIO. -->
        <KeyValue key="DeploymentScope" type="String" value="CBIO" comment="Deployment scope"/>

        <!--
          - Starts the User settings Solutionunit directly after the user has logged into the
            client. The User settings Solutionunit is a solution unit that can be used to force
            the user to do some initial settings like selecting a business unit or a dealer.
            The workflow of the User settings Solutionunit is defined by the client but the name
            of the SolutionUnit must always be "UserSettings".
        -->
        <KeyValue key="StartUserSettingsSU" type="Boolean" value="true" comment="The name of the web client application"/>

        <!-- SOI name for security initialization -->
        <KeyValue key="SoiNameForSecurity" type="String" value="SECURITY" comment="The name of the security SOI"/>

        <!-- SOI version for security initialization -->
        <KeyValue key="SoiVersionForSecurity" type="String" value="3" comment="The version of the security SOI"/>

        <!--
          - The implementation of the ModelContainer
          - Default is com.lhs.ccb.cfw.cda.servicelayer.model.DefaultModelContainer
          -
          - Used by SoiContainerFactory
        -->
        <KeyValue key="ModelContainerImpl" type="String" value="com.lhs.ccb.cfw.cda.servicelayer.model.WebModelContainer" comment="The implementation of the model container"/>

        <!--
          - Client/server data exchange options (it doesn't affect HTTP communication):
            - true: the client will send only changed attributes to the CORBA server
            - false: the client will send all attrubutes to the CORBA server
        -->
        <KeyValue key="SendOnlyChangedData" type="Boolean" value="true" comment=""/>

        <!-- Permission checker class to be used by the client framework -->
        <KeyValue key="PermissionChecker" type="String" value="com.lhs.ax.util.ClientPermissionChecker" comment=""/>

        <!--
          - Specifies the root path where help files are stored
            - Help root path is a directory located in the web server
            - example: help path is "help". Then the root direcory for the help files is
                       http://host:port/CMS/help where http://host:port/CMS is the path of the deployed application.
            - If the root help path should have different sub directories these sub directories
              must be specified in the workflow configuration xml file. For this have a look at
              workflowconfiguration.dtd.
        -->
        <KeyValue key="HelpRootPath" type="String" value="help" comment=""/>

        <!--
          - The configuration files for default models (each default model must have a configuration file)
          - used by: ModelMetaDataRepository
        -->
        <Node name="ModelConfigs">
            <KeyValue key="FinancialDocumentModels" type="String" value="com/lhs/ax/financialOverview/resource/FinancialDocumentModelConfig.xml" comment=""/>
            <KeyValue key="FinancialTransactionModels" type="String" value="com/lhs/ax/financialOverview/resource/FinancialTransactionModelConfig.xml" comment=""/>
            <KeyValue key="FinancialUseCaseModels" type="String" value="com/lhs/ax/usecase/resource/FinancialUseCaseModelConfig.xml" comment=""/>
            <KeyValue key="CollectionModels" type="String" value="com/lhs/ax/financialOverview/resource/CollectionModelConfig.xml" comment=""/>
            <KeyValue key="DebtorCreditorModels" type="String" value="com/lhs/ax/debtorCreditor/resource/DebtorCreditorModelConfig.xml" comment=""/>
            <KeyValue key="DebtorCreditorContractModels" type="String" value="com/lhs/ax/contract/resource/DebtorCreditorContractModelConfig.xml" comment=""/>
            <KeyValue key="DebtorCreditorReferenceDataModels" type="String" value="com/lhs/ax/contract/resource/DebtorCreditorReferenceDataModelConfig.xml" comment=""/>
            <KeyValue key="BSCSModels" type="String" value="com/lhs/ccb/model/resource/BSCSModelConfig.xml" comment=""/>
            <KeyValue key="CustomerModels" type="String" value="com/lhs/ccb/model/resource/CustomerModelConfig.xml" comment=""/>
            <KeyValue key="BillingAccountModels" type="String" value="com/lhs/ccb/billingAccount/resource/BillingAccountModelConfig.xml" comment=""/>
            <KeyValue key="ServiceModels" type="String" value="com/lhs/ccb/service/resource/ServiceModelConfig.xml" comment=""/>
            <KeyValue key="BillingDocumentModels" type="String" value="com/lhs/ccb/billing/resource/BillingModelConfig.xml" comment=""/>
            <KeyValue key="SecurityModel" type="String" value="com/lhs/ccb/user/resource/SecurityModelConfig.xml" comment=""/>
            <KeyValue key="FinancialSettingModels" type="String" value="com/lhs/ax/financialsettings/resource/FinancialSettingModelConfig.xml"/>
            <KeyValue key="AXUltilityModels" type="String" value="com/lhs/ax/util/resource/AXUltilityModelConfig.xml" comment="" />
            <KeyValue key="PaymentInstructionModels" type="String" value="com/lhs/ax/paymentInstruction/resource/PaymentInstructionModelConfig.xml" comment="" />
            <KeyValue key="PromotionModel" type="String" value="com/lhs/ccb/model/resource/PromotionModelConfig.xml" comment=""/>
            <KeyValue key="FinancialDocumentTransactionModels" type="String" value="com/lhs/ax/financialOverview/resource/FinancialDocumentTransactionModelConfig.xml" comment=""/>
        </Node>

        <!--
          - Global Resource bundle file for general error messages. It should be used to define
            global error messages that can occur in several pages.
            - used by: ErrorUtil class of CFW to obtain the error messages
        -->
        <KeyValue key="CommonErrorBundle" type="String" value="com/lhs/ax/util/resource/CommonErrorsBundle" comment=""/>

        <!--
          - Validator configuration used for AX.
        -->
        <KeyValue key="ClientValidation" type="String" value="com/lhs/ax/util/resource/AXValidation.xml" comment=""/>

        <!--
          - Hook that is called from the client framework after a Service Accessor (Service Object) is created
            - this class reinitialises the Business unit and the dealer for the user
        -->
        <KeyValue key="UserInitialisation"  type="String"  value="com.lhs.ax.util.ClientUserInitialisation"/>

        <!-- Branding options -->
        <Node name="Branding">

            <!--
              - The class that implements the branding for this application.
                If no value is specified the default framework branding implementation is used.
            -->
            <KeyValue key="Class" type="String" value="com.lhs.ax.util.BusinessUnitBrandingAdapter"/>

            <!--
              - List all business units as nodes that have a different appearance as the default.
                The name of the node is the business unit identifier.
            -->
            <!--
              - List all business units as nodes that have a different appearance as the default.
                The name of the node is the business unit identifier.

            <Node name="2">
                <KeyValue key="StyleSheet_bscs_main" type="String" value="webresources/css/bscs_main.css" comment="Path to the stylesheet used for this business unit."/>
                <KeyValue key="StyleSheet_bscs_main_expanded" type="String" value="webresources/css/bscs_main_expanded.css" comment="Path to the expanded stylesheet used for this business unit."/>
                <KeyValue key="StyleSheet_bscs_dojo" type="String" value="webresources/css/bscs_dojo.css" comment="Path to the dojo stylesheet used for this business unit."/>
            </Node>
            -->

        </Node>

        <!--
          - Comma separated list of user attributes that must be observed for changes in order to perform a SESSION.CHANGE on the reference connection.
            - note: they are stored in the user session by UserPropertiesFacade
            - used by: UserAttributesObservable.java
        -->
        <KeyValue key="ObservedUserAttributes" type="String" value="BU_ID,DEALER_ID"/>

        <!-- Class that filters the data containers before they are processed for execution (used for future dated requests) -->
        <!-- <KeyValue key="CustomizedExecutionFilter" type="String" value="com.lhs.ccb.util.JobCommitFilter"/> -->

        <!--
          - Configuration of the SOI name and version the client should connect to.
          - This configuration overrules the configuration of "soiName" and "soiVersion" in the ModelConfig files.
          - It needs to be adapted for customization purposes.
        -->
        <!-- The SOI name the client should connect to. -->
        <KeyValue key="CIL" type="String" value="CIL" comment="The name of the SOI."/>

        <!-- The SOI version the client should connect to. -->
        <KeyValue key="CIL_Version" type="String" value="7" comment="The version of the SOI."/>

        <!--  URL to DCX -->
        {{- if and .Values.tomcat.secretName }}
        <KeyValue key="DCX_URL" type="String" value="https://{{.Values.global.ingress.fqdn.TRF}}/dcx/" comment=""/>
        {{ else }}
        <KeyValue key="DCX_URL" type="String" value="http://{{.Values.global.ingress.fqdn.TRF}}/dcx/" comment=""/>
        {{ end }}

        <!--  Codes of payment methods always valid for incoming documents (separated by ',')
              (see PAYMENTTYPE_ALL.PAYMENTCODE):
              D - direct debit
              P - cash
         -->
        <KeyValue key="IncDocDefPayMethods" type="String" value="D,P" comment=""/>


        <!-- Cash/Payable discount options -->
        <Node name="Discounts">

            <!--
               - The following setting allows the configuration of cash discounts.
               - If the cash discount functionality is switched off no display and entry fields
               - for cash discount, GL-account for cash discount have to be shown on the screens.
             -->
            <KeyValue key="EnableCashDiscounts" type="Boolean" value="true" comment="Flag to configure the application of cash discounts"/>

            <!--
               - The following setting allows the configuration of payable discounts.
               - If the payable discount functionality is switched off no display and entry fields
               - for cash discount, GL-account for cash discount have to be shown on the screens.
             -->
            <KeyValue key="EnablePayableDiscounts" type="Boolean" value="true" comment="Flag to configure the application of payable discounts"/>

        </Node>

         <!-- Payment Options -->
        <Node name="Payment">

            <!--
               - The following setting allows the configuration of the behavior of AX in case of over payments.
               - Either a warning is displayed or not.
             -->
            <KeyValue key="EnableOverpaymentWarning" type="Boolean" value="false" comment="Flag to activate a warning message in case of over payments"/>

        </Node>

        <Node name="EventDrivenService">
        <!-- set the value from MPDEVTAB.DES -->
            <KeyValue key="BankChargeAmount" type="String" value="Banking charge for rejected direct debit/check"/>
            <KeyValue key="HandlingChargeAmount" type="String" value="Handling charge for rejected direct debit/check"/>
        </Node>

        <!--
           List of files containing the client's application context configuration
         -->
        <Node name="ApplicationContextConfigs">
            <KeyValue key="rootApplicationContext-ax.xml" value=""
                      comment="The first application context configuration file of the AX client" />
        </Node>

        <!--
          -Valid values are "money" and "bscsMoney"
          -if no value or wrong value is configured. The default value "money" will be used.
          -money - validator uses Currency format from JAVA (MoneyValidator).
          -bscsMoney - validator uses currency format from database table CURRENCY_VERSION (BSCSMoneyValidator).
        -->
        <KeyValue key="CurrencyValidator" type="String" value="money"/>

        <!-- Specifies how to the PDF will be sent to the browser
                inline - the PDF will open in the browser
                attachment - the PDF will be sent to download
         -->
        <KeyValue key="BrowserPDFDisposition" value="attachment" type="String"  />

        <!-- Configures the MODE parameter when the BILLING_ACCOUNT.SEARCH loading 'Search memo' for Large Account-->
        <KeyValue key="BillingAccountMode" type="String" value="O" comment="Define the MODE parameter when the BILLING_ACCOUNT.SEARCH is going to be called when loading 'Search memo' page when called from the link for such a large account in the Memo page overview. Default value is 'O'= MODE_OWNED. Acceptable values 'L'= MODE_LA_OWNED , 'U'= MODE_USABLE"/>


    </Node>
    </ComponentRegistry>
