{{- if .Values.global.rbac.sa_roles_create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-sa
roleRef:
  kind: Role
  name: eric-bss-eb-regular-role
  apiGroup: rbac.authorization.k8s.io
---
{{ if .Values.global.dataHighAvailability.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding-data-monitor
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-sa
roleRef:
  kind: Role
  name: eric-bss-eb-lease-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}