apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-gmdcom-rac-setup.xml
data:
  RAC_Setup.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC "ComponentRegistry.dtd" "ComponentRegistry.dtd">
    <ComponentRegistry>
            <Node name="RAC_Setup">

                    <!-- error codes are listed in FUNC_FRMWK_SRV_DB_Registry.xml -->

                    <KeyValue key="WaitTime" type="Integer" value={{ .Values.gmdcomRacSetup.waitTime | quote }} comment="after connection failure the process has to sleep WaitTime ms before reconnect"/>
                    <KeyValue key="TotalWaitTime" type="Integer" value={{ .Values.gmdcomRacSetup.totalWaitTime | quote }} comment="the process will try to reconnect till TotalWaitTime s has been reached"/>
                    <KeyValue key="NumAttempts" type="Integer" value={{ .Values.gmdcomRacSetup.numAttempts | quote }} comment="the process will try to reconnect at most NumAttemps time"/>
            </Node>
    </ComponentRegistry>