apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-dcx-registry.xml
data:
  DCX_Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>
        <Node name="FUNC_WCLT">

            <!-- - The application name used for window titles. - This value is directly
                accessible through method ApplicationSettings.getApplicationName() This key
                is also used as parent permission key for initialization of the PermissionChecker. -->
            <KeyValue key="ApplicationName" type="String" value="DCX" comment="The name of the web client application" />
            <!-- - The version of the application. -->
            <KeyValue key="ApplicationVersion" type="String" value="1.0" comment="The version of the web client application" />

                <!-- Deployment scope. Available values are BSCS and CBIO. -->
            <KeyValue key="DeploymentScope" type="String" value="CBIO" comment="Deployment scope"/>

            <!-- Starts the User settings Solutionunit directly after the user has
                logged into the client. The User settings Solutionunit is a solution unit
                that can be used to force the user to do some initial settings like selecting
                a business unit or a dealer. The workflow of the User settings Solutionunit
                is defined by the client but the name of the SolutionUnit must always be
                "UserSettings". -->
            <KeyValue key="StartUserSettingsSU" type="Boolean" value="true"
                comment="The name of the web client application" />

            <!-- Feature 305080_wmx - Michel Forster - Begin -->
            <Node name="PartLinkNextStep">
                <KeyValue key="INSTALLMENT" type="String"
                    value="PaymentPlanOverview_Result" />
                <KeyValue key="COLLECTION" type="String"
                    value="CollectionAgencyDetails_Result" />
            </Node>
            <!-- Feature 305080_wmx - Michel Forster - End -->

            <!-- SoiName for security initialization -->
            <KeyValue key="SoiNameForSecurity" type="String" value="SECURITY"
                comment="The name of the security SOI" />
            <!-- SoiVersion for security initialization -->
            <KeyValue key="SoiVersionForSecurity" type="String" value="3"
                comment="The version of the security SOI" />
            <!-- - The implementation of the ContainerFactory - Default is com.lhs.ccb.cfw.cda.servicelayer.SoiContainerFactory
                - - Used by SoiServerGateway -->
            <!-- configuration key="ContainerFactoryImpl" constant="com.lhs.ccb.cfw.cda.servicelayer.SoiContainerFactory"
                / -->


            <!-- - The implementation of the ModelContainer - Default is com.lhs.ccb.cfw.cda.servicelayer.model.DefaultModelContainer
                - - Used by SoiContainerFactory -->
            <KeyValue key="ModelContainerImpl" type="String"
                value="com.lhs.ccb.cfw.cda.servicelayer.model.WebModelContainer"
                comment="The implementation of the model container." />

            <!-- - When set to "true" force application to send only changed attributes
                - to the CORBA server. - "false" means that all attrubutes will be sent to
                the CORBA server. - This flag doesn't affect HTTP communication. -->
            <KeyValue key="SendOnlyChangedData" type="Boolean" value="true"
                comment="" />


            <!-- - Permission checker class to be used by the client framework. -->

            <KeyValue key="PermissionChecker" type="String"
                value="com.lhs.ccb.cfw.wcs.security.CFWPermissionChecker" comment="" />

            <!-- - Service box in navigation pane enabling. -->
            <KeyValue key="NavigationPaneServiceBoxEnabled" type="String"
                value="true" comment="Enables the criteria service box above the navigation pane" />

            <KeyValue key="NavigationPaneServiceBoxAlias" type="String"
                value="coll" comment="Alias for DCX" />

            <!-- - Default service box workflow file. - When the service box in the
                navigation pane is enabled, this will be the workflow file used by it. -->
            <KeyValue key="DefaultServiceBoxWorkflow" type="String"
                value="com/lhs/wmx/servicebox/resource/NavigationServiceBoxWorkflow.xml" />

            <Node name="ModelConfigs">
                <KeyValue key="PaymentPlanModelConfig" type="String"  value="com/lhs/dcx/paymentplan/resource/PaymentPlanModelConfig.xml"  comment="" />
                <KeyValue key="TaskModelConfig" type="String"  value="com/lhs/dcx/task/resource/TaskModelConfig.xml" comment="" />
                <KeyValue key="UtilModelConfig" type="String"  value="com/lhs/dcx/util/resource/UtilModelConfig.xml" comment="" />
                <KeyValue key="CollectionAgencyModelConfig"  type="String" value="com/lhs/dcx/agency/resource/CollectionAgencyModelConfig.xml"   comment="" />
                <KeyValue key="WorkflowDefinitionSetupModelConfig"   type="String"  value="com/lhs/dcx/workflowdefinition/resource/WorkflowDefinitionSetupModelConfig.xml"   comment="" />
                <KeyValue key="SampleJobModelConfig" type="String"  value="com/lhs/dcx/batchjob/resource/SampleJobModelConfig.xml"  comment="" />
                <KeyValue key="JobModelConfig" type="String" value="com/lhs/wmx/batchjob/resource/JobModelConfig.xml" comment=""/>
                <KeyValue key="JobModelConfigDcx" type="String"  value="com/lhs/dcx/batchjob/resource/JobModelConfig.xml" comment="" />
                <KeyValue key="CollectionFeeModelConfig" type="String" value="com/lhs/dcx/debtmanagement/resource/CollectionFeeModelConfig.xml"  comment="" />
                <KeyValue key="WorkqueueModelConfig" type="String" value="com/lhs/wmx/workqueue/resource/WorkqueueModelConfig.xml" comment="" />
                <KeyValue key="WorkgroupModel" type="String" value="com/lhs/wmx/workgroup/resource/WorkgroupModelConfig.xml" comment="" />
                <KeyValue key="SystemSettingsModelConfig" type="String" value="com/lhs/wmx/user/resource/SystemSettingsModelConfig.xml" comment=""/>
                <KeyValue key="AgentModelConfig" type="String" value="com/lhs/wmx/agent/resource/AgentModelConfig.xml" comment="" />
                <KeyValue key="WorkflowModelConfig" type="String" value="com/lhs/wmx/workflow/resource/WorkflowModelConfig.xml" comment=""/>
                <KeyValue key="EventModelConfig" type="String" value="com/lhs/wmx/event/resource/EventModelConfig.xml" comment=""/>
            </Node>

            <!-- - Hook that is called from the client framework after a Service Accessor
                (Service Object) is created - This class reinitialises the Business unit
                and the dealer for the user -->
            <KeyValue key="UserInitialisation" type="String"
                value="com.lhs.wmx.util.ClientUserInitialisation" />

            <!-- - User attributes names,(Stored in user session by UserPropertiesFacade)
                whose chage should be observed and, as a result a SESSION.CHANGE will be
                performed on the reference connection. - Note the attribute names should
                be separated from each other by comma(,). - - Used by: UserAttributesObservable.java -->
            <KeyValue key="ObservedUserAttributes" type="String" value="BU_ID" />

            <!-- F305180_dcx: Set the PDF generator resources path -->
            <KeyValue key="PDFResourcesPath" type="String"
                value="com/lhs/dcx/pdf/resource/" />

            <!-- Branding options -->
            <Node name="Branding">

                <!-- - The class that implements the branding for this application. If
                    no value is specified the default framework branding implementation is used. -->
                <KeyValue key="Class" type="String"
                    value="com.lhs.wmx.util.BusinessUnitBrandingAdapter" />

                <!-- - List all business units as nodes that have a different appearance
                    as the default. The name of the node is the business unit identifier. -->
                <Node name="2">
                    <KeyValue key="StyleSheet_bscs_main" type="String"
                        value="webresources/css/bscs_main.css" comment="Path to the stylesheet used for this business unit." />
                    <KeyValue key="StyleSheet_bscs_main_expanded" type="String"
                        value="webresources/css/bscs_main_expanded.css"
                        comment="Path to the expanded stylesheet used for this business unit." />
                    <KeyValue key="StyleSheet_bscs_dojo" type="String"
                        value="webresources/css/bscs_dojo.css" comment="Path to the dojo stylesheet used for this business unit." />
                </Node>

            </Node>

            <Node name="WorkflowEntityContentRenderer">

                <!-- Default renderer configured here -->
                <KeyValue key="Renderer" type="String"
                    value="com.lhs.wmx.workflow.controller.WorkflowEntityTableRenderer"
                    comment="The default class used for rendering." />
                <KeyValue key="View" type="String"
                    value="/workflow/include/TableWorkflowEntityOverview.jsp" comment="The JSP fragment used for rendering." />
                <!-- Default renderer, don't delete it -->
                <Node name="DefaultContentRenderer">
                    <KeyValue key="Renderer" type="String" value="com.lhs.wmx.workflow.controller.WorkflowEntityTableRenderer" comment="The default class used for rendering."/>
                    <KeyValue key="View" type="String" value="/workflow/include/TableWorkflowEntityOverview.jsp" comment="The JSP fragment used for rendering."/>

                    <!-- Even if market with 'Y' or 'B' in WORKFLOW_PART_ATTRIBUTE.GUI_IND, these attributes must not be displayed -->
                    <Node name="FilteredAttributes">
                        <KeyValue key="CUSTOMER" type="String" value="*" comment="All CUSTOMER part attributes should not be displayed"/>
                        <KeyValue key="INVOICE" type="String" value="BILLING_ACCOUNT_PKEY, BILLING_ACCOUNT_BALANCE, BILLING_ACCOUNT_OVERDUE_AMOUNT" comment="INVOICE part attributes that should not be displayed"/>
                        <KeyValue key="BILLING_ACCOUNT" type="String" value="*" comment="All BILLING_ACCOUNT part attributes should not be displayed"/>
                    </Node>
            </Node>

            </Node>

            <!-- This will identify the used scope used to search  properly. -->
            <KeyValue key="Scope" type="String" value="DCS" comment="Scope used to handle searches." />

            <!-- List of files containing the client's application context configuration -->
            <Node name="ApplicationContextConfigs">
                <KeyValue key="rootApplicationContext-dcx.xml" value=""
                    comment="The first application context configuration file of the OMX client" />
            </Node>

        </Node>
        <Node name="DCX Settings">
            <KeyValue key="FeedbackParDescriton" type="String" value="Feedback Part"
                comment="Feedback part short descritpion for the collection agency feedback combo" />
            <KeyValue key="FeedbackAttribute" type="String" value="FEEDBACK_REASON"
                comment="Attribute short description for the collection agency feedback combo" />
        </Node>



    </ComponentRegistry>