# Default values for bghChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  bgh:
    repoPath:
    pullPolicy:
    registry:
      url:
  bgh-init-customized:
    repoPath:
    pullPolicy:
    registry:
      url:
  init-wait-for-data:
    repoPath:
    pullPolicy:
    registry:
      url:
  init-wait-for-xrefs:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  bgh:
    name: "eric-bss-eb-bgh"
    tag: "22.15.12"
  bgh-init-customized:
#   Example for customization:
#    name: bscs/batch-init
#    directory: /external-files
    name:
    tag:
    directory:
  init-wait-for-data:
    name: "eric-bss-eb-wait-for-condition"
    tag: "22.15.12"
  init-wait-for-xrefs:
    name: "eric-bss-eb-wait-for-condition"
    tag: "22.15.12"

# To generate tracefiles, it is necessary set the tracefile name in the variables below.
# These files will be stored in the log PVC.
tracingAndLogging:
  bscsErrorTimestamp: ""
  # dtaTracefile: "dta.bgh.trc"
  dtaTracefile: ""
  # udrTracefile: "udr.bgh.trc"
  udrTracefile: ""
  # dxlTracefile: "dxl.bgh.trc"
  dxlTracefile: ""

replicaCount: 1

restartPolicy: Always

metadataName: eric-bss-eb-bgh

# Grace period for POD termination, in which the POD can shut down gracefully.
# After that period, k8s will terminate the POD un-gracefully (SIGKILL).
# Adapt this value in case the POD needs more time to terminate gracefully,
# Note, after the POD has terminated gracefully, the terminationGracePeriodSeconds is stopped immediately.
#       So it does not harm to specify a big value here.
terminationGracePeriodSeconds: 60

#DATA_RETRY_TIME, DATA_RETRY_TIME_MAX
#By default, there is no definition for a time interval in which applications try to reconnect to DaTA.
#If you set the environment variable, the value represents the time interval an application waits
#until it tries to reconnect to DaTA.
#Subsequent connection retries are performed under the following conditions:
# - A double time interval has elapsed and has exceeded a maximum of 60 seconds.
# - A double time interval has elapsed and the value specified by DATA_RETRY_TIME_MAX has been exceeded
dataRetry:
  dataRetryTime:
  dataRetryTimeMax:

bghRacSetup:
  waitTime: 500
  totalWaitTime: 30
  numAttempts: 60

# Customizable start parameters for bgh
startParameters:
  # -a
  applicationNumber: "0"
  # -n
  numberOfBusinessDocumentsPerDirectory: "5000"
  # -t
  traceModeLevel: "0"
  # -u additional DXL routing for a business unit
  businessUnitId:

resources:
  limits:
    cpu: 1000m
    memory: 10Gi
  requests:
    cpu: 100m
    memory: 256Mi

#A local nodeSelector definition has priority over the global definition above.
#nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b


suffix:

tnsnames:
  bscsdb: '{{ tpl .Values.global.tnsnames.bscsdb . }}'

sqlnet:
  ora: '{{ tpl .Values.global.sqlnet.ora . }}'

#Parameters used for logging
logging:
  #"handlers" specifies a comma separated list of log Handler classes
  #These handlers will be installed during VM startup
  #Note that these classes must be on the system classpath
  handlers: "ProcessIDFileHandler"

  #Logging level
  level: "SEVERE"

  #Log level for processIDFileHandler
  # Possible Levels in ascending order FINEST (lowest value), FINER, FINE, CONFIG, INFO, WARNING, SEVERE (highest value)
  processIDFileHandlerLevel: "SEVERE"

  #Properties of java.util.logging.FileHandler
  FileHandlerFormatter: "java.util.logging.SimpleFormatter"
  FileHandlerAppend: false

  #Level of logger named "FOP" which is the FOUserAgent-Logger
  FOPLevel: "SEVERE"

#OpenText Exstream HTTP(S) 1.1 POST Connection
httpExstreamUrl:
  # fqdn for Exstream Server
  # host: "myExstreamServer.myDomain.com"  # example value
  host: ""
  # Port Exstream Server, e. g. 31717
  port:

# Exstream from OpenText
exstream:
  securityTls:
    # Switch to enable secure tls connections to exstream.
    enable: true
    # Conditional, if tls to exstream is enabled: Name of the client secret
    # clientSecretName: "eric-bss-eb-exstream-client-secret"  # example value
    clientSecretName: ""
    # Conditional, if tls to exstream is enabled: Filename of the exstream client certificate
    # Note, this filename has to match the key of the key-value pair in the data section of the exstream secret file.
    # exstreamClientCertificateFileName: "exstream-ca-certificate.pem"  # example value
    exstreamClientCertificateFileName: ""

#Business Config Files - customizable configmaps
overrideConfigmap:
  # Default configmap: eric-bss-eb-bgh-plugin-registry.xml
  pluginRegistryXml:
  # Default configmap: eric-bss-eb-bgh-rac-setup.xml
  racSetupXml:
  # Default configmap: eric-bss-eb-bgh-logging.properties
  loggingProperties:
