# Default values for dmfjobChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  dmf:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  dmf:
    name: "eric-bss-eb-dmf"
    tag: "22.15.12"
  init-copydbscripts:
    name: "eric-bss-eb-dbscripts"
    tag: "22.15.12"

#A local nodeSelector definition has priority over the global definition.
nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b

#Example:
#nodeSelector:
#  kubernetes.io/hostname: "<hostname>"

standardpar:
#Presence of the RETENTION_PERIOD_SAMPLE_SETUP
#Mandatory, default value false.
#Setup has to be reviewed and adapted to the local requirements.
#Set to true after the review to activate the installation.
  RETENTION_PERIOD_SAMPLE_SETUP: false

standardupgrade:
  MIG_PROJECT_LABEL: "bscsdb"
  ERROR_MAX_NUM: 0
  TOTAL_PROCESS_NUM: 0
  TRACE_LEVEL: 2

tnsnames:
  bscsdb: '{{ tpl .Values.global.tnsnames.bscsdb . }}'
  bscsdb_admin: '{{ tpl .Values.global.tnsnames.bscsdb_admin . }}'
  rtxdb: '{{ tpl .Values.global.tnsnames.rtxdb . }}'
  rtxdb_admin: '{{ tpl .Values.global.tnsnames.rtxdb_admin . }}'

sqlnet:
  ora: '{{ tpl .Values.global.sqlnet.ora . }}'

bscsToRtxNetDescriptor: '{{ tpl .Values.global.bscsToRtxNetDescriptor . }}'
rtxToBscsNetDescriptor: '{{ tpl .Values.global.rtxToBscsNetDescriptor . }}'

#Business Config Files - customizable configmaps
overrideConfigmap:
  # Default configmap: eric-bss-eb-dmfjob-standard-res.xml
  dmfjobStandardResXml:
  dmfjobStandardParXml:
