apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-sms-rootapplicationcontext-sms-server.xml
data:
  rootApplicationContext-sms-server.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:util="http://www.springframework.org/schema/util"
           xmlns:tx="http://www.springframework.org/schema/tx"
           xmlns:aop="http://www.springframework.org/schema/aop"
           xmlns:context="http://www.springframework.org/schema/context"
           xsi:schemaLocation="
           http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
           http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.3.xsd
           http://www.springframework.org/schema/tx  http://www.springframework.org/schema/tx/spring-tx-4.3.xsd
           http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-4.3.xsd
           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.3.xsd"
           default-autowire="byName">

        <context:annotation-config/>

        <import resource="classpath*:applicationContext-sfw-passwordManagement.xml" />

        <bean id="vaultClientManager"  class="com.lhs.ccb.sfw.security.password.vault.VaultClientManager">
            <property name="applicationName" value="sms_server"/>
        </bean>
    </beans>
