apiVersion: v2
appVersion: "1.0"
description: The root Helm chart for license solution
name: eric-bss-eb-license
version: 22.15.12+0

dependencies:
- name: eric-bss-eb-lem-rbac
  version: 22.15.12+0
  repository: file://./charts/rbacChart
  condition: eric-bss-eb-lem-rbac.enabled

- name: eric-bss-eb-lem-networkpolicies
  version: 22.15.12+0
  repository: file://./charts/networkpoliciesChart
  condition: eric-bss-eb-lem-networkpolicies.enabled

- name: eric-bss-eb-lem
  version: 22.15.12+0
  repository: file://./charts/lemChart
