apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cch-registry.xml
data:
  CCH_Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC "ComponentRegistry.dtd" "../ComponentRegistry.dtd">
    <!-- CCH Component Registry. -->
    <ComponentRegistry>
      <Node name="CCH">
        <Node name="Modules">
          <KeyValue key="FilterModule" value="${BSCS_LIB}/librcc_filter.so" type="String"/>
          <KeyValue key="DiscountModule" value="${BSCS_LIB}/librcc_discount.so" type="String"/>
          <KeyValue key="AlertModule" value="${BSCS_LIB}/librcc_alert.so" type="String"/>
          <KeyValue key="RolloverModule" value="${BSCS_LIB}/librcc_rollover.so" type="String"/>
          <KeyValue key="XBalanceActionModule" value="${BSCS_LIB}/librcc_xbalance.so" type="String"/>
        </Node>
        <Node name="Balance">
          <KeyValue key="AggregateNegativeCharges" value={{ .Values.cchRegistry.balance.aggNegCharges | quote}} type="String"/>
          <Node name="PostpaidRemainingCredit">
            <KeyValue key="Amount" value={{ .Values.cchRegistry.balance.postpaidRemCredit.amount | quote}} type="Integer"/>
            <KeyValue key="Currency" value={{ .Values.cchRegistry.balance.postpaidRemCredit.currency | quote}} type="Integer"/>
          </Node>
          <Node name="ApplicationOrder">
            <KeyValue key="Bundle" value={{ .Values.cchRegistry.balance.appOrder.bundle | quote}} type="Integer"/>
            <KeyValue key="Normal" value={{ .Values.cchRegistry.balance.appOrder.normal | quote}} type="Integer"/>
            <KeyValue key="PrepaidCredit" value={{ .Values.cchRegistry.balance.appOrder.prepaidCredit | quote}} type="Integer"/>
            <KeyValue key="SimpleDiscount" value={{ .Values.cchRegistry.balance.appOrder.simpleDiscount | quote}} type="Integer"/>
            <KeyValue key="SpendingControl" value={{ .Values.cchRegistry.balance.appOrder.spendingControl | quote}} type="Integer"/>
          </Node>
        </Node>
        <Node name="Bundle">
          <KeyValue key="AlertCodeExpiration" value={{ .Values.cchRegistry.bundle.alertExpiration | quote}} type="Integer"/>
          <KeyValue key="AlertCodeNearExpiration" value={{ .Values.cchRegistry.bundle.alertNearExpiration | quote}} type="Integer"/>
        </Node>
        <Node name="EventProcessing">
          <KeyValue key="RoundCharges" value={{ .Values.cchRegistry.eventProc.roundCharges | quote}} type="Boolean"/>
          <Node name="OnlineCharging">
            <KeyValue key="NonUsage" value="RejectIfNoCredit" type="String"/>
            <KeyValue key="Usage" value="RejectIfNoCredit" type="String"/>
          </Node>
          <Node name="OfflineCharging">
            <KeyValue key="NonUsage" value="BookPartialAndSplit" type="String"/>
            <KeyValue key="Usage" value="BookAlways" type="String"/>
          </Node>
        </Node>
        <Node name="Tracing">
          <KeyValue key="Level" value={{ .Values.cchRegistry.tracingLevel | quote}} type="Integer"/>
        </Node>
        <Node name="ExternalInterface">
          <KeyValue key="MultiMessage" value={{ .Values.cchRegistry.extInterface.multiMessage | quote}} type="Boolean"/>
          <KeyValue key="SuppressPublicKey" value={{ .Values.cchRegistry.extInterface.suppressPubKey | quote}} type="Boolean"/>
        </Node>
        <Node name="RequestHistory">
          <KeyValue key="MaxNoPerApp" value={{ .Values.cchRegistry.reqHistory.maxNodePerApp | quote}} type="Integer"/>
        </Node>
        <Node name="HighAvailability">
          <KeyValue key="HAMode" value="false" type="Boolean" />
          <KeyValue key="DBBasedCurcyTax" value="false" type="Boolean" />
        </Node>
        <Node name="Throttling">
          <KeyValue key="ThrottlingInfoOn" value="false" type="Boolean" />
        </Node>
        <Node name="Discounting">
          <KeyValue key="RemainingChargeCalculation" value={{ .Values.cchRegistry.discounting.remChargeCalc | quote}} type="String" />
        </Node>
        <!-- 00343578_cch_1 -->
        <Node name="BIRProcessing">
          <KeyValue key="EmptyRemarkReasonId" value={{ .Values.cchRegistry.birProcessing.emptyRemarkReasonId | quote}} type="Integer" />
          <KeyValue key="DefaultRemarkReasonId" value={{ .Values.cchRegistry.birProcessing.defaultRemarkReasonId | quote}} type="Integer"/>
        </Node>
      </Node>
    </ComponentRegistry>
