apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-lem-lem.properties
data:
  lem.properties: |-
    # The directory for the FeatureStates.xml should not be changed because
    # it is shared by different LEM pods to synchronize the latest feature states.
    lem.featuresStatesFileName=/licensingsolution/resource/lic_lem/license_extension_files/feature_status/FeatureStates.xml

    # When the Sentinel RMS is not available, LEM will start trying to reestablish the connection.
    # When the number of connection retries exceeds the configured limit, LEM will be suspended.
    # During suspension LEM will not respond to queries or updates on the license feature status.
    # When RMS is running again and LEM could reestablish the connection, it will be reactivated
    # and be responsive again.
    lem.rmsConnectionRetryLimit= {{ .Values.rmsConnectionRetryLimit }}
