apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-lem-ior
  labels:
    run: eric-bss-eb-lem-ior
    app: eric-bss-eb-lem
    chart: {{ template "eric-bss-eb-lem.chart" . }}
    {{- include "eric-bss-eb-lem.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: ior-provider
      protocol: TCP
      port: 4322
      targetPort: 4322
    - name: orb-server-port
      protocol: TCP
      port: 43221
      targetPort: 43221
  selector:
    app: eric-bss-eb-lem
    app.kubernetes.io/instance: {{ .Release.Name }}