apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-fih-tnsnames.ora
data:
  tnsnames.ora: |-
    bscsdb =
{{ tpl .Values.tnsnames.bscsdb . | indent 6 }}
    dupdb =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}
    tapdb =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}
    rapdb =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}