{{ if .Values.global.ingress.enabled }}
{{ if or (index .Values "eric-bss-eb-ax" "enabled") (index .Values "eric-bss-eb-bp" "enabled") (index .Values "eric-bss-eb-cms" "enabled") (index .Values "eric-bss-eb-cpx" "enabled") (index .Values "eric-bss-eb-cx" "enabled") (index .Values "eric-bss-eb-dcx" "enabled") .Values.ingress.customHttpproxy.TRF}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: eric-bss-eb-trf-root-httpproxy
  annotations:
    {{ if .Values.global.ingress.ingressClass.TRF }}
    projectcontour.io/ingress.class: {{.Values.global.ingress.ingressClass.TRF}}
    {{ end }}
spec:
  virtualhost:
    fqdn: {{.Values.global.ingress.fqdn.TRF}}
    {{- if .Values.global.ingress.tlsSecretName.TRF }}
    tls:
      secretName: {{.Values.global.ingress.tlsSecretName.TRF}}
    {{- end }}
  includes:
{{ if index .Values "eric-bss-eb-ax" "enabled" }}
    - name: eric-bss-eb-ax-httpproxy
      conditions:
        - prefix: /ax_full
{{ end }}
{{ if index .Values "eric-bss-eb-bp" "enabled" }}
    - name: eric-bss-eb-bp-httpproxy
      conditions:
        - prefix: /custcare_bp
{{ end }}
{{ if index .Values "eric-bss-eb-cms" "enabled" }}
    - name: eric-bss-eb-cms-rest-httpproxy
      conditions:
        - prefix: /rest
    - name: eric-bss-eb-cms-soap-httpproxy
      conditions:
        - prefix: /wsi
{{ end }}
{{ if index .Values "eric-bss-eb-cpx" "enabled" }}
    - name: eric-bss-eb-cpx-httpproxy
      conditions:
        - prefix: /cpx
{{ end }}
{{ if index .Values "eric-bss-eb-cx" "enabled" }}
    - name: eric-bss-eb-cx-httpproxy
      conditions:
        - prefix: /custcare_cu
{{ end }}
{{ if index .Values "eric-bss-eb-dcx" "enabled" }}
    - name: eric-bss-eb-dcx-httpproxy
      conditions:
        - prefix: /dcx
{{ end }}
{{ range $ind, $custProxy := .Values.ingress.customHttpproxy.TRF }}
    - name: {{ $custProxy.httpproxyName }}
      conditions:
        - prefix: {{ $custProxy.httpproxyPrefix }}
{{ end }}
{{ if not .Values.global.ingress.ingressClass.OAM }}
{{ if index .Values "eric-bss-eb-admx" "enabled" }}
    - name: eric-bss-eb-admx-httpproxy
      conditions:
        - prefix: /admx_full
{{ end }}
{{ if index .Values "eric-bss-eb-wex" "enabled" }}
    - name: eric-bss-eb-wex-httpproxy
      conditions:
        - prefix: /wex
{{ end }}
{{ end }}
{{ end }}
{{ end }}
