# A Cron Job is launched for each of the items in the $cahJobs of values.yaml file.
# Every occurrence of cahJob variable is replaced during each range loop
# by the cahJobs item from the values.yaml file.
{{- range $cahJob := .Values.cahJobs }}
{{- if $.Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: "eric-bss-eb-cah-{{ $cahJob.name | lower }}"
  labels:
    app:  eric-bss-eb-cah
    chart: {{ template "eric-bss-eb-cah.chart" $ }}
    {{- include "eric-bss-eb-cah.kubernetesIoInfo" $ | nindent 4 }}
    heritage: {{ $.Release.Service }}
  annotations:
  {{- include "eric-bss-eb-cah.productInfo" $ | indent 4 }}
spec:
  schedule: {{ $cahJob.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ $cahJob.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $cahJob.successfulJobsHistoryLimit }}
  suspend: {{ $.Values.global.suspendCronJobs.cah }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: eric-bss-eb-cah
            {{- include "eric-bss-eb-cah.kubernetesIoInfo" $ | nindent 12 }}
            eric-bss-eb-network-database-client: 'true'
            eric-bss-eb-network-lem-client: 'true'
            eric-bss-eb-network-vault-client: 'true'
          annotations:
          {{- include "eric-bss-eb-cah.productInfo" $ | indent 12 }}
        spec:
          securityContext:
            {{- include "eric-bss-eb-cah.checkPodUserLoginData" $ | nindent 12 }}
          {{- if $.Values.global.rbac.sa_roles_create }}
          serviceAccountName: {{ $.Chart.Name }}-sa
          {{- end }}
          {{- if $.Values.global.imageCredentials.pullSecret }}
          imagePullSecrets:
            - name: {{ $.Values.global.imageCredentials.pullSecret }}
          {{- end }}
          containers:
            - name: eric-bss-eb-cah
              # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
              {{ $templDict := dict "Values" $.Values "containerKey" "eric-bss-eb-cah" }}
              image: "{{ template "eric-bss-eb-cah.registryUrl" $templDict }}/{{ template "eric-bss-eb-cah.repoPath" $templDict }}{{ index $.Values "images" $templDict.containerKey "name" }}:{{ index $.Values "images" $templDict.containerKey "tag" }}"
              imagePullPolicy: {{ template "eric-bss-eb-cah.pullPolicy" $templDict }}
              resources:
                limits:
                  memory: "{{ $.Values.resources.limits.memory}}"
                  cpu: "{{ $.Values.resources.limits.cpu}}"
                requests:
                  memory: "{{ $.Values.resources.requests.memory}}"
                  cpu: "{{ $.Values.resources.requests.cpu}}"
              env:
              - name: K8S_ENV
                value: "true"
              {{ if $.Values.global.databaseTls.enable }}
              - name: ORA_SEC_WLT
                value: "/oratns/secret"
              {{ end }}
              - name: NLS_LANG
                value: "{{ $.Values.global.nlsLang }}"
              - name: TZ
                value: "{{ $.Values.global.timezone }}"
              {{ if not $.Values.global.secretManager.enable }}
              - name: NO_SECRET_MANAGER
                value: "true"
              {{ end }}
              command: ["/bin/bash"]
              args: ["-c", "ulimit -c unlimited && mkdir -p {{ $.Values.global.coredumpDirectory }} && \
                            ./cah {{ $cahJob.startParameters.traceModeLevel }}  \
                              -a  {{ $cahJob.startParameters.actionParameter }} \
                                  {{ $cahJob.startParameters.optionalParameters }}"]
              volumeMounts:
              - name: pwdmgr-security-volume
                mountPath: /workdir/PWDMGR_SECURITY
              - name: logs-volume
                mountPath: /log
              - name: coredump-volume
                mountPath: "{{ $.Values.global.coredumpDirectory }}"
              - name: archive-volume
                mountPath: {{ $cahJob.folderToArchive }}
              - name: tnsnames-ora-volume
                mountPath: /oratns/tnsnames.ora
                subPath: tnsnames.ora
              - name: sqlnet-ora-volume
                mountPath: /oratns/sqlnet.ora
                subPath: sqlnet.ora
              {{ if $.Values.global.databaseTls.enable }}
              - name: wallet-volume
                mountPath: /oratns/secret
              {{ end }}
              {{ if and ($.Values.global.secretManager.enable) ($.Values.global.secretManager.vault.caSecretName) }}
              - name: secretmanager-tls-volume
                mountPath: "/tls/secretManager/vault"
                readOnly: true
              {{ end }}
              - name: vault-clientcfg-xml-volume
                mountPath: /ericssonbilling/resource/vault-clientcfg/vault-clientcfg.xml
                subPath: vault-clientcfg.xml
              - name: vault-clientcfg-dtd-volume
                mountPath: /ericssonbilling/resource/vault-clientcfg/vault-clientcfg.dtd
                subPath: vault-clientcfg.dtd
          {{- if $cahJob.nodeSelector }}
          nodeSelector: {{ toYaml $cahJob.nodeSelector | nindent 12 }}
          {{- else if $.Values.global.nodeSelector }}
          nodeSelector: {{ toYaml $.Values.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if $cahJob.affinity }}
          affinity: {{ toYaml $cahJob.affinity | nindent 12 }}
          {{- else if $.Values.global.affinity }}
          affinity: {{ toYaml $.Values.global.affinity | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          volumes:
          - name: pwdmgr-security-volume
            persistentVolumeClaim:
              claimName: eric-bss-eb-pvc-pwdmgr-security
          - name: logs-volume
            persistentVolumeClaim:
              claimName: eric-bss-eb-pvc-logs
          - name: coredump-volume
            persistentVolumeClaim:
              claimName: eric-bss-eb-pvc-coredump
          - name: archive-volume
            persistentVolumeClaim:
              claimName: eric-bss-eb-cah-pvc-archive
          - name: tnsnames-ora-volume
            configMap:
              name: eric-bss-eb-cah-tnsnames.ora
          - name: sqlnet-ora-volume
            configMap:
              name: eric-bss-eb-cah-sqlnet.ora
          - name: vault-clientcfg-xml-volume
            configMap:
              name: eric-bss-eb-cah-vault-clientcfg.xml
          - name: vault-clientcfg-dtd-volume
            configMap:
              name: eric-bss-eb-cah-vault-clientcfg.dtd
          {{ if and ($.Values.global.secretManager.enable) ($.Values.global.secretManager.vault.caSecretName) }}
          - name: secretmanager-tls-volume
            secret:
              secretName: "{{ $.Values.global.secretManager.vault.caSecretName }}"
              items:
              - key: {{ $.Values.global.secretManager.vault.caCertificate }}
                path: ca.pem
          {{ end }}
          {{ if $.Values.global.databaseTls.enable }}
          - name: wallet-volume
            secret:
              secretName: "{{ $.Values.global.databaseTls.clientSecretName }}"
          {{ end }}
      backoffLimit: {{ $cahJob.backoffLimit }}
---
{{- end}}
