apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-pwdmgrjob-sqlnet.ora
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1005"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  sqlnet.ora: |-
{{ tpl .Values.sqlnet.ora . | indent 4 }}
