apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-pwdmgrjob-tnsnames.ora
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1005"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  tnsnames.ora: |-
    bscsdb =
{{ tpl .Values.tnsnames.bscsdb . | indent 6 }}
    rtxdb =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}
