apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-admx-registry.xml
data:
  ADMX_Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <!-- ADMX -->

    <ComponentRegistry>
    <Node name="FUNC_WCLT">

        <!--
          - Application name used for window titles.
            - This value is directly accessible through method ApplicationSettings.getApplicationName()
            - This key is also used as parent permission key for initialization of the PermissionChecker
        -->
        <KeyValue key="ApplicationName" type="String" value="ADMX" comment="The name of the web client application"/>

        <!-- Application version TODO: used anywhere? -->
        <KeyValue key="ApplicationVersion" type="String" value="1.0" comment="The version of the web client application"/>

        <!-- Application name as defined in APP_MODULES -->
        <KeyValue key="ModuleName" type="String" value="ADMX" comment="The module name as defined in APP_MODULES"/>

        <!-- Product identification. Allow values are BSCSiX, iXRating and iXBilling -->
        <KeyValue key="Product" type="String" value="BSCSiX" comment="Product identification."/>

        <!-- Deployment scope. Available values are BSCS and CBIO. -->
        <KeyValue key="DeploymentScope" type="String" value="CBIO" comment="Deployment scope"/>

        <!--
          - Starts the User settings Solutionunit directly after the user has logged into the
            client. The User settings Solutionunit is a solution unit that can be used to force
            the user to do some initial settings like selecting a business unit or a dealer.
            The workflow of the User settings Solutionunit is defined by the client but the name
            of the SolutionUnit must always be "UserSettings".
        -->
        <KeyValue key="StartUserSettingsSU" type="Boolean" value="false" comment="Enables/Disables user settings SU"/>


        <!-- SOI name for security initialization -->
        <KeyValue key="SoiNameForSecurity" type="String" value="SECURITY" comment="The name of the security SOI"/>

        <!-- SOI version for security initialization -->
        <KeyValue key="SoiVersionForSecurity" type="String" value="3" comment="The version of the security SOI"/>

        <!-- The SOI name the client should connect to. -->
        <KeyValue key="CIL" type="String" value="CIL" comment="The name of the SOI."/>

        <!-- The SOI version the client should connect to. -->

        <KeyValue key="CIL_Version" type="String" value="7" comment="The version of the SOI."/>

        <!--
          - The implementation of the ModelContainer
          - Default is com.lhs.ccb.cfw.cda.servicelayer.model.DefaultModelContainer
          -
          - Used by SoiContainerFactory
        -->
        <KeyValue key="ModelContainerImpl" type="String" value="com.lhs.ccb.cfw.cda.servicelayer.model.WebModelContainer" comment="The implementation of the model container"/>

        <!--
          - Client/server data exchange options (it doesn't affect HTTP communication):
            - true: the client will send only changed attributes to the CORBA server
            - false: the client will send all attrubutes to the CORBA server
        -->
        <KeyValue key="SendOnlyChangedData" type="Boolean" value="true" comment=""/>

        <!-- Permission checker class to be used by the client framework -->
        <KeyValue key="PermissionChecker" type="String" value="com.lhs.admx.util.ClientPermissionChecker" comment=""/>

        <!--
          - Specifies the root path where help files are stored
            - Help root path is a directory located in the web server
            - example: help path is "help". Then the root direcory for the help files is
                       http://host:port/CMS/help where http://host:port/CMS is the path of the deployed application.
            - If the root help path should have different sub directories these sub directories
              must be specified in the workflow configuration xml file. For this have a look at
              workflowconfiguration.dtd.
        -->
        <KeyValue key="HelpRootPath" type="String" value="help" comment=""/>

          <!--
          - The configuration files for default models (each default model must have a configuration file)
          - used by: ModelMetaDataRepository
        -->
        <Node name="ModelConfigs">
            <KeyValue key="ReferenceDataModels" type="String" value="com/lhs/admx/referencedata/resource/ReferenceDataModelConfig.xml" comment=""/>
            <KeyValue key="PMWarningModel" type="String" value="com/lhs/admx/warning/model/resource/PMWarningModelConfig.xml" comment="" />
            <KeyValue key="RDWarningModel" type="String" value="com/lhs/admx/warning/model/resource/RDWarningModelConfig.xml" comment="" />
            <KeyValue key="CSInfrastructureModels" type="String" value="com/lhs/admx/infrastructure/resource/CSInfrastructureModelConfig.xml" comment=""/>
            <KeyValue key="UserModels" type="String" value="com/lhs/admx/ua/resource/UserModelConfig.xml" comment=""/>
            <KeyValue key="RoleModels" type="String" value="com/lhs/admx/ua/resource/RoleModelConfig.xml" comment=""/>
            <KeyValue key="CMSDataModels" type="String" value="com/lhs/admx/util/resource/CMSDataModelConfig.xml" comment=""/>
            <KeyValue key="MemoTemplatesModels" type="String" value="com/lhs/admx/templates/resource/MemoTemplatesModelConfig.xml" comment=""/>
            <KeyValue key="TemplatesModels" type="String" value="com/lhs/admx/templates/resource/TemplatesModelConfig.xml" comment=""/>
            <KeyValue key="TemplatesASModels" type="String" value="com/lhs/admx/templates/resource/TemplatesASModelConfig.xml" comment=""/>
            <KeyValue key="ScheduledJobModels" type="String" value="com/lhs/admx/job/resource/JobModelConfig.xml" comment=""/>
            <KeyValue key="LicenseCheckModels" type="String" value="com/lhs/admx/user/resource/SecurityModelConfig.xml" comment=""/>
            <KeyValue key="PAEConfigModels" type="String" value="com/lhs/admx/archive/resource/PAEConfigModelConfig.xml" comment=""/>
            <KeyValue key="AvailableFunctionsModels" type="String" value="com/lhs/admx/availablefunctions/resource/AvailableFunctionsModelConfig.xml" comment=""/>
            <KeyValue key="DataRightsModels" type="String" value="com/lhs/admx/ua/resource/DataRightsModelConfig.xml" comment=""/>
            <KeyValue key="BillMediaModels" type="String" value="com/lhs/admx/billmedia/resource/BillMediaModelConfig.xml" comment=""/>
            <KeyValue key="NetworkModels" type="String" value="com/lhs/admx/topology/resource/NetworkModelConfig.xml" comment=""/>
        </Node>

        <!--
          - Global Resource bundle file for general error messages. It should be used to define
            global error messages that can occur in several pages.
            - used by: ErrorUtil class of CFW to obtain the error messages
        -->
        <KeyValue key="CommonErrorBundle" type="String" value="com/lhs/admx/util/resource/CommonErrorsBundle" comment=""/>

            <!--
          - Hook that is called from the client framework after a Service Accessor (Service Object) is created
            - this class reinitialises the Business unit and the dealer for the user
        -->
        <KeyValue key="UserInitialisation"  type="String"  value="com.lhs.admx.util.ClientUserInitialisation"/>

            <!-- Branding options -->
        <Node name="Branding">

            <!--
              - The class that implements the branding for this application.
                If no value is specified the default framework branding implementation is used.
            -->
            <KeyValue key="Class" type="String" value="com.lhs.ccb.cfw.wcs.branding.BusinessUnitBrandingAdapter"/>

            <!--
              - List all business units as nodes that have a different appearance as the default.
                The name of the node is the business unit identifier.
            -->
            <!--
              - List all business units as nodes that have a different appearance as the default.
                The name of the node is the business unit identifier.

            <Node name="2">
                <KeyValue key="StyleSheet_bscs_main" type="String" value="webresources/css/bscs_main.css" comment="Path to the stylesheet used for this business unit."/>
                <KeyValue key="StyleSheet_bscs_main_expanded" type="String" value="webresources/css/bscs_main_expanded.css" comment="Path to the expanded stylesheet used for this business unit."/>
                <KeyValue key="StyleSheet_bscs_dojo" type="String" value="webresources/css/bscs_dojo.css" comment="Path to the dojo stylesheet used for this business unit."/>
            </Node>
            -->

        </Node>

         <!--
          - Comma separated list of user attributes that must be observed for changes in order to perform a SESSION.CHANGE on the reference connection.
            - note: they are stored in the user session by UserPropertiesFacade
            - used by: UserAttributesObservable.java
        -->
        <KeyValue key="ObservedUserAttributes" type="String" value=""/>

        <!-- Class that filters the data containers before they are processed for execution (used for future dated requests) -->
        <KeyValue key="CustomizedExecutionFilter" type="String" value="com.lhs.admx.job.model.JobCommitFilter"/>

        <!-- specifies the default row number of the MSISDN range table which are used for LCA and SLF batch job creation -->
        <KeyValue key="DefaultMsisdnRangeTableSize" type="Integer" value="1" comment="default MSISDN range table size" />

        <!-- specifies the page size of users table -->
        <KeyValue key="DefaultPageSize" type="Integer" value="10" comment="default users range table size" />

        <!--
           List of files containing the client's application context configuration
         -->
        <Node name="ApplicationContextConfigs">
            <KeyValue key="rootApplicationContext-admx.xml" value=""
                      comment="The first application context configuration file of the OMX client" />
        </Node>

        <!-- specifies the suffixes for solution unit entries in Modules table -->
        <KeyValue key="SolutionUnitSuffixes" type="String" value="SU,WE"/>

        <Node name="BillMediaStyleSheetComboBox">
            <KeyValue key="business-doc-excelss-1.0.xslt" type="String" value="business-doc-excelss-1.0.xslt" comment=""/>
            <KeyValue key="business-doc-csv-txt-1.0.xslt" type="String" value="business-doc-csv-txt-1.0.xslt" comment=""/>
            <KeyValue key="business-doc-html5-1.0.xslt" type="String" value="business-doc-html5-1.0.xslt" comment=""/>
            <KeyValue key="business-doc-xml-1.0.xslt" type="String" value="business-doc-xml-1.0.xslt" comment=""/>
            <KeyValue key="business-doc-fo1.1-1.0.xslt" type="String" value="business-doc-fo1.1-1.0.xslt" comment=""/>
        </Node>

    </Node>
    </ComponentRegistry>
