apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-admx-http
  labels:
    run: eric-bss-eb-admx-http
    app: eb-java-admx
    chart: {{ template "eric-bss-eb-admx.chart" . }}
    {{- include "eric-bss-eb-admx.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-admx.productInfo" . | indent 4 }}
    {{ if .Values.tomcat.secretName }}
    projectcontour.io/upstream-protocol.tls: "8443,admx-http"
    {{ end }}
    projectcontour.io/max-connections: "{{ .Values.ingress.max_connections }}"
    projectcontour.io/max-pending-requests: "{{ .Values.ingress.max_pending_requests }}"
    projectcontour.io/max-requests: "{{ .Values.ingress.max_requests }}"
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http-admx
      protocol: TCP
      name: admx-http
  selector:
    app: eb-java-admx
    app.kubernetes.io/instance: {{ .Release.Name }}
