apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-wfmssupporttool-wma.properties
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-50"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
data:
  wma.properties: |
    ######################################################
    # Class that implements default Task handler         #
    ######################################################
    TaskHandler.Default=com.lhs.wms.task.TaskHandler

    ######################################################
    # Max number of unsuccessful executions retry        #
    # inside of a custom activity node.                  #
    ######################################################
    MaxErrorExecutionCount={{.Values.wma.properties.MaxErrorExecutionCount}}

    ######################################################
    # Enable last executed action update                 #
    # Must be false for migration tool                   #
    ######################################################
    EnableLastExecutedActionUpdate={{.Values.wma.properties.EnableLastExecutedActionUpdate}}

    ######################################################
    # Bind name to register wrapped data                 #
    # source in JNDI                                     #
    ######################################################
    WrappedDataSourceBindName=jdbc/lhsdbwma
