apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-wfmssupporttool-hibernate.properties
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-50"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
data:
  hibernate.properties: |
    ####################################
    # Hibernate Configuration for JBPM #
    ####################################

    hibernate.dialect org.hibernate.dialect.Oracle10gDialect


    #################################
    ### Datasource configuration  ###
    #################################

    hibernate.jndi.class com.lhs.ccb.sfw.application.naming.ApplicationInitialContextFactory
    hibernate.connection.datasource jdbc/lhsdb
