apiVersion: batch/v1
kind: Job

metadata:
  name: eric-bss-eb-job-wfmssupporttool-importworkflows
  labels:
    app: eric-bss-eb-wfmssupporttool
    chart: {{ template "eric-bss-eb-wfmssupporttool.chart" . }}
    {{- include "eric-bss-eb-wfmssupporttool.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-wfmssupporttool.productInfo" . | indent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: eric-bss-eb-wfmssupporttool
        chart: {{ template "eric-bss-eb-wfmssupporttool.chart" . }}
        eric-bss-eb-network-database-client: 'true'
        eric-bss-eb-network-vault-client: 'true'
        {{- include "eric-bss-eb-wfmssupporttool.kubernetesIoInfo" . | nindent 8 }}
        heritage: {{ .Release.Service }}
      annotations:
      {{- include "eric-bss-eb-wfmssupporttool.productInfo" . | indent 8 }}
    spec:
      securityContext:
        {{- include "eric-bss-eb-wfmssupporttool.checkPodUserLoginData" . | nindent 8 }}
      restartPolicy: Never
      {{- if .Values.global.rbac.sa_roles_create }}
      serviceAccountName: {{ .Chart.Name }}-sa
      {{- end }}
      {{- if $.Values.global.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.global.imageCredentials.pullSecret }}
      {{- end }}
      initContainers:
        - name: init-wait-for-pwdmgr
          # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
          {{ $templDict := dict "Values" .Values "containerKey" "init-wait-for-pwdmgr" }}
          image: "{{ template "eric-bss-eb-wfmssupporttool.registryUrl" $templDict }}/{{ template "eric-bss-eb-wfmssupporttool.repoPath" $templDict }}{{ index .Values "images" $templDict.containerKey "name" }}:{{ index .Values "images" $templDict.containerKey "tag" }}"
          imagePullPolicy: {{ template "eric-bss-eb-wfmssupporttool.pullPolicy" $templDict }}
          command: ["/bin/bash"]
          args: ["-c", "./waitForPwdMgr.sh /workdir/PWDMGR_SECURITY {{ $.Values.global.conditionCheckInterval }}"]
          volumeMounts:
          - name: pwdmgr-security-volume
            mountPath: /workdir/PWDMGR_SECURITY
        - name: init-logging-wfmssupporttool
          # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
          {{ $templDict := dict "Values" .Values "containerKey" "init-logging-wfmssupporttool" }}
          image: "{{ template "eric-bss-eb-wfmssupporttool.registryUrl" $templDict }}/{{ template "eric-bss-eb-wfmssupporttool.repoPath" $templDict }}{{ index .Values "images" $templDict.containerKey "name" }}:{{ index .Values "images" $templDict.containerKey "tag" }}"
          imagePullPolicy: {{ template "eric-bss-eb-wfmssupporttool.pullPolicy" $templDict }}
          command: ["/bin/sh"]
          args: ["-c","sed s/{HOSTNAME}/$HOSTNAME/g /ericssonbilling/log4j2.xml >> /ericssonbilling/resource/wms/support/log4j2.xml && mkdir -p /log/wfmssupporttool -m 750"]
          volumeMounts:
          - name: init-log4j2-xml-volume
            mountPath: /ericssonbilling/resource/wms/support
          - name: wfmssupporttool-log4j2-xml-volume
            mountPath: /ericssonbilling
          - name: logs-volume
            mountPath: /log
      containers:
        - name: eric-bss-eb-wfmssupporttool
          # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
          {{ $templDict := dict "Values" .Values "containerKey" "eric-bss-eb-wfmssupporttool" }}
          image: "{{ template "eric-bss-eb-wfmssupporttool.registryUrl" $templDict }}/{{ template "eric-bss-eb-wfmssupporttool.repoPath" $templDict }}{{ index .Values "images" $templDict.containerKey "name" }}:{{ index .Values "images" $templDict.containerKey "tag" }}"
          imagePullPolicy: {{ template "eric-bss-eb-wfmssupporttool.pullPolicy" $templDict }}
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory}}"
              cpu: "{{ .Values.resources.limits.cpu}}"
            requests:
              memory: "{{ .Values.resources.requests.memory}}"
              cpu: "{{ .Values.resources.requests.cpu}}"
          command: ["/bin/bash"]
          args: ["-c", "./scripts/run_WFMSSupportTool.sh -d resource/wfmssupporttool/workflows"]
          env:
          - name: K8S_ENV
            value: "true"
          - name: SOISRV_DATABASE_NAME
            value: "{{ .Values.global.bscsDb }}"
          - name: SOISRV_DATABASE_PORT
            value: "{{ int .Values.global.databaseServerPort }}"
          - name: SOISRV_DATABASE_SERVER
            value: "{{ .Values.global.databaseServerName }}"
          - name: BSCSDB
            value: "{{ .Values.global.bscsDb }}"
          - name: NLS_LANG
            value: "{{ .Values.global.nlsLang }}"
          - name: TZ
            value: "{{ .Values.global.timezone }}"
          {{ if .Values.global.databaseTls.enable }}
          - name: ORA_SEC_WLT
            value: "/oratns/secret"
          - name: TNS_ADMIN
            value: "/oratns"
          - name: WALLET_LOCATION
            value: "/oratns/secret"
          - name: SOISRV_TNS_ENTRY
            value: '{{ tpl .Values.tnsnames.bscsdb . | replace "\n" "" | nospace }}'
          {{ end }}
          {{ if .Values.global.ebTruststore.secretName }}
          - name: CERTIFICATE_PATH
            value: "-Djavax.net.ssl.trustStore=/ssl/{{ .Values.global.ebTruststore.trustStoreName }} \
                    -Djavax.net.ssl.trustStorePassword={{ .Values.global.ebTruststore.trustStorePassword }}"
          {{ end }}
          {{ if not $.Values.global.secretManager.enable }}
          - name: NO_SECRET_MANAGER
            value: "true"
          {{ end }}
          volumeMounts:
          - name: logs-volume
            mountPath: /log
          - name: workflows-volume
            mountPath: /ericssonbilling/resource/wfmssupporttool/workflows
          {{ if .Values.global.databaseTls.enable }}
          - name: wallet-volume
            mountPath: /oratns/secret
          {{ end }}
          {{ if .Values.global.ebTruststore.secretName }}
          - name: eb-trust-store-volume
            mountPath: "/ssl"
            readOnly: true
          {{ end }}
          - mountPath: /workdir/PWDMGR_SECURITY
            name: pwdmgr-security-volume
          - name: init-log4j2-xml-volume
            mountPath: /ericssonbilling/resource/wms/support/log4j2.xml
            subPath: log4j2.xml
          - name: wfmssupporttool-database-properties-volume
            mountPath: /ericssonbilling/resource/database.properties
            subPath: database.properties
          - name: wfmssupporttool-hibernate-properties-volume
            mountPath: /ericssonbilling/resource/wfms/support/hibernate.properties
            subPath: hibernate.properties
          - name: wfmssupporttool-jbpm-cfg-xml-volume
            mountPath: /ericssonbilling/resource/wfms/support/jbpm.cfg.xml
            subPath: jbpm.cfg.xml
          - name: vault-clientcfg-xml-volume
            mountPath: /ericssonbilling/resource/vault-clientcfg/vault-clientcfg.xml
            subPath: vault-clientcfg.xml
          - name: wfmssupporttool-sqlnet-ora-volume
            mountPath: /oratns/sqlnet.ora
            subPath: sqlnet.ora
          - name: wfmssupporttool-tnsnames-ora-volume
            mountPath: /oratns/tnsnames.ora
            subPath: tnsnames.ora
          - name: wfmssupporttool-wma-volume
            mountPath: /ericssonbilling/resource/wma.properties
            subPath: wma.properties
          - name: wfmssupporttool-rootappcontext-wfmssupporttool-volume
            mountPath: /ericssonbilling/resource/wms/support/rootApplicationContext-wfmssupporttool.xml
            subPath: rootApplicationContext-wfmssupporttool.xml
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector: {{ toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.global.affinity }}
      affinity: {{ toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      volumes:
      {{ if .Values.global.databaseTls.enable }}
      - name: wallet-volume
        secret:
          secretName: "{{ .Values.global.databaseTls.clientSecretName }}"
      {{ end }}
      {{ if .Values.global.ebTruststore.secretName }}
      - name: eb-trust-store-volume
        secret:
          secretName: {{ .Values.global.ebTruststore.secretName }}
      {{ end }}
      - name: init-log4j2-xml-volume
        emptyDir: {}
      - name: logs-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-logs
      - name: pwdmgr-security-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-pwdmgr-security
      - name: workflows-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-workflows
      - name: wfmssupporttool-database-properties-volume
        configMap:
          name: eric-bss-eb-wfmssupporttool-database.properties
      - name: wfmssupporttool-hibernate-properties-volume
        configMap:
          name: {{ .Values.overrideConfigmap.hibernateProperties | default "eric-bss-eb-wfmssupporttool-hibernate.properties" }}
      - name: wfmssupporttool-jbpm-cfg-xml-volume
        configMap:
          name: {{ .Values.overrideConfigmap.jbpmCfgXml | default "eric-bss-eb-wfmssupporttool-jbpm.cfg.xml" }}
      - name: wfmssupporttool-sqlnet-ora-volume
        configMap:
          name: eric-bss-eb-wfmssupporttool-sqlnet.ora
      - name: wfmssupporttool-tnsnames-ora-volume
        configMap:
          name: eric-bss-eb-wfmssupporttool-tnsnames.ora
      - name: wfmssupporttool-wma-volume
        configMap:
          name: eric-bss-eb-wfmssupporttool-wma.properties
      - name: wfmssupporttool-log4j2-xml-volume
        configMap:
          name: {{ .Values.overrideConfigmap.log4j2xml | default "eric-bss-eb-wfmssupporttool-log4j2.xml" }}
      - name: vault-clientcfg-xml-volume
        configMap:
          name: eric-bss-eb-wfmssupporttool-vault-clientcfg.xml
      - name: wfmssupporttool-rootappcontext-wfmssupporttool-volume
        configMap:
          name: {{ .Values.overrideConfigmap.rootApplicationContextWfmsSupportToolXml | default "eric-bss-eb-wfmssupporttool-rootappcontext-wfmssupporttool.xml" }}
  backoffLimit: 0
