{{- if .Values.global.rbac.sa_roles_create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa
roleRef:
  kind: Role
  name: eric-bss-eb-regular-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
