apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-evh-bir-ascii.ini
data:
  bir_ascii.ini: |
    , ; %
    P 1
    '1'  1          // Dummy call type field
    2    264 9      // BI_S_P_NUMBER                 - ADDRESS
    3    264 487    //                               - NUMBERING_PLAN_PKEY
    4    192 302    // BI_PURPOSE                    - BI_PURPOSE
    5    227 367    // BI_REMARK                     - REASON_ID
    6    227 90     //                               - REMARK
    7    215 5      // BI_REQ_AMOUNT                 - AMOUNT
    8    215 437    //                               - CURRENCY_PKEY
    9    215 8      //                               - GROSS_IND
    10   215 6      //                               - TAX
    11   216 450    // BI_REQ_VOLUME                 - UOM_PKEY
    12   216 3      //                               - VOLUME
    P 2
    1    200 5      // BI_AGGREGATE_CHARGE           - AMOUNT
    2    200 437    //                               - CURRENCY_PKEY
    3    201 450    // BI_AGGREGATE_VOLUME           - UOM_PKEY
    4    201 3      // NET_ELEMENT_ENTITY            - VOLUME
    5    199 307    // BI_BALANCE_ATTRIBUTE          - BALANCE_SEQUENCE
    6    198 317    // BI_BALANCE_IDENTIFICATION     - AGGREGATE_MONEY
    7    198 276    //                               - ACCOUNT_ID
    8    198 1013   //                               - ACCOUNT_TYPE
    9    223 1      // BI_BALANCE_SNAPSHOT_DATE      - TIMESTAMP
    10   223 493    //                               - TIME_ZONE_PKEY
    11   203 5      // BI_CREDIT_CHARGE              - AMOUNT
    12   203 437    //                               - CURRENCY_PKEY
    13   204 450    // BI_CREDIT_VOLUME              - UOM_PKEY
    14   204 3      //                               - VOLUME
    15   206 1      // BI_END_DATE                   - TIMESTAMP
    16   206 493    //                               - TIME_ZONE_PKEY
    17   207 1      // BI_NEXT_RESET                 - TIMESTAMP
    18   207 493    //                               - TIME_ZONE_PKEY
    19   225 5      // BI_REMAINING_CREDIT_CHARGE    - AMOUNT
    20   225 437    //                               - CURRENCY_PKEY
    21   226 450    // BI_REMAINING_CREDIT_VOLUME    - UOM_PKEY
    22   226 3      //                               - VOLUME
