apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-evh-registry.xml
data:
  Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE Registry PUBLIC "Registry.dtd" "Registry.dtd">

    <Registry>

        <!-- Location of CMN framework registry file-->
        <Link location="FUNC_FRMWK_CMN_Registry.xml"/>

        <!-- Location of component registry file. -->
        <!-- Must be last to allow overwriting of CMN framework settings. -->
        <Link location="EvhRegistry.xml" />
        <Link location="plugin_nk/EvhRegistry_nk.xml" />

    </Registry>
