# Default values for dlyChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  eric-bss-eb-dly:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  eric-bss-eb-dly:
    name: "eric-bss-eb-dly"
    tag: "22.15.12"

resources:
  limits:
    cpu: 1000m
    memory: 5Gi
  requests:
    cpu: 100m
    memory: 256Mi

dlyJobs:
  # CronJob for DLY with parameter -d
  - name: Job-Finance
    schedule: "0 1 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    # Customizable start parameters for dly
    startParameters:
      # 0 = trace off, 1 = trace on
      traceModeLevel: 1
      runParameters: "-d"

  # CronJob for DLY with parameter -om
  - name: Job-Billing
    schedule: "0 1 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    # Customizable start parameters for dly
    startParameters:
      # 0 = trace off, 1 = trace on
      traceModeLevel: 1
      runParameters: "-bill"

    # CronJob for DLY combining all other start parameters
  - name: Job-AllOthers
    schedule: "0 1 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    # Customizable start parameters for dly
    startParameters:
      # 0 = trace off, 1 = trace on
      traceModeLevel: 1
      runParameters: "-acc -om -coco -esh -fagr -roam -tok -uba -X"

#A local nodeSelector definition has priority over the global definition above.
#nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b

tnsnames:
  bscsdb: '{{ tpl .Values.global.tnsnames.bscsdb . }}'

sqlnet:
  ora: '{{ tpl .Values.global.sqlnet.ora . }}'
