apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-gmdrrs
  labels:
    run: eric-bss-eb-gmdrrs
    app: {{ template "eric-bss-eb-gmdrrs.name" . }}
    chart: {{ template "eric-bss-eb-gmdrrs.chart" . }}
    {{- include "eric-bss-eb-gmdrrs.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-gmdrrs.productInfo" . | nindent 4 }}
  {{- include "eric-bss-eb-gmdrrs.serviceAnnotations" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: gmdrrs
      port: {{ .Values.service.clusterPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      targetPort: {{ .Values.service.clusterPort }}
  selector:
    app: eric-bss-eb-gmdrrs
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{ if .Values.loadBalancerIp }}
    loadBalancerIP: {{ .Values.loadBalancerIp }}
    {{ end }}
