apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-rlh-tnsnames.ora
data:
  tnsnames.ora: |-
    bscsdb =
{{ tpl .Values.tnsnames.bscsdb . | indent 6 }}
    rtxdb =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}
