apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-evh-evh-registry-nk.xml
data:
  EvhRegistry_nk.xml: |+
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC "ComponentRegistry.dtd" "ComponentRegistry.dtd">
    <!--
        Registry for EVH non-kernel plug in implementations.
        Each node inside the ComponentRegistry should represent one plug in.
        This component registry is linked to the main registry file Registry.xml.
    -->

    <ComponentRegistry>

    </ComponentRegistry>
