apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-evh-evh-registry.xml
data:
  EvhRegistry.xml: |+
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC "ComponentRegistry.dtd" "ComponentRegistry.dtd">

    <!--
      Component Registry for EVH

      This component registry is linked to the main registry file Registry.xml.
    -->

    <ComponentRegistry>

        <Node name="EVH">

            <Node name="PromotionAction" >
                <!-- please use SOISRV_HOST and SOISRV_PORT environment variables, ORBInitRef can not be set in the registry                      -->
                <!--KeyValue comment="" key="ORBInitRef" type="String" value="NameService=corbaloc:iiop:'ServerNode':'Portnumber'/NameService" /-->
                <KeyValue comment="" key="NameServer" value="com/lhs/public/soi/fedfactory1"     type="String" />
                <KeyValue comment="" key="SoiName"    value="CIL"                                type="String" />
                <KeyValue comment="" key="SoiVersion" value="7"                                  type="Integer" />
                <KeyValue comment="" key="UserName"   value="EVHSOICL"                           type="String" />
                <!-- automatical overdraft clearence -->
                <KeyValue comment="" key="AOC"        value="Y"                                  type="String" />
            </Node>

            <Node name="PrepaidBalanceRefill" >
                <!-- please use SOISRV_HOST and SOISRV_PORT environment variables, ORBInitRef can not be set in the registry                     -->
                <!-- KeyValue comment="" key="ORBInitRef" type="String" value="NameService=corbaloc:iiop:'ServerNode':'Portnumber'/NameService" /-->
                <KeyValue comment="" key="NameServer" value="com/lhs/public/soi/fedfactory1"     type="String" />
                <KeyValue comment="" key="SoiName"    value="CIL"                                type="String" />
                <KeyValue comment="" key="SoiVersion" value="7"                                  type="Integer" />
                <KeyValue comment="" key="UserName"   value="EVHSOICL"                           type="String" />
                <!-- automatical overdraft clearence -->
                <KeyValue comment="" key="AOC"        value="Y"                                  type="String" />
            </Node>

            <Node name="BillingRequest" >
                <!--Offset value to be added to the reference date-->
                <KeyValue comment="" key="RefDateOffset"  value="10" type="Integer" />
            </Node>

            <Node name="ExpDRR">
                <!--For the initialization of the FX_NameGenerator-->
                <KeyValue key="FX_SUBPATH"  type="String" value="{date:yyyymmdd}/{udr:244,404}/" comment="" />
                <KeyValue key="FX_FILENAME" type="String" value="{uuid}.xml" comment="" />
            </Node>

            <Node name="UDR_ASCII">
                <KeyValue key="FX_SUBPATH" type="String" value="/Ericsson/UDR_TI/" comment="" />
                <KeyValue key="FX_FILENAME" type="String" value="TA_FILE{uuid}" comment="" />
            </Node>

            <Node name="HandleCostControlAlerts" >
                <!-- ORBInitRef can not be set in the registry -->
                <!-- KeyValue comment="" key="ORBInitRef" type="String" value="NameService=corbaloc:iiop:'ServerNode':'Portnumber'/NameService" /-->
                <KeyValue comment="" key="NameServer" value="com/lhs/public/soi/fedfactory1" type="String" />
                <KeyValue comment="" key="SoiName"    value="CIL"   type="String" />
                <KeyValue comment="" key="SoiVersion" value="7"     type="Integer" />
                <KeyValue comment="" key="UserName"   value="EVHSOICL"   type="String" />
                <KeyValue comment="" key="DefaultBU"  value="DEFBU" type="String" />
                <Node name="MarketServiceMapping" >
                    <!--The service code (public) for the operator barring service-->
                    <KeyValue comment="" key="DEFAULT"   value="XXX"   type="String" />
                    <KeyValue comment="" key="GSM"       value="XXX"   type="String" />
                </Node>
            </Node>

            <Node name="HandleUnbalPrepaid_OneAndRec" >
                <!-- ORBInitRef can not be set in the registry -->
                <!-- KeyValue comment="" key="ORBInitRef" type="String" value="NameService=corbaloc:iiop:'ServerNode':'Portnumber'/NameService" /-->
                <KeyValue comment="" key="NameServer" value="com/lhs/public/soi/fedfactory1" type="String" />
                <KeyValue comment="" key="SoiName"    value="CIL"   type="String" />
                <KeyValue comment="" key="SoiVersion" value="7"     type="Integer" />
                <KeyValue comment="" key="UserName"   value="EVHSOICL"   type="String" />
                <Node name="ServiceActionDefinition" >
                    <!--The service code (public) for the operator barring service-->
                    <KeyValue comment="" key="TEL"       value="D"   type="String" />
                </Node>

                <Node name="AdvanceChargeHandling" >
                    <!-- value for attribute key  must be either
                           - 'DEFAULT_VALUE' (specifies the default handling for all services) or
                           - or the service public key (overwrites the default handling for the particular service)
                         value fo attrinute value must be either
                           - 'C' (charging)
                           - 'R' (rollback)
                    -->
                    <KeyValue comment="" key="DEFAULT_VALUE"       value="R"   type="String" />
                </Node>

                <Node name="ReasonCodes" >
                    <!-- reason codes must be configured in REASONSTATUS_ALL -->
                    <KeyValue comment="" key="ACT"    value="20"   type="Integer" />
                    <KeyValue comment="" key="DEACT"  value="21"   type="Integer" />
                </Node>
            </Node>

            <Node name="InitialActivation" >
                <!-- ORBInitRef can not be set in the registry -->
                <!-- KeyValue comment="" key="ORBInitRef" type="String" value="NameService=corbaloc:iiop:'ServerNode':'Portnumber'/NameService" /-->
                <KeyValue comment="" key="NameServer" value="com/lhs/public/soi/fedfactory1" type="String" />
                <KeyValue comment="" key="SoiName"    value="CIL"   type="String" />
                <KeyValue comment="" key="SoiVersion" value="7"     type="Integer" />
                <KeyValue comment="" key="UserName"   value="EVHSOICL"   type="String" />
                <KeyValue comment="" key="DefaultBU"  value="DEFBU" type="String" />
            </Node>

            <!-- All error codes in this file must be written WITHOUT the "CMS." prefix !  -->

            <Node name="SpecialCMSErrorCodes" >
            <!--
                List of (CMS) error codes that qualify temporary errors
                (e.g. contracts with pending requests)
             -->
                <KeyValue key="RC5008-002" value="" type="String"/>  <!-- Contract.PendingRequests -->
                <KeyValue key="RC5008-003" value="" type="String"/>
                <KeyValue key="RC5008-006" value="" type="String"/>
                <KeyValue key="IN.id0018"  value="" type="String"/>
                <KeyValue key="Contract.IndividualMicroCells.ContractPendingRequest"      value="" type="String"/>
                <KeyValue key="Contract.IndividualMicroCells.DuplicatedMemberInIMC"       value="" type="String"/>
                <KeyValue key="Contract.PendingRequests"                                  value="" type="String"/>
                <KeyValue key="Contract.PendingContractStatusNotAllowedOnSuspDeact"          value="" type="String"/>
                <KeyValue key="Contract.FafElement.PendingRequest"                        value="" type="String"/>
            </Node>

            <Node name="TemporaryConnectionErrors" >
            <!--
                List of error codes that indicate a temporary connection error (e.g. timeout) to the SOI server
                and require a re-initialization.
             -->
                <KeyValue key="FUNC_FRMWK_CMN.0120"     value="" type="String"/>
                <KeyValue key="FUNC_FRMWK_CMN.id0120"   value="" type="String"/>
                <KeyValue key="FUNC_FRMWK_CMN.id0222"   value="" type="String"/>
            </Node>

            <Node name="WrongChargingEngineErrors" >
            <!--
                List of (CMS) error codes that qualify permanent errors
                because the contract is not rated by CS.
            -->
                <KeyValue key="Contract.WrongBSCSorCSContractType" value="" type="String"/><!-- The contract type does not allow this operation. Provide BSCS or CS contracts only -->
            </Node>


            <!-- define error codes to be ignored per CIL command -->
            <Node name="CONTRACT_SERVICES.WRITE" >
              <Node name="IgnoreErrorCodes">
                <KeyValue key="RC6703-002"                            value="" type="String"/>
                <KeyValue key="RC6020-004"                            value="" type="String"/>
                <KeyValue key="RC6608-003"                            value="" type="String"/>
                <KeyValue key="Contract.RequestedStateAlreadySet"     value="" type="String"/>
                <KeyValue key="ConcurrentRequest.RedundantRequest"    value="" type="String"/>
              </Node>
            </Node>

            <Node name="CONTRACT_SERVICES.ADD" >
              <Node name="IgnoreErrorCodes">
                <KeyValue key="RC6226"                                value="" type="String"/> <!-- Service already assigned -->
              </Node>
            </Node>

            <Node name="PRODUCT.CHANGE" >
              <Node name="IgnoreErrorCodes">
                <KeyValue key="RC6003-002"                            value="" type="String"/> <!-- the new product equals the old one  -->
                <KeyValue key="RC6219"                                value="" type="String"/> <!-- the passed product is already assigned to contract -->
              </Node>
            </Node>

            <Node name="FAF_NUMBER.WRITE" >
              <Node name="IgnoreErrorCodes">
                <KeyValue key="Contract.FafElement.DuplicateDestination" value="" type="String"/> <!-- The FAF number is already assigned  -->
              </Node>
            </Node>

        </Node>

        <Node name="FUNC_FRMWK_CMN">
            <Node name="JNI-Settings">
                <!-- List of JVM options. -->
                <Node name="Options">
                    <KeyValue key="-Xrs" value="" type="String" comment="signal handling"/>
                    <!--
                    <KeyValue key="-verbose:" value="jni" type="String"  comment="enable verbose output"/>
                    -->
                </Node>
                <!-- List of EVH specifically overloaded JVM system properties. -->
                <Node name="SysProps">
                    <KeyValue key="java.class.path" type="String" value="${BSCS_RESOURCE}/evh:${BSCS_RESOURCE}:${BSCS_JAR}/func_util.jar:${BSCS_JAR}/soi.jar:${BSCS_JAR}/func_frwmwk_cmn.jar:${BSCS_3PP_JAR}/jgroups-5.1.9.Final.jar:${BSCS_3PP_JAR}/spring-context-5.3.20.jar:${BSCS_3PP_JAR}/spring-aop-5.3.20.jar:${BSCS_3PP_JAR}/spring-beans-5.3.20.jar:${BSCS_3PP_JAR}/spring-core-5.3.20.jar:${BSCS_3PP_JAR}/commons-logging-1.0.4.jar:${BSCS_3PP_JAR}/spring-expression-5.3.20.jar:${BSCS_3PP_JAR}/spring-context-support-5.3.20.jar:${BSCS_3PP_JAR}/spring-security-core-5.5.8.jar:${BSCS_3PP_JAR}/jacorb-3.9.jar:${BSCS_3PP_JAR}/jacorb-omgapi-3.9.jar:${BSCS_3PP_JAR}/slf4j-api-1.7.30.jar:${BSCS_3PP_JAR}/slf4j-jdk14-1.7.30.jar:${BSCS_3PP_JAR}/ascii-table-1.2.0.jar:${BSCS_3PP_JAR}/commons-lang3-3.12.0.jar:${BSCS_3PP_JAR}/log4j-core-2.17.1.jar:${BSCS_3PP_JAR}/log4j-api-2.17.1.jar:${BSCS_3PP_JAR}/log4j-jul-2.17.1.jar" comment=""/>
                    <KeyValue key="java.io.tmpdir" type="String" value="${BSCS_LOG}/evh" comment=""/>
                    <KeyValue key="java.util.logging.config.file" type="String" value="${BSCS_RESOURCE}/evh/logging.properties" comment=""/>
                </Node>
            </Node>
        </Node>

    </ComponentRegistry>
