apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-foh-tnsnames.ora
data:
  tnsnames.ora: |-
    bscsdb =
{{ tpl .Values.tnsnames.bscsdb . | indent 6 }}
    expdb.world =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}
    tapdb.world =
{{ tpl .Values.tnsnames.rtxdb . | indent 6 }}
