# Default values for smsChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  sms-init:
    repoPath:
    pullPolicy:
    registry:
      url:
  eb-java-sms:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  sms-init:
    name: "eric-bss-eb-init-logging"
    tag: "22.15.12"
  eb-java-sms:
    name: "eric-bss-eb-smsserver"
    tag: "22.15.12"

# Allowed: 0,1
replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 128Mi

args:
  javaOpts: "-Xms64M \
             -Xmx128M \
             -XX:+UseG1GC \
             -XX:+HeapDumpOnOutOfMemoryError \
             -Xlog:safepoint=warning \
             -Xlog:gc=info"
  javaDebugOpts:

# By default k8s allows a graceful application shutdown within 30s
# This default value can be overwritten here.
terminationGracePeriodSeconds: 30

#A local nodeSelector definition has priority over the global definition above.
#nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b


suffix:

#A local nodeSelector definition has priority over the global definition above.
#nodeSelector: {}

tnsnames:
  bscsdb: '{{ tpl .Values.global.tnsnames.bscsdb . }}'

sqlnet:
  ora: '{{ tpl .Values.global.sqlnet.ora . }}'

#Business Config Files - customizable configmaps
overrideConfigmap:
  # Default configmap: eric-bss-eb-sms-logging-log4j2.xml
  log4j2xml:
  # Default configmap: eric-bss-eb-sms-rootapplicationcontext-sms-server.xml
  rootApplicationContextSmsServerXml: