apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-rlh-pvc-bab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.rlhBab | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.rlhBab }}
