apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-dmf-pvc-log
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.dmfLog | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.dmfLog }}
