apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-pvc-pwdmgr-security
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.pwdmgrSecurity | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.pwdmgrSecurity }}
