apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-pvc-data-fail-in-workdir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName.datafailinworkdir | default .Values.global.storageClassName.rwo | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.datafailinworkdir }}
