apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-wex-wmx-registry.xml
data:
  WMX_Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>
    <Node name="FUNC_WCLT">

        <!-- Soi server name and version -->
        <KeyValue key="DCI" type="String" value="CIL" comment=""/>
        <KeyValue key="DCI_Version" type="String" value="7" comment=""/>

        <!--
            - The application name used for window titles.
            - This value is directly accessible through method
            ApplicationSettings.getApplicationName()
            This key is also used as parent permission key for initialization of the
            PermissionChecker.
          -->
          <KeyValue key="ApplicationName" type="String" value="WMX" comment="The name of the web client application" />
          <!--
            - The version of the application.
          -->
          <KeyValue key="ApplicationVersion" type="String" value="1.0" comment="The version of the web client application" />

         <!--
          Starts the User settings Solutionunit directly after the user has logged into the
          client. The User settings Solutionunit is a solution unit that can be used to force
          the user to do some initial settings like selecting a business unit or a dealer.
          The workflow of the User settings Solutionunit is defined by the client but the name
          of the SolutionUnit must always be "UserSettings".
          -->
        <KeyValue key="StartUserSettingsSU" type="Boolean" value="true" comment="The name of the web client application" />

        <KeyValue key="SettingsSU" type="String" value="ViewConfigurationSU" comment="Define the solution unit of the settings configuration" />

        <!--
        SoiName for security initialization
        -->
        <KeyValue key="SoiNameForSecurity" type="String" value="SECURITY" comment="The name of the security SOI" />
        <!--
        SoiVersion for security initialization
        -->
        <KeyValue key="SoiVersionForSecurity" type="String" value="3" comment="The version of the security SOI" />
        <!--
             - The implementation of the ContainerFactory
             - Default is com.lhs.ccb.cfw.cda.servicelayer.SoiContainerFactory
             -
             - Used by SoiServerGateway
          -->
          <!-- configuration key="ContainerFactoryImpl"
                     constant="com.lhs.ccb.cfw.cda.servicelayer.SoiContainerFactory" /-->


          <!--
            - The implementation of the ModelContainer
            - Default is com.lhs.ccb.cfw.cda.servicelayer.model.DefaultModelContainer
            -
            - Used by SoiContainerFactory
          -->
        <KeyValue key="ModelContainerImpl" type="String" value="com.lhs.ccb.cfw.cda.servicelayer.model.WebModelContainer" comment="The implementation of the model container." />

          <!--
            - When set to "true" force application to send only changed attributes
            - to the CORBA server.
            - "false" means that all attrubutes will be sent to the CORBA server.
            - This flag doesn't affect HTTP communication.
          -->
          <KeyValue key="SendOnlyChangedData" type="Boolean" value="true" comment="" />


          <!--
            - Permission checker class to be used by the client framework.
          -->

            <KeyValue key="PermissionChecker" type="String" value="com.lhs.ccb.cfw.wcs.security.CFWPermissionChecker" comment="" />

          <!--
            - Service box in navigation pane enabling.
          -->
          <KeyValue key="NavigationPaneServiceBoxEnabled" type="String" value="true" comment="Enables the criteria service box above the navigation pane" />

          <KeyValue key="NavigationPaneServiceBoxAlias" type="String" value="odr" comment="Alias for DCX" />

          <!--
            - Default service box workflow file.
            - When the service box in the navigation pane is enabled, this will be the workflow file used by it.
          -->
          <KeyValue key="DefaultServiceBoxWorkflow" type="String" value="com/lhs/wmx/servicebox/resource/NavigationServiceBoxWorkflow.xml"/>


           <!--
            - The list of the default model configurations. This list is
            - only used as key postfix for the ModelConfigFiles.
            -
            - Pattern of the constant: <modelConfig>[,<modelConfig]*
            -
            - Example: <configuration key="DefaultModels"
            -                         constant="models1,models2"
            -
            - Used by: ModelMetaDataRepository
          -->
          <KeyValue key="DefaultModels" type="String"
                    value="JobModelConfig,SampleJobModelConfig,SecurityModelConfig,SystemSettingsModelConfig,WorkqueueModelConfig,WorkgroupModel,TaskModelConfig,AgentModelConfig,WorkflowModelConfig,UtilModelConfig,EventModelConfig,WorkflowDefinitionSetupModelConfig"
                    comment="" />
            <!--
              - The configuration file for default models. For every defined
              - model config, a file must be defined.
              -
              - Pattern of the key: ModelConfigFile_<modelConfig>
              -
              - Example: <configuration key="ModelConfigFile_models1"
              -                         constant="com/lhs/ccb/myComponent/clt/dal/MyModels.xml" />
              -
              - Used by: ModelMetaDataRepository

            -->
        <!-- Feature 318068 - Begin -->
        <KeyValue key="ModelConfigFile_SampleJobModelConfig" type="String" value="com/lhs/wmx/batchjob/resource/SampleJobModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_JobModelConfig" type="String" value="com/lhs/wmx/batchjob/resource/JobModelConfig.xml" comment="" />
        <!-- Feature 318068 - End -->
        <KeyValue key="ModelConfigFile_SecurityModelConfig" type="String" value="com/lhs/wmx/user/resource/SecurityModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_SystemSettingsModelConfig" type="String" value="com/lhs/wmx/user/resource/SystemSettingsModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_WorkqueueModelConfig" type="String" value="com/lhs/wmx/workqueue/resource/WorkqueueModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_WorkgroupModel" type="String" value="com/lhs/wmx/workgroup/resource/WorkgroupModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_TaskModelConfig" type="String" value="com/lhs/wmx/task/resource/TaskModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_AgentModelConfig" type="String" value="com/lhs/wmx/agent/resource/AgentModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_WorkflowModelConfig" type="String" value="com/lhs/wmx/workflow/resource/WorkflowModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_UtilModelConfig" type="String" value="com/lhs/wmx/util/resource/UtilModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_EventModelConfig" type="String" value="com/lhs/wmx/event/resource/EventModelConfig.xml" comment="" />
        <KeyValue key="ModelConfigFile_WorkflowDefinitionSetupModelConfig" type="String" value="com/lhs/wmx/workflowdefinition/resource/WorkflowDefinitionSetupModelConfig.xml" comment="" />
    <!--    <KeyValue key="ModelConfigFile_SecurityModel" type="String" value="com/lhs/pd/modelconfig/SecurityModelConfig.xml" comment="" />

    -->

        <!--
            - Hook that is called from the client framework after a Service Accessor (Service Object) is created
            - This class reinitialises the Business unit and the dealer for the user
        -->
        <KeyValue key="UserInitialisation"  type="String"  value="com.lhs.wmx.util.ClientUserInitialisation"/>

        <!--
            - User attributes names,(Stored in user session by UserPropertiesFacade) whose chage should be observed and,
              as a result  a SESSION.CHANGE will be performed on the reference connection.

            - Note  the attribute names should be separated from each other by comma(,).
            -
            - Used by: UserAttributesObservable.java
          -->
        <KeyValue key="ObservedUserAttributes"  type="String"  value="BU_ID"/>

        <!--
            feature 341875_wmx - Rafael Werner Begin
        -->
        <KeyValue key="SettingsSU" type="String" value="ViewConfigurationSU"/>
        <!--
            feature 341875_wmx - Rafael Werner End
        -->

        <!-- Feature 305080_wmx - Michel Forster - Begin -->
        <KeyValue key="AttributeConcatenationChar" type="String" value=", "/>
        <!-- Feature 305080_wmx - Michel Forster - End -->

        <!-- Branding options -->
        <Node name="Branding">

            <!--
              -     The class that implements the branding for this application.
                If no value is specified the default framework branding implementation is used.
            -->
            <KeyValue key="Class" type="String" value="com.lhs.wmx.util.BusinessUnitBrandingAdapter"/>

           <!--
              - List all business units as nodes that have a different appearance as the default.
                The name of the node is the business unit identifier.
            -->
            <Node name="2">
                <KeyValue key="StyleSheet_bscs_main" type="String" value="webresources/css/bscs_main.css" comment="Path to the stylesheet used for this business unit."/>
                <KeyValue key="StyleSheet_bscs_main_expanded" type="String" value="webresources/css/bscs_main_expanded.css" comment="Path to the expanded stylesheet used for this business unit."/>
                <KeyValue key="StyleSheet_bscs_dojo" type="String" value="webresources/css/bscs_dojo.css" comment="Path to the dojo stylesheet used for this business unit."/>
            </Node>

        </Node>

        <Node name="WorkflowEntityContentRenderer">

            <!-- Default renderer configured here -->
            <KeyValue key="Renderer" type="String" value="com.lhs.wmx.workflow.controller.WorkflowEntityTableRenderer" comment="The default class used for rendering."/>
            <KeyValue key="View" type="String" value="/workflow/include/TableWorkflowEntityOverview.jsp" comment="The JSP fragment used for rendering."/>

        </Node>

        <!-- Feature 318068 -->
        <!-- This will identify the used scope used to search  properly. -->
        <KeyValue key="Scope" type="String" value="WMS" comment="Scope used to handle searches." />

        <!-- History period in months used when WORKFLOW_PROCESS.READ is executed with no execution date and no type parameter set. Note that this value must be at lest 1. If no value is specified, the default value is 3. -->
        <KeyValue key="HistoryPeriod" type="String" value="3" comment="History period in months."/>

        <!-- PN 00359337 - Begin -->
        <KeyValue key="ErrorTask" type="String" value="VerifyExecutionError" comment="Name of error task created when some error occurs in the workflow execution."/>
        <!-- PN 00359337 - End -->

        <!-- Permission checker class to be used by the client framework -->
        <KeyValue key="PermissionChecker" type="String" value="com.lhs.wmx.util.ClientPermissionChecker" comment=""/>

    </Node>
    </ComponentRegistry>