# Default values for cxChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  cx-config-init:
    repoPath:
    pullPolicy:
    registry:
      url:
  cx-init-customized:
    repoPath:
    pullPolicy:
    registry:
      url:
  cx-webapps-init:
    repoPath:
    pullPolicy:
    registry:
      url:
  eb-java-cx:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  cx-config-init:
    name: "eric-bss-eb-cx-config-init"
    tag: "22.15.12"
  cx-init-customized:
#   Example for customization:
#    name: bscs/java-cx-customized-init
#    directory: /external-files
    name:
    tag:
    directory:
  cx-webapps-init:
    name: "eric-bss-eb-cx-webapps-init"
    tag: "22.15.12"
  eb-java-cx:
    name: "eric-bss-eb-client-tomcat"
    tag: "22.15.12"

replicaCount: 2

readinessProbe:
# Optional: Number of seconds after the container has started before readiness probe is initiated.
# Defaults to 0 seconds. Minimum value is 0.
  initialDelaySeconds: 30
# Optional: How often (in seconds) to perform the probe.
# Default to 10 seconds. Minimum value is 1.
  periodSeconds: 30
# Optional: Minimum consecutive successes for the probe to be considered successful after having failed.
# Defaults to 1. Minimum value is 1.
  successThreshold: 1
# Optional: When a probe fails, Kubernetes will try failureThreshold times before giving up.
# In case of readiness probe the Pod will be marked Unready.
# Defaults to 3. Minimum value is 1.
  failureThreshold: 3
# Optional: Number of seconds after which the probe times out.
# Defaults to 1 second. Minimum value is 1.
  timeoutSeconds: 10

livenessProbe:
# Optional: Number of seconds after the container has started before liveness probe is initiated.
# Defaults to 0 seconds. Minimum value is 0.
  initialDelaySeconds: 60
# Optional: How often (in seconds) to perform the probe.
# Default to 10 seconds. Minimum value is 1.
  periodSeconds: 30
# Optional: Minimum consecutive successes for the probe to be considered successful after having failed.
# Defaults to 1. Must be 1 for liveness probe. Minimum value is 1.
  successThreshold: 1
# Optional: When a probe fails, Kubernetes will try failureThreshold times before giving up.
# Giving up in case of liveness probe means restarting the container.
# Defaults to 3. Minimum value is 1.
  failureThreshold: 3
# Optional: Number of seconds after which the probe times out.
# Defaults to 1 second. Minimum value is 1.
  timeoutSeconds: 10

args:
  ephemeralDHKeySize: "2048"
  javaDebugOpts:

# If a Tomcat secret name is defined, the HTTPS protocol is used, and the keystoreFile and keystorePass
# have to be defined. Otherwise, the HTTP protocol is applied.
tomcat:
  secretName:
  connector:
    maxThreads: 150
    keystoreFile:
    keystorePass:

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

#A local nodeSelector definition has priority over the global definition above.
#nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b


suffix:

#
########## CX_Intergration.xml
#
cxIntegration:
  EnablePrivacyLegalNotice: "true"
  PrivacyPolicy_Uri: "privacyPolicy"
  # For PaymentProcessor entries for the related custom routes
  # can be set up in global values.yaml file in this section:
  # ingress:
  #   customHttpproxy:
  paymentProcessorLink: "PaymentProcessor"

# Ingress / HTTPProxy related settings
ingress:
  timeoutPolicy:
    # Response timeout should be sufficient to cover long running requests to
    # SOI server (see jacorb.orbConnection timeouts for SOI servers).
    # Adapt to the maximum of jacorb.orbConnection.clientPendingReplyTimeout and
    # jacorb.orbConnection.clientConnectTimeout multiplied by jacorb.orbConnection.retries.
    # Otherwise ingress will respond with an "upstream request timeout" message.
    response: "35m"
    idle: "5m"
  retryPolicy:
    count: 1
    perTryTimeout: "15s"
  max_connections: 1024
  max_pending_requests: 1024
  max_requests: 1024
  healthCheck:
    intervalSeconds: 5
    timeoutSeconds: 2
    unhealthyThresholdCount: 3
    healthyThresholdCount: 5
    host: "contour-envoy-healthcheck"

# JacORB properties
jacorb:
  orbConnection:
    # Client settings for establishing CORBA connections to SOI server. If no connection
    # can be established after retries * (retryInterval + clientConnectTimeout) the
    # client session will be logged out.
    # retries: number of connect retries
    # retryInterval: time (in msec) between two connect retries
    # clientConnectTimeout: waiting time (in msec) for a connect attempt to succeed
    retries: 1
    retryInterval: 500
    clientConnectTimeout: 1000

#Business Config Files - customizable configmaps
overrideConfigmap:
  # Default configmap: eric-bss-eb-cx-ax-registry.xml
  cxAxRegistryXml:
  # Default configmap: eric-bss-eb-cx-registry.xml
  cxRegistryXml:
  # Default configmap: eric-bss-eb-cx-integration.xml
  integrationXml:
  # Default configmap: eric-bss-eb-cx-logging.properties
  loggingProperties:
