apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-data.config
data:
  data.config: |-
    DATA_SERVER_DEFINITION
    DATA_SERVER_NAME               {{ .Values.global.dataServerName }}
    {{ if .Values.global.dataHighAvailability.enable }}
    DATA_SERVER_ADDRESS1           T:eric-bss-eb-data-service:{{ .Values.global.dataClusterPort }}
    ADS_ADDRESS1                   T:eric-bss-eb-data1-service:{{ .Values.global.dataClusterPort }}
    TRANSACTION_COLLECTION         {{ .Values.dataConfigFile.transactionCollection }}
    TIMEOUT                        {{ .Values.dataConfigFile.timeout }}
    INTER_DATA_CONNECT_TIMEOUT     {{ .Values.dataConfigFile.interDataConnectTimeout }}
    FAIL_OVER_MODE                 2
    {{ else }}
    DATA_SERVER_ADDRESS1           T:localhost:{{ .Values.global.dataClusterPort }}
    {{- end }}
    DATA_SERVER_DEFINITION_END

    {{ if .Values.global.dataHighAvailability.enable }}
    REPLICATION_DEFINITION
    MESSAGE_PROFILE                {{ .Values.dataConfigFile.messageADSProfile }}
    MEP_HOST                       2
    REP_MODE                       1
    MESSAGE_PROFILE                {{ .Values.dataConfigFile.messagePDSProfile }}
    MEP_HOST                       1
    REP_MODE                       1
    REPLICATION_DEFINITION_END
    {{- end }}

    {{ if or .Values.dataConfigFile.mepHandling .Values.dataConfigFile.globalBcDefinition }}
    MEP_HANDLING
    {{- range .Values.dataConfigFile.mepHandling }}
    MESSAGE_PROFILE                {{ .mep }}
    MODE                           {{ .mode }}
    SYNC_MODE                      {{ .syncMode }}
    {{- end }}

    {{- range .Values.dataConfigFile.globalBcDefinition }}
    MESSAGE_PROFILE                {{ .mep }}
    GLOBAL_BC_FLAG                 Y
    BC_COM_TYPE                    {{ .bcComType }}
    {{- end }}
    MEP_HANDLING_END
    {{ end }}

    {{ if .Values.dataConfigFile.dataUserDefinition }}
    DATA_USER_DEFINITION
    {{- range .Values.dataConfigFile.dataUserDefinition }}
    USER                           {{ .user }}
    USER_NAME                      {{ .userName }}
    HOST                           {{ .host }}
    APPLICATION                    {{ .application }}
    {{- end }}
    DATA_USER_DEFINITION_END
    {{ end }}

    {{ if .Values.dataConfigFile.userRestrictionDefinition }}
    USER_RESTRICTION_DEFINITION
    DATA_SERVER_NAME               {{ .Values.global.dataServerName }}
    {{- range .Values.dataConfigFile.userRestrictionDefinition }}
    USER                           {{ .user }}
    {{- end }}
    USER_RESTRICTION_DEFINITION_END
    {{ end }}

    GLOBAL_CONFIGURATION
    P2P_MESSAGE_VERSIONING         0
    GLOBAL_CONFIGURATION_END
