{{ if .Values.global.dataHighAvailability.enable }}
apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-data1-service
  labels:
    run: eric-bss-eb-data1-service
    app: {{ template "eric-bss-eb-data.name" . }}
    chart: {{ template "eric-bss-eb-data.chart" . }}
    {{- include "eric-bss-eb-data.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-data.productInfo" . | nindent 4 }}
  {{- include "eric-bss-eb-data.serviceAnnotations" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: data
      port: {{ required "A valid .Values.global.dataClusterPort entry is required!" .Values.global.dataClusterPort }}
      nodePort: {{ .Values.global.dataHighAvailability.dataNodePort }}
      protocol: TCP
      targetPort: {{ .Values.global.dataClusterPort }}
    #Note: If DaTA calls dconf, DaTA uses dataPort+1
    - name: data-dconf
      port: {{ add .Values.global.dataClusterPort 1 }}
      {{ if .Values.global.dataHighAvailability.dataNodePort }}
      nodePort: {{ add .Values.global.dataHighAvailability.dataNodePort 1 }}
      {{ end }}
      protocol: TCP
      targetPort: {{ add .Values.global.dataClusterPort 1 }}
    #Note: If TLS connection is enabled DaTA uses dataPort+2
    - name: data-tls
      port: {{ add .Values.global.dataClusterPort 2 }}
      {{ if .Values.global.dataHighAvailability.dataNodePort }}
      nodePort: {{ add .Values.global.dataHighAvailability.dataNodePort 2 }}
      {{ end }}
      protocol: TCP
      targetPort: {{ add .Values.global.dataClusterPort 2 }}
  selector:
    statefulset.kubernetes.io/pod-name: eric-bss-eb-data-1
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{ if .Values.loadBalancerIp }}
    loadBalancerIP: {{ .Values.loadBalancerIp }}
    {{ end }}
{{ end }}