apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-dmfjob-standard-par.xml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  standard_1_par.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      =============================================================================
         Origins: Ericsson Telekommunikation GmbH & Co KG
          Author: R&D Database Team, Frankfurt
            Date: 03-Nov-2015
         Version: "@(#) lhsj_main/bscs/container/helm/ericssonBillingChart/charts/dmfChart/templates/configmap-standard-par-xml.yaml, , 22.15.12, 22.15.12 @@22.15.12 28-Nov-2022"

      Copyright (c) Ericsson, 2015.  All rights reserved.

      The copyright in this work is vested in Ericsson.
      The information contained in this work (either in whole or in part)
      is confidential and must not be modified, reproduced, disclosed or
      disseminated to others or used for purposes other than that for which
      it is supplied, without the prior written permission of Ericsson.
      If this work or any part hereof is furnished to a third party by
      virtue of a contract with that party, use of this work by such party
      shall be governed by the express contractual terms between Ericsson, which
      is party to that contract and the said party.

      The information in this document is subject to change without notice
      and should not be construed as a commitment by Ericsson. Ericsson assumes no
      responsibility for any errors that may appear in this document. With
      the appearance of a new version of this document all older versions
      become invalid.


       =============================================================================
    -->

    <DMF_PARAMETER_LIST xmlns="BSS:Telco:Main:DataMigrationFramework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="BSS:Telco:Main:DataMigrationFramework DMF_Parameter.xsd">
      <PARA xsi:type="PString" Key="RETENTION_PERIOD_SAMPLE_SETUP">
        <DEF_VALUE>{{ .Values.standardpar.RETENTION_PERIOD_SAMPLE_SETUP }}</DEF_VALUE>
        <DESC>Presence of the RETENTION_PERIOD_SAMPLE_SETUP</DESC>
      </PARA>
      <PARA xsi:type="PString" Key="MX">
        <DEF_VALUE>false</DEF_VALUE>
        <DESC>Presence of the component MX</DESC>
      </PARA>
      <PARA xsi:type="PResource" Key="PARA_ADMIN_TO_RTX">
         <DEF_VALUE>BSCS_ADMIN_TO_RTX_LINK</DEF_VALUE>
         <DESC>Name of the BSCS_ADMIN_TO_RTX_LINK Resource key from the resource list.</DESC>
      </PARA>
      <PARA xsi:type="PResource" Key="PARA_ADMIN_TO_BSCS">
         <DEF_VALUE>RTX_ADMIN_TO_BSCS_LINK</DEF_VALUE>
         <DESC>Name of the RTX_ADMIN_TO_BSCS_LINK Resource key from the resource list.</DESC>
      </PARA>
      <PARA xsi:type="PResource" Key="PARA_ORA_FIS" >
         <DEF_VALUE>ORA_FIS</DEF_VALUE>
         <DESC Language="US">Oracle application FIS user from the resource list.</DESC>
      </PARA>
      <PARA xsi:type="PResource" Key="PARA_ORA_FIS_ORA" >
         <DEF_VALUE>ORA_FIS_ORA</DEF_VALUE>
         <DESC Language="US">Oracle application FIS user from the resource list.</DESC>
      </PARA>
      <PARA xsi:type="PResource" Key="PARA_PWDMGR">
         <DEF_VALUE>PWDMGR</DEF_VALUE>
         <DESC Language="US">User for Password Manager from the resource list.</DESC>
      </PARA>
      <PARA xsi:type="PResource" Key="PARA_PWDMGR_UDR">
         <DEF_VALUE>PWDMGR_UDR</DEF_VALUE>
         <DESC Language="US">User for Password Manager from the resource list.</DESC>
      </PARA>
    </DMF_PARAMETER_LIST>


