apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-dmfjob-std-upgrade-set.xml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  standard_upgrade_dmfjob_set.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
       =============================================================================
             Origins: Ericsson Telekommunikation GmbH & Co KG
              Author: R&D Database Team, Frankfurt
                Date: 03-Nov-2015
             Version: "@(#) lhsj_main/bscs/container/helm/ericssonBillingChart/charts/dmfChart/templates/configmap-standard-upgrade-dmfjob-set-xml.yaml, , 22.15.12, 22.15.12 @@22.15.12 28-Nov-2022"
             Purpose: Setup file

        Copyright (c) Ericsson, 2015.  All rights reserved.

        The copyright in this work is vested in Ericsson.
        The information contained in this work (either in whole or in part)
        is confidential and must not be modified, reproduced, disclosed or
        disseminated to others or used for purposes other than that for which
        it is supplied, without the prior written permission of Ericsson.
        If this work or any part hereof is furnished to a third party by
        virtue of a contract with that party, use of this work by such party
        shall be governed by the express contractual terms between Ericsson, which
        is party to that contract and the said party.

        The information in this document is subject to change without notice
        and should not be construed as a commitment by Ericsson. Ericsson assumes no
        responsibility for any errors that may appear in this document. With
        the appearance of a new version of this document all older versions
        become invalid.

       =============================================================================
    -->
    <DMF_SETUP xmlns="BSS:Telco:Main:DataMigrationFramework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="BSS:Telco:Main:DataMigrationFramework DMF_SetUp.xsd">
       <OPTION>
          <MIG_PROJECT_LABEL>{{ .Values.standardupgrade.MIG_PROJECT_LABEL }}</MIG_PROJECT_LABEL>
          <START_UNIT_NAME>R17_UPGRADE</START_UNIT_NAME>
          <MIG_LOG_DIR>LOG</MIG_LOG_DIR>
          <ERROR_MAX_NUM>{{ .Values.standardupgrade.ERROR_MAX_NUM }}</ERROR_MAX_NUM>
          <TOTAL_PROCESS_NUM>{{ .Values.standardupgrade.TOTAL_PROCESS_NUM }}</TOTAL_PROCESS_NUM>
          <TRACE_LEVEL>{{ .Values.standardupgrade.TRACE_LEVEL }}</TRACE_LEVEL>
       </OPTION>
       <RESOURCE>
           <DMF_RESOURCE_FILE>/dbscripts/database/share/standard_1_res.xml</DMF_RESOURCE_FILE>
       </RESOURCE>
       <DEFINE Name="R17_UPGRADE" ResourceKey="SYSTEM_ADMINISTRATOR" Directory="database">
          <DMF_DEFINITION_FILE>upgrade_all_mdf.xml</DMF_DEFINITION_FILE>
       </DEFINE>
       <PARAMETER>
          <DMF_PARAMETER_FILE>/dbscripts/database/share/standard_1_par.xml</DMF_PARAMETER_FILE>
       </PARAMETER>
    </DMF_SETUP>

