apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-dmfjob-tnsnames.ora
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  tnsnames.ora: |-
    bscsdb_admin =
{{ tpl .Values.tnsnames.bscsdb_admin . | indent 6 }}
    rtxdb_admin =
{{ tpl .Values.tnsnames.rtxdb_admin . | indent 6 }}
