apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-bee.properties
data:
  bee.properties: |
    job.taskExecutor.pool.size={{ .Values.beeProperties.jobTaskExecutorPoolSize }}
    job.default.skip.limit={{ .Values.beeProperties.jobDefaultSkipLimit }}

    serviceAccessorDatasource.username=BEE
    serviceAccessorDatasource.soiName=CIL
    serviceAccessorDatasource.soiVersion=7
