apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-common-applicationcontext.xml
data:
  common-ApplicationContext.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.springframework.org/schema/beans
                               http://www.springframework.org/schema/beans/spring-beans-4.3.xsd"
           default-lazy-init="true">

        <!-- GLOBAL PART - BEGIN -->
        <bean id="defaultDestination" class="com.lhs.dxl.jms.DXLDaTADestination" scope="prototype"/>

        <bean id="serviceAccessorPool" class="com.lhs.adaptor.common.ServiceAccessorPool">
            <constructor-arg value="CEB" /> <!-- Username -->
            <constructor-arg type="int" value="2" /> <!-- Pool Size -->
            <constructor-arg value="NamingService"/> <!-- Accessor Root: getting the dedicated implementation -->
        </bean>

        <bean id="cebServiceAccessorPool" class="com.lhs.ceb.CEBServiceAccessorPool">
            <property name="serviceAccessorPool" ref="serviceAccessorPool"/>
            <property name="poolFinalizationTries" value="{{ .Values.cebServiceAccessorPoolProperties.poolFinalizationTries }}"/>
            <property name="poolRetryWait" value="{{ .Values.cebServiceAccessorPoolProperties.poolRetryWait }}"/>
            <property name="soiName" value="CIL"/>
            <property name="soiVersion" value="7"/>
        </bean>

    </beans>
