apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-cms-accounting.xml
data:
  Registry_CMS_Accounting.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>
        <Node name="CMS Settings">

            <!-- Settings for package Accounting -->
            <Node name="Accounting Settings">
                <KeyValue key="SimplePaymentMethodId" type="String" value="-1" comment="ID of simple payment method in table PAYMENTTYPE_ALL"/>
                <KeyValue key="BookingRequest.ValidFromDate.Range" type="Integer" value="10" comment="ValidFromDate range ie between (validFromDate-range) and (validFromDate+range)"/>
                <KeyValue key="GLAccountOverrideAllowed" type="Boolean" value="false" comment="If true it is allowed to override the default GL accounts, if false GL accounts cannot be overriden"/>
                <KeyValue key="GLCode" type="String" value="GEL000T00ZZZZ00Z00CU" comment="ID of the general ledger account (Corresponds to relevant entry in USERLBL table)"/>
                <KeyValue key="MinimumCommitmentGLCode" type="String" value="GEL000T00ZZZZ00Z00CU" comment="ID of the general ledger account used for MinimumCommitmentGLCode (Corresponds to relevant entry in USERLBL table)"/>
                <KeyValue key="DiscountGLCode" type="String" value="GEL000T00ZZZZ00Z00CU" comment="ID of the general ledger account used for DiscountGLCode (Corresponds to relevant entry in FIN_UCASETRANS_GLACCOUNT table)"/>
                <KeyValue key="JobCostId" type="Integer" value="1" comment="ID of the JobCost (Corresponds to relevant entry in JOBCOST table)"/>
                <KeyValue key="MinimumCommitmentJobCostId" type="Integer" value="1" comment="ID of the JobCost userd for MinimumCommitmentJobCost (Corresponds to relevant entry in JOBCOST table)"/>
                <KeyValue key="DiscountJobCostId" type="Integer" value="1" comment="ID of the JobCost used for DiscountJobCost (Corresponds to relevant entry in JOBCOST table)"/>
                <KeyValue key="DeleteAlreadyBilledOCC" type="Boolean" value="false" comment="Enable or disable to delete an OCC that was already billed by BCH. (CFCODE = 14000)"/>
                <KeyValue key="BookingRequestSearchDefaultResultSetSize" value="50" type="Integer" comment="Booking request search default result set size"/>
                <KeyValue key="IsConvertedValue" type="Boolean" value="false" comment="Enable or disable the condition of the conversion value that is set for the number of free units in BookingRequestForFreeUnitI class"/>
            </Node>

            <Node name="BankInstitute Search">
                <KeyValue key="MaxResultSetSize" type="Integer" value="500" comment="null"/>
                <KeyValue key="DefaultResultSetSize" type="Integer" value="50" comment="null"/>
                <KeyValue key="DefaultOutput" type="String" value="Id, Code, Name, Zip, City" comment="null"/>
                <KeyValue key="BaseTable" type="String" value="BANK_ALL" comment="null"/>
                <KeyValue key="BaseTableAlias" type="String" value="BA" comment="null"/>
                <KeyValue key="DefaultConditionClause" type="String" value="BA.BANKTYPE=&apos;B&apos;" comment="null"/>
                <KeyValue key="DefaultNumberOfCharactersBeforeWildcard" type="Integer" value="0" comment="null"/>
                <KeyValue key="FromClauseOrder" type="String" value="BANK_ALL BA" comment="null"/>

                <Node name="Attributes">
                    <Node name="Id">
                        <KeyValue key="SelectClause" type="String" value="BA.BANK_ID" comment="null"/>
                        <KeyValue key="ConditionWhereClause" type="String" value="BA.BANK_ID" comment="null"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null"/>
                    </Node>

                    <Node name="Code">
                        <KeyValue key="SelectClause" type="String" value="BA.BANKCODE" comment="null"/>
                        <KeyValue key="ConditionWhereClause" type="String" value="BA.BANKCODE" comment="null"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null"/>
                        <KeyValue key="SupportsCaseInsensitiveSearch" type="Boolean" value="true" comment="null"/>
                    </Node>

                    <Node name="Name">
                        <KeyValue key="SelectClause" type="String" value="BA.BANKNAME" comment="null"/>
                        <KeyValue key="ConditionWhereClause" type="String" value="BA.BANKNAME" comment="null"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null"/>
                        <KeyValue key="SupportsCaseInsensitiveSearch" type="Boolean" value="true" comment="null"/>
                    </Node>

                    <Node name="Zip">
                        <KeyValue key="SelectClause" type="String" value="BA.BANKZIP" comment="null"/>
                        <KeyValue key="ConditionWhereClause" type="String" value="BA.BANKZIP" comment="null"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null"/>
                        <KeyValue key="SupportsCaseInsensitiveSearch" type="Boolean" value="true" comment="null"/>
                    </Node>

                    <Node name="City">
                        <KeyValue key="SelectClause" type="String" value="BA.BANKLOC" comment="null"/>
                        <KeyValue key="ConditionWhereClause" type="String" value="BA.BANKLOC" comment="null"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null"/>
                        <KeyValue key="SupportsCaseInsensitiveSearch" type="Boolean" value="true" comment="null"/>
                    </Node>

                    <Node name="ResultSize">
                        <KeyValue key="ConditionWhereClause" type="String" value="ROWNUM" comment="null"/>
                        <KeyValue key="Operator" type="String"    value="&lt;" comment="null"/>
                    </Node>
                </Node>
            </Node>

        </Node><!-- CMS Settings -->

    </ComponentRegistry>
