apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-compcmd.xml
data:
  Registry_CompCmd.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>
        <Node name="CompositeCmdAdapter">
            <Node name="ExecutionListeners">
               <!--
               key: composite command
               value: Execution listener for the composite command
               -->
               <KeyValue key="BEL_PAYMENT_METHOD.WRITE" type="String" value="com.lhs.cil.listeners.configurablecompositecommand.ConfigurableCompCmdListener" comment="null"/>
               <KeyValue key="BEL_BILLING_ACCOUNT.WRITE" type="String" value="com.lhs.cil.listeners.configurablecompositecommand.ConfigurableCompCmdListener" comment="null"/>
               <KeyValue key="BEL_CUSTOMER.RETRIEVE" type="String" value="com.lhs.cil.listeners.configurablecompositecommand.ConfigurableCompCmdListener" comment="null"/>
               <KeyValue key="BEL_PARTY.RETRIEVE" type="String" value="com.lhs.cil.listeners.configurablecompositecommand.ConfigurableCompCmdListener" comment="null"/>
            </Node>
        </Node>
    </ComponentRegistry>
