apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-cdi-collectionagencyadaptor.xml
data:
  Registry_CDI_CollectionAgencyAdaptor.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >
    <ComponentRegistry>
        <!-- Add CDI Adaptor to DCS -->
        <Node name="DCS Settings">
            <Node name="Adaptors">
                <KeyValue key="CollectionAgencyAdaptor" type="String" value="com.lhs.cdi.importer.CollectionAgencyAdaptor" comment="Collection Agency adaptor" />
            </Node>
        </Node>
        <Node name="CDI Settings">
            <Node name="Collection Agency Adaptor">
                <Node name="Connection Pool Settings"> <!-- For DCS connection -->
                    <KeyValue key="PoolSize" type="Integer" value="{{ .Values.debtColl.cdiSettings.PoolSize }}" comment="null" />
                    <KeyValue key="FinalizationTries" type="Integer" value="{{ .Values.debtColl.cdiSettings.FinalizationTries }}" comment="null" />
                    <KeyValue key="FinalizationTime" type="Integer" value="{{ .Values.debtColl.cdiSettings.FinalizationTime }}" comment="null" />
                    <KeyValue key="DCSUser" type="String" value="{{ .Values.debtColl.cdiSettings.DCSUser }}" comment="null" />
                    <KeyValue key="SOIName" type="String" value="DCI" comment="null" />
                    <KeyValue key="SOIVersion" type="String" value="2" comment="null" />
                </Node><!-- Connection Pool Settings -->
                <Node name="Importer Settings">
                    <KeyValue key="ReadInterval" type="Integer" value="{{ .Values.debtColl.cdiSettings.ReadInterval }}" comment="null" />
                    <KeyValue key="InputXMLDirectory" type="String" value="{{ .Values.debtColl.cdiSettings.InputXMLDirectory }}" comment="null" />
                    <KeyValue key="ProcessedXMLDirectory" type="String" value="{{ .Values.debtColl.cdiSettings.ProcessedXMLDirectory }}" comment="null" />
                    <KeyValue key="RejectedXMLDirectory" type="String" value="{{ .Values.debtColl.cdiSettings.RejectedXMLDirectory }}" comment="null" />
                </Node><!-- Importer Settings -->
            </Node><!-- Collection Agency Adaptor -->
        </Node><!-- CDI Settings -->
    </ComponentRegistry>
