apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-cms-billing.xml
data:
  Registry_CMS_Billing.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>

        <Node name="CMS Settings">

            <Node name="BillingAccounts">
                <KeyValue key="useAuthentication" type="Boolean"
                    value="false"
                    comment="Authentication is used to determine Jurisdiction and Incorporated indicator" />
                <KeyValue key="callDetailsFlagDefault" type="Boolean"
                    value="false"
                    comment="True if the call details flag should be enabled as default." />
                <KeyValue key="defaultAssignmentTemplate" type="String"
                    value="TEMPLATE"
                    comment="Default template used during the explicit assignment done direct during the contract creation. Reference to table bill_acc_assign_templ" />
                <KeyValue key="defaultPageSize" type="Integer"
                    value="25"
                    comment="Default page size for customer's different billcycles page"/>
            </Node>

            <Node name="BillingDocuments">
                <KeyValue key="DocTypeNameForCds" type="String" value="CDS" />
                <KeyValue key="DocTypeNameForCrp" type="String" value="CRP" />
            </Node>

            <Node name="BillingService">
                <KeyValue key="MaxResultSetSize" type="Integer" value="500"/>
                <KeyValue key="DefaultResultSetSize" type="Integer" value="50"/>
                <KeyValue key="MaxResultSizeForDocImage" type="Integer"  value="0"/>
                <KeyValue key="MinimumNumberOfCharactersBeforeWildcard" type="Integer" value="5"/>
                <KeyValue key="CallingProcess" type="String" value="OMS" comment="Name of calling process"/>
                <KeyValue key="DocumentRetrievalTimeout" type="Integer" value="20" comment="Timeout in seconds used when waiting for document retrieval response messages."/>
            </Node>

        </Node><!-- CMS Settings -->

    </ComponentRegistry>
