apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-batch.xml
data:
  Registry_Batch.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>

        <Node name="FUNC_FRMWK_SRV">

            <KeyValue key="BSCS_VTIMEZONE" type="String" value="Europe/Berlin" comment="used in CAASTimeConverter()"/>

            <KeyValue key="CDFRootDirectory" type="String" value="cdf" comment="Root directory for the command definition files. Case sensitive entry."/>

            <KeyValue key="SOIRootDirectory" type="String" value="soi" comment="Root directory for the service oriented interface definition files. Case sensitive entry."/>

            <!--
            List of files defining SOI's. These files are searched in SOIRootDirectory
            Filenames should be entered in as "key" attributes, "value" attributes remains empty.
            -->
            <Node name="SOIDefinitions" >
                <KeyValue key="BATCH_1.xml" value="" type="String" comment=""/>
            </Node>


            <!--
                List of files containing the server's application context configuration
             -->
            <Node name="ApplicationContextConfigs">
                <KeyValue key="rootApplicationContext-bee.xml" value="" type="String"
                    comment="The application context configuration file of the server" />
            </Node>

            <!--
            <KeyValue key="ValidationRootDirectory" type="String" value="val" comment="Root directory for the validation definition files. Case sensitive entry."/>
            -->
            <!--
            List of validation definitions. These files are searched in ValidationRootDirectory
            Filenames should be entered in as "key" attributes, "value" attributes remains empty.
            <Node name="ValidationDefinitions" >
                <KeyValue key="CMS_Validation.xml" value="" type="String" comment=""/>
            </Node>
            -->

            <!-- Flag indicates whether to validate the input-SVLObjects against the  command definitions. Allowed values are 'true' and 'false'. -->
            <KeyValue key="ValidateInput" value="false" type="Boolean"/>

            <!--
            List of listeners implementing ServerStartupListener interface.
            Each listener entered here will be instantiated using default constructor without parameters and
            corresponding before- and after- methods will be called during server initialization process
            -->
            <Node name="StartupListeners" >
                <KeyValue key="com.lhs.ccb.sfw.spring.SpringIntegrationServerEventListener" type="String" value="" comment="null"/>
                <KeyValue key="com.lhs.ccb.sfw.remoting.soi.BeanCreatingSOILayerStartupListener" type="String" value="" comment="null"/>
            </Node>

            <!--
            List of listeners implementing ServerShutdown interface.
            Each listener entered here will be instantiated using default constructor without parameters and
            corresponding before- and after- methods will be called during server shutdown
            -->
            <Node name="ShutdownListeners" >
                <KeyValue key="com.lhs.cma.batch.core.BatchShutdownListener" type="String" value="" comment="null"/>
            </Node>

            <!-- This node holds the names of all DomainServiceAdapter classes. -->
            <Node name="ServiceLayerAdapterNames" >
            </Node>

            <!-- This node contains class to subclass mappings. It can be used to customize an
                 implementation class by subclassing. Each customized class needs a KeyValue
                 entry here, mapping the parent class name of the core implementation to a
                 customized class name. Per default this node is empty.
            -->
            <Node name="ClassLookupTable">
            </Node>

            <!-- TOPLink related settings, configuration of persistent domain objects-->
            <Node name="Persistence">

                <!-- Settings for the Java wrapper of NEXTFREE stored procedures. -->
                <Node name="NEXTFREE">
                    <!--
                    Specifies fetch size for a particular sequence.
                    If a sequence is found in the list than NEXTFREE.GetNumValues / NEXTFREE.GetStringValues  with
                    array interface will be used with specified fetch size

                    If a sequence isn't found in the list than NEXTFREE.GetValue / NEXTFREE.GetStringValue
                    will be used (no array interface and caching)
                     -->
                    <Node name="FetchSizePerSequence">
                    </Node>
                </Node>

                <!-- Contains KeyValue entries holding the package names of all packages with
                     persistent classes. Each of the packages listed here is assumed to contain
                     a class 'BOregister', which must add the descriptors of the package to the
                     list of all application descriptors.
                -->
                <Node name="PackageNamesForBORegistry">
                    <KeyValue key="com.lhs.cma.batch.domain" value=""/>
                </Node>

                <!--
                Contains a list of reference data classes, that should be refreshed periodically.
                 -->
                <Node name="RefreshReferenceData">
                </Node>
            </Node>


            <KeyValue key="SecurityArea" type="String" value="CustomerManagementServer"
                comment="A top-element in the permission hierarchy, used to retrieve permissions for this server. See 'PERMISSION' argument of 'USER_RIGHT.CHECK' command."
             />
        </Node><!-- FUNC_FRMWK_SRV -->
    </ComponentRegistry>
