apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-jacorb.properties
data:
  jacorb.properties: |

    ##################################
    #                                #
    #  Logging configuration         #
    #                                #
    ##################################

    # hexdump outgoing messages (values "on", "off")
    jacorb.debug.dump_outgoing_messages={{ .Values.jacorb.log.dumpOutgoingMessages }}

    # hexdump incoming messages (values "on", "off")
    jacorb.debug.dump_incoming_messages={{ .Values.jacorb.log.dumpIncomingMessages }}

    ###################################
    #                                 #
    #  ORB Connection Configuration   #
    #                                 #
    ###################################

    # number of retries if connection cannot directly be established
    jacorb.retries={{ int64 .Values.jacorb.orbConnection.retries }}

    # how many msecs. do we wait between retries
    jacorb.retry_interval={{ int64 .Values.jacorb.orbConnection.retryInterval }}

    # client-side connection idle timeout, set no non-zero to stop
    # close the connection after so many msecs.
    jacorb.connection.client.idle_timeout={{ int64 .Values.jacorb.orbConnection.clientIdleTimeout }}

    # Initial timeout for establishing a connection.
    jacorb.connection.client.connect_timeout={{ int64 .Values.jacorb.orbConnection.clientConnectTimeout }}

    # Wait the specified number of million seconds for a reply to a request.
    # If exceeded, a org.omg.CORBA.TIMEOUT exception will be thrown
    jacorb.connection.client.pending_reply_timeout={{ int64 .Values.jacorb.orbConnection.clientPendingReplyTimeout }}

    #########################
    #                       #
    #   POA Configuration   #
    #                       #
    #########################

    # Thread pool configuration for request processing.
    # New threads may be started until the total number of threads reaches
    # the max value. Otherwise, request processing is blocked until a thread
    # is returned to the pool.
    # Setting min to a value greater than one means keeping a certain number
    # of threads ready to serve incoming requests without delay.
    jacorb.poa.thread_pool_max={{ int64 .Values.jacorb.poaConfig.threadPoolMax }}
    jacorb.poa.thread_pool_min={{ int64 .Values.jacorb.poaConfig.threadPoolMin }}
