apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-bee-inputmassremoveiotdevicesrecord.v1.schema.json
data:
  inputMassRemoveIoTDevicesRecord.v1.schema.json: |
    {
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "title": "Mass Removing of IoT Devices Input File",
        "description": "Schema for the input file for the batch job Mass Removing of IoT Devices.",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "record": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "recordNumber": {
                        "$ref": "recordNumber.v1.schema.json"
                    },
                    "entity": {
                        "type": "object",
                        "description": "A record of the devices.",
                        "additionalProperties": false,
                        "properties": {
                            "effectiveDate": {
                                "$ref": "dateTime.v1.schema.json",
                                "description": "The effective date for removing the device must correspond to the maximum de-assignment timestamp in the device package. It needs to be calculated and provided as the effective date field per record in order to avoid rejection of usage records in the process of rating logical resources linked to IoT device. If the effective date is not provided, the batch job will consider the current timestamp as the de-assignment date of the devices provided in the device package."
                            },
                            "devices": {
                                "type": "array",
                                "description": "List of devices.",
                                "minItems": 1,
                                "maxItems": {{ .Values.beeInputMassRemoveIoTDevicesRecord.maxItems }},
                                "items": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "properties": {
                                        "deviceNumber": {
                                            "type": "string",
                                            "minLength": 1,
                                            "description": "Device number. Type of number depends on resource specification ID (devices, SIM cards)."
                                        }
                                    },
                                    "required": [
                                        "deviceNumber"
                                    ]
                                }
                            }
                        }
                    }
                },
                "required": [
                    "recordNumber",
                    "entity"
                ]
            }
        }
    }
