apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-dcs-installments.xml
data:
  Registry_DCS_Installments.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >
    <ComponentRegistry>
        <Node name="DCS Settings">
            <KeyValue key="Installment Part Definition" type="String" value="INSTALLMENT" comment="Installment Part definition name" />
            <KeyValue key="Current Installment Timer Update Event" type="String" value="RecreateTimer"
                comment="The existent event used to update the current installment information in timers" />
            <Node name="Payment Plan Template Search">
                <KeyValue key="MaxResultSetSize" type="Integer" value="{{ .Values.debtColl.PaymentPlanTemplateSearch.MaxResultSetSize }}" comment="null" />
                <KeyValue key="DefaultResultSetSize" type="Integer" value="{{ .Values.debtColl.PaymentPlanTemplateSearch.DefaultResultSetSize }}" comment="null" />
                <KeyValue key="DefaultOutput" type="String"
                    value="PAYMENT_PLAN_TEMPLATE_ID, PAYMENT_PLAN_TEMPLATE_ID_PUB,
                            DESCRIPTION, PAYMENT_PLAN_TYPE_ID, INTEREST_TYPE_ID, BU_ID,
                            INTEREST_RATE, PAYMENT_INTERVAL, PAYMENT_INTERVAL_PERIOD_ID,
                            DURATION, DURATION_PERIOD_ID"
                    comment="null" />
                <KeyValue key="BaseTable" type="String" value="PAY_PLAN_TEMPLATE" comment="null" />
                <KeyValue key="BaseTableAlias" type="String" value="PPT" comment="null" />
                <KeyValue key="DefaultNumberOfCharactersBeforeWildcard" type="Integer" value="3" comment="null" />
                <Node name="Attributes">
                    <Node name="PAYMENT_PLAN_TEMPLATE_ID">
                        <KeyValue key="SelectClause" type="String" value="PPT.PAY_PLAN_TEMPLATE_ID" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.PAY_PLAN_TEMPLATE_ID" comment="null" />
                    </Node>
                    <Node name="PAYMENT_PLAN_TEMPLATE_ID_PUB">
                        <KeyValue key="SelectClause" type="String" value="PPT.SHDES" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.SHDES" comment="null" />
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null" />
                    </Node>
                    <Node name="DESCRIPTION">
                        <KeyValue key="SelectClause" type="String" value="PPT.DES" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.DES" comment="null" />
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true" comment="null" />
                    </Node>
                    <Node name="PAYMENT_PLAN_TYPE_ID">
                        <KeyValue key="SelectClause" type="String" value="PPT.PAY_PLAN_TYPE_ID" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.PAY_PLAN_TYPE_ID" comment="null" />
                    </Node>
                    <Node name="INTEREST_TYPE_ID">
                        <KeyValue key="SelectClause" type="String" value="PPT.INTEREST_TYPE_ID" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.INTEREST_TYPE_ID" comment="null" />
                    </Node>
                    <Node name="BU_ID">
                        <KeyValue key="SelectClause" type="String" value="PPT.BUSINESS_UNIT_ID" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.BUSINESS_UNIT_ID" comment="null" />
                    </Node>
                    <Node name="INTEREST_RATE">
                        <KeyValue key="SelectClause" type="String" value="PPT.I_VALUE" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.I_VALUE" comment="null" />
                    </Node>
                    <Node name="PAYMENT_INTERVAL_PERIOD_ID">
                        <KeyValue key="SelectClause" type="String" value="PPT.N_VALUE_PERIOD" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.N_VALUE_PERIOD" comment="null" />
                    </Node>
                    <Node name="PAYMENT_INTERVAL">
                        <KeyValue key="SelectClause" type="String" value="PPT.N_VALUE" comment="null" />
                        <KeyValue key="ConditionWhereClause" type="String" value="PPT.N_VALUE" comment="null" />
                    </Node>
                    <Node name="DURATION_PERIOD_ID">
                        <KeyValue key="SelectClause" type="String" value="PPT.PERIOD_ID" comment="null" />
                    </Node>
                    <Node name="DURATION">
                        <KeyValue key="SelectClause" type="String" value="PPT.PERIOD_NUMBER" comment="null" />
                    </Node>
                </Node>
            </Node>
        </Node>
    </ComponentRegistry>
