apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-cms-product.xml
data:
  Registry_CMS_Product.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>

        <Node name="CMS Settings">

            <Node name="Product Settings">
                <KeyValue key="readAllProducts" type="Boolean" value="false" comment="null"/>
                <KeyValue key="OCC_BILL_X_TIMES_ALWAYS_ALLOW_OVERWRITE" type="Boolean" value="false" comment="Configuration flag of CMS: Is it allowed to overwrite the frequency setting for billing event services in CX?
                   TRUE: CX/CMS can overwrite the frequency during assign of OCC even if the service is set in PX as one time charge.
                   FALSE: CX/CMS can only overwrite the frequency during assign of OCC when the service is set in PX as recurring chargeable and customer care is allowed to overwrite the amount."/>
                   <KeyValue key="CHARGING_SCHEDULE_ALLOW_OVERWRITE" type="Boolean" value="true" comment="Indicates if it is allowed to overwrite the default charging schedule at contract service level."/>
                <Node name="BasicServiceGroups Search">
                    <KeyValue key="wildcardLimit" type="Integer" value="3" comment="the minimum number of characters before wildcard in a search string"    />
                 </Node>
            </Node>

            <Node name="PredefinedChargeableEventName">
                <KeyValue key="Temporary deactivation of a contract" comment="null" type="Integer" value="9"/>
                <KeyValue key="Reactivation of a contract" comment="null" type="Integer" value="10"/>
                <KeyValue key="Replacement of a directory number" comment="null" type="Integer" value="17"/>
                <KeyValue key="Replacement of a resource" comment="null" type="Integer" value="8"/>
                <KeyValue key="Micro cells maintenance" comment="null" type="Integer" value="30"/>
                <KeyValue key="IMC element insertion" comment="null" type="Integer" value="172"/>
                <KeyValue key="IMC scale factor change" comment="null" type="Integer" value="173"/>
                <KeyValue key="IMC element change" comment="null" type="Integer" value="174"/>
                <KeyValue key="IMC element deletion" comment="null" type="Integer" value="175"/>
                <KeyValue key="Itemized bill" comment="null" type="Integer" value="13"/>
                <KeyValue key="Itemized bill charge per line" comment="null" type="Integer" value="31"/>
                <KeyValue key="Invocation of alternate rateplan" comment="null" type="Integer" value="40"/>
                <KeyValue key="Usage of alternate rateplan" comment="null" type="Integer" value="41"/>
                <KeyValue key="Operator-assisted service activation" comment="null" type="Integer" value="11"/>
                <KeyValue key="Operator-assisted switch interrogation" comment="null" type="Integer" value="12"/>
                <KeyValue key="Replacement of a Private Directory Number" comment="null" type="Integer" value="10010"/>
                <KeyValue key="Directory number porting in charge" comment="null" type="Integer" value="203"/>
                <KeyValue key="Directory number porting out charge" comment="null" type="Integer" value="204"/>
            </Node>

        </Node><!-- CMS Settings -->

    </ComponentRegistry>
