apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-bee-inputmassaddiotdevicesrecord.v1.schema.json
data:
  inputMassAddIoTDevicesRecord.v1.schema.json: |
    {
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "title": "Mass Adding of IoT Devices Record",
        "description": "Schema for the input records of the job Mass Adding of IoT Devices.",
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "record": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "recordNumber": {
                        "$ref": "recordNumber.v1.schema.json"
                    },
                    "entity": {
                        "type": "object",
                        "description": "A device package.",
                        "additionalProperties": false,
                        "properties": {
                            "effectiveDate": {
                                "$ref": "dateTime.v1.schema.json",
                                "description": "The effective date of device assignment."
                            },
                            "devices": {
                                "type": "array",
                                "description": "List of devices.",
                                "minItems": 1,
                                "maxItems": {{ .Values.beeInputMassAddIoTDevicesRecord.maxItems }},
                                "items": {
                                    "type": "object",
                                    "additionalProperties": false,
                                    "properties": {
                                        "deviceNumber": {
                                            "type": "string",
                                            "minLength": 1,
                                            "description": "Device number. Type of number depends on resource specification ID (devices, SIM cards)."
                                        },
                                        "deviceDescription": {
                                            "type": "string",
                                            "description": "The device description."
                                        },
                                        "deviceSubtypeIdPub": {
                                            "type": "string",
                                            "description": "The public key of the device subtype."
                                        },
                                        "storageMediumClassIdPub": {
                                            "type": "string",
                                            "description": "The public key of the storage medium class."
                                        },
                                        "eId": {
                                            "$ref": "string32.v1.schema.json",
                                            "description": "The serial number attached to a device that uses an embedded SIM (eSIM)."
                                        },
                                        "ports": {
                                            "type": "array",
                                            "description": "List of ports.",
                                            "items": {
                                                "type": "object",
                                                "additionalProperties": false,
                                                "properties": {
                                                    "portNumber": {
                                                        "type": "string",
                                                        "minLength": 1,
                                                        "description": "The port number."
                                                    },
                                                    "homeLocationRegisterIdPub": {
                                                        "type": "string",
                                                        "description": "The public key of the home location register."
                                                    },
                                                    "effectiveDate": {
                                                        "$ref": "dateTime.v1.schema.json",
                                                        "description": "The effective date of port status modification."
                                                    }
                                                },
                                                "required": [
                                                    "portNumber"
                                                ]
                                            }
                                        },
                                        "directoryNumbers": {
                                            "type": "array",
                                            "description": "List of directory numbers.",
                                            "items": {
                                                "type": "object",
                                                "additionalProperties": false,
                                                "properties": {
                                                    "prefix": {
                                                        "type": "string",
                                                        "description": "The prefix of the directory number."
                                                    },
                                                    "directoryNumber": {
                                                        "type": "string",
                                                        "minLength": 1,
                                                        "description": "The directory number."
                                                    },
                                                    "homeLocationRegisterIdPub": {
                                                        "type": "string",
                                                        "description": "The public key of the home location register."
                                                    },
                                                    "logicalHomeLocationRegisterIdPub": {
                                                        "type": "string",
                                                        "description": "The public key of the logical home location register."
                                                    },
                                                    "resourceStructureIdPub": {
                                                        "type": "string",
                                                        "description": "The public key of the resource structure."
                                                    },
                                                    "technologyIdPub": {
                                                        "type": "string",
                                                        "description": "The public key of the technology."
                                                    },
                                                    "showDirectoryNumberOnBill": {
                                                        "type": "boolean",
                                                        "description": "Indicates whether the directory number should be shown on bill."
                                                    },
                                                    "isVanityNumber": {
                                                        "type": "boolean",
                                                        "description": "Indicates whether the directory number is a vanity number."
                                                    },
                                                    "virtualPrivateNetworkIdPub": {
                                                        "type": "string",
                                                        "description": "The public key of the VPN."
                                                    },
                                                    "nationalDestinationCode": {
                                                        "type": "string",
                                                        "description": "Prefix of the VPN number (in case of telephony)."
                                                    },
                                                    "linkedPortId": {
                                                        "$ref": "longInteger.v1.schema.json",
                                                        "description": "The id of the linked port."
                                                    },
                                                    "effectiveDate": {
                                                        "$ref": "dateTime.v1.schema.json",
                                                        "description": "The effective date of directory number status modification."
                                                    }
                                                },
                                                "required": [
                                                    "directoryNumber"
                                                ]
                                            }
                                        }
                                    },
                                    "required": [
                                        "deviceNumber"
                                    ]
                                }
                            }
                        }
                    }
                },
                "required": [
                    "recordNumber",
                    "entity"
                ]
            }
        }
    }
