apiVersion: v1
kind: Secret
metadata:
  name: eric-bss-eb-secret-cms-security-log4j2.xml
type: Opaque
stringData:
  security_log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Configuration of the package, which contains the package name of the plugin,
         implemented to create a custom Pattern Layout for the log files.
         (refer to com.lhs.ccb.sfw.utilities.ServerLogPattern)-->
    <Configuration packages="com.lhs.ccb.sfw.utilities">
      <Properties>
        <!-- The basePath defines the location of the log files. -->
        <Property name="basePath">${sys:java.io.tmpdir}</Property>
        <Property name="processId">${sys:processId}</Property>
      </Properties>
      <Appenders>
        <!-- The RollingFile defines the name of the log files as well as their rolling policies. -->
        <RollingFile name="SecSrvGenericSecurityFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
        <RFC5424Layout facility="AUTH" newLine="true" messageId="SECGEN" appName="SECSRV" />
            <Policies>
                <SizeBasedTriggeringPolicy size="10 MB" />
                <TimeBasedTriggeringPolicy modulate="true"/>
            </Policies>
            <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvAccessRightGroupCreateFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ACRGCR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvAccessRightGroupDeleteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ACRGDE" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvAccessRightGroupWriteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ACRGWR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvAccessRightReadFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ACRIRE" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvDatabasePropertiesReadFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="DBPRRD" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvPasswordChangeFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="PWDCHN" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvPasswordSettingsReadFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="PWDSRD" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleAccessRightReadFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="RACRRE" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleAccessRightWriteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="RACRWR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleAssignmentWriteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="RASSWR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleCreateFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ROLECR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleDefinitionExportFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="RODEEX" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleDeleteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ROLEDE" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRoleWriteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ROLEWR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvRolesReadFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="ROLSRD" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvUserCreateFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="USERCR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvUserReadFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="USERRE" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvUserRightCheckFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="USRICH" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvUserSearchFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="USERSR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <RollingFile name="SecSrvUserWriteFile" fileName="${basePath}/SECSRV.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/SECSRV.${hostName}.${processId}.SecLog_%d{yyyy-MM-dd}_%03i.log">
            <RFC5424Layout facility="AUTH" newLine="true" messageId="USERWR" appName="SECSRV" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="10 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
        </RollingFile>
        <!-- The Syslog Appender is used to send messages to a remote syslog daemon.
             This is an example of configuration of this appender. The values must be set accordingly, such as host, port etc.
             For SSL, the location and the password of both TrustStore and KeyStore can be set using environment variables.
             You can configure more than one Syslog as you need. If it is necessary to distinguish the messages according to its message Id, it is possible
             to configure one Syslog for each logger, as the examples: SecSrvAccessRightGroupCreateSyslog and SecSrvAccessRightGroupCreateSyslog
        <Syslog name="SecSrvAccessRightGroupCreateSyslog" host="{{ .Values.global.SyslogAppenderSecurityTls.hostSyslogAppender }}" port="{{ .Values.global.SyslogAppenderSecurityTls.portSyslogAppender }}" format="RFC5424" newLine="true" messageId="ACRGCR" appName="SECSRV">
            <SSL>
                <TrustStore location="${env:SYSLOG_TRUSTSTORE}" passwordFile="${env:SYSLOG_TRUSTSTORE_PASSWORD_FILE}"/>
                <KeyStore location="${env:SYSLOG_KEYSTORE}" passwordFile="${env:SYSLOG_KEYSTORE_PASSWORD_FILE}" />
            </SSL>
        </Syslog>
        <Syslog name="SecSrvAccessRightGroupDeleteSyslog" host="{{ .Values.global.SyslogAppenderSecurityTls.hostSyslogAppender }}" port="{{ .Values.global.SyslogAppenderSecurityTls.portSyslogAppender }}" format="RFC5424" newLine="true" messageId="ACRGDE" appName="SECSRV">
            <SSL>
                <TrustStore location="${env:SYSLOG_TRUSTSTORE}" passwordFile="${env:SYSLOG_TRUSTSTORE_PASSWORD_FILE}"/>
                <KeyStore location="${env:SYSLOG_KEYSTORE}" passwordFile="${env:SYSLOG_KEYSTORE_PASSWORD_FILE}" />
            </SSL>
        </Syslog>
        -->
      </Appenders>
      <!-- Defines the Loggers with their names and logging levels. -->
      <Loggers>
        <Logger name="SecSrvAccessRightGroupCreateLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvAccessRightGroupCreateFile" />
         <!-- This is an example how to use the Syslog Appender to log messages to a remote syslog server.
         <AppenderRef ref="SecSrvAccessRightGroupCreateSyslog" /> -->
        </Logger>
        <Logger name="SecSrvAccessRightGroupDeleteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvAccessRightGroupDeleteFile" />
         <!-- This is an example how to use the Syslog Appender to log messages to a remote syslog server.
         <AppenderRef ref="SecSrvAccessRightGroupDeleteSyslog" /> -->
        </Logger>
        <Logger name="SecSrvAccessRightGroupWriteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvAccessRightGroupWriteFile" />
        </Logger>
        <Logger name="SecSrvAccessRightReadLog" level="warn" additivity="false">
         <AppenderRef ref="SecSrvAccessRightReadFile" />
        </Logger>
        <Logger name="SecSrvDatabasePropertiesReadLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvDatabasePropertiesReadFile" />
        </Logger>
        <Logger name="SecSrvPasswordChangeLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvPasswordChangeFile" />
        </Logger>
        <Logger name="SecSrvPasswordSettingsReadLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvPasswordSettingsReadFile" />
        </Logger>
        <Logger name="SecSrvRoleAccessRightReadLog" level="warn" additivity="false">
         <AppenderRef ref="SecSrvRoleAccessRightReadFile" />
        </Logger>
        <Logger name="SecSrvRoleAccessRightWriteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvRoleAccessRightWriteFile" />
        </Logger>
        <Logger name="SecSrvRoleAssignmentWriteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvRoleAssignmentWriteFile" />
        </Logger>
        <Logger name="SecSrvRoleCreateLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvRoleCreateFile" />
        </Logger>
        <Logger name="SecSrvRoleDefinitionExportLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvRoleDefinitionExportFile" />
        </Logger>
        <Logger name="SecSrvRoleDeleteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvRoleDeleteFile" />
        </Logger>
        <Logger name="SecSrvRoleWriteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvRoleWriteFile" />
        </Logger>
        <Logger name="SecSrvRolesReadLog" level="warn" additivity="false">
         <AppenderRef ref="SecSrvRolesReadFile" />
        </Logger>
        <Logger name="SecSrvUserCreateLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvUserCreateFile" />
        </Logger>
        <Logger name="SecSrvUserReadLog" level="warn" additivity="false">
         <AppenderRef ref="SecSrvUserReadFile" />
        </Logger>
        <Logger name="SecSrvUserRightCheckLog" level="error" additivity="false">
         <AppenderRef ref="SecSrvUserRightCheckFile" />
        </Logger>
        <Logger name="SecSrvUserSearchLog" level="warn" additivity="false">
         <AppenderRef ref="SecSrvUserSearchFile" />
        </Logger>
        <Logger name="SecSrvUserWriteLog" level="info" additivity="false">
         <AppenderRef ref="SecSrvUserWriteFile" />
        </Logger>
        <Root level="warn" additivity="false">
            <AppenderRef ref="SecSrvGenericSecurityFile" />
        </Root>
      </Loggers>
    </Configuration>
