apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-cms-soap
  labels:
    run: eric-bss-eb-cms-soap
    app: eric-bss-eb-cms
    chart: {{ template "eric-bss-eb-cms.chart" . }}
    {{- include "eric-bss-eb-cms.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-cms.productInfo" . | indent 4 }}
    {{ if .Values.tomcat.secretName }}
    projectcontour.io/upstream-protocol.tls: "8443,endpoint-cms"
    {{ end }}
    projectcontour.io/max-connections: "{{ .Values.ingress.max_connections }}"
    projectcontour.io/max-pending-requests: "{{ .Values.ingress.max_pending_requests }}"
    projectcontour.io/max-requests: "{{ .Values.ingress.max_requests }}"
spec:
  type: ClusterIP
  ports:
    - name: endpoint-cms
      port: 8443
      targetPort: cms-endpoint
      protocol: TCP
  selector:
    app: eric-bss-eb-cms
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-cms-rest
  labels:
    run: eric-bss-eb-cms-rest
    app: eric-bss-eb-cms
    chart: {{ template "eric-bss-eb-cms.chart" . }}
    {{- include "eric-bss-eb-cms.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-cms.productInfo" . | indent 4 }}
    {{ if .Values.tomcat.secretName }}
    projectcontour.io/upstream-protocol.tls: "8443,endpoint-cms"
    {{ end }}
    projectcontour.io/max-connections: "{{ .Values.ingress.max_connections }}"
    projectcontour.io/max-pending-requests: "{{ .Values.ingress.max_pending_requests }}"
    projectcontour.io/max-requests: "{{ .Values.ingress.max_requests }}"
spec:
  type: ClusterIP
  ports:
    - name: endpoint-cms
      port: 8443
      targetPort: cms-endpoint
      protocol: TCP
  selector:
    app: eric-bss-eb-cms
    app.kubernetes.io/instance: {{ .Release.Name }}
