apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-dmfjob-standard-res.xml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  standard_1_res.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <DMF_RESOURCE_LIST xmlns="BSS:Telco:Main:DataMigrationFramework"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="BSS:Telco:Main:DataMigrationFramework DMF_Resource.xsd">
       <!-- If DB_NAME is not set, the value of the environment variable TWO_TASK is used by DMF !-->
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ADMINISTRATOR">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD> 
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ACCOUNT_MANAGER">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ACCOUNT_MANAGER_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE ResourceKey="REPOSITORY" xsi:type="DB_ORACLE">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA>DMF</DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD> 
       </RESOURCE>
       <RESOURCE ResourceKey="DMF_REPOSITORY" xsi:type="DB_ORACLE">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA>DMFADM</DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD> 
       </RESOURCE>
       <RESOURCE ResourceKey="DMF_REPOSITORY_R" xsi:type="DB_ORACLE">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA>DMFADM</DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD> 
       </RESOURCE>
       <RESOURCE ResourceKey="DMF_TEST_ADMIN" xsi:type="DB_ORACLE">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA>DMTADM</DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD> 
       </RESOURCE>
    </DMF_RESOURCE_LIST>
