apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-eoh-eoh-registry.xml
data:
  EOH_Registry.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC "ComponentRegistry.dtd" "ComponentRegistry.dtd">

    <!-- 
      EOH registry

      The registry is used to configure Mappings to be used for UDR variants. This configuration
      is done under Node MAPPING. Node STORAGE defines Storage Contexts to be used for the 
      specified UDR variants.
      !!!  NOTE: THIS IS ONLY AN EXAMPLE SETUP. FOR SPECIFIC USAGE IT HAS TO BE ADAPTED  !!!
    -->

    <ComponentRegistry>
        <Node name="EOH">
            <Node name="MAPPING">
              <!-- Node "MAPPING" is used to configure Mappings for UDR variants.                     -->
              <!-- For possible values see database table DATA_MAPPING, column NAME                   -->

                <Node name="UDR">            
                <!-- Node UDR contains the possible values, how a record of type UDR can me mapped.     -->
                <!-- Depending on the UDR Attribute UDR_SUBS_TAG, different Mappings can be applied     -->
                <!-- to UDR records. For instance 'key="1"' identifies a UDR records where the          -->
                <!-- UDR attribute UDR_SUBS_TAG is set to value 1. Note that 'key="0"' has a very       -->
                <!-- special meaning, as it is used to define a default Mapping for UDR records.        -->
                <!-- That is, if no specific value is defined for UDR attribute UDR_SUBS_TAG, the       -->
                <!-- value defined for 'key="0"' will be taken as Mapping.                              -->
                <!-- If nothing is defined under this node, no mapping will take place for UDR records. -->

                <!-- Possibles keys run from "0" to "10", for possble values see table DATA_MAPPING, columns NAME -->

                   <KeyValue key="0" type="String" value="UDR_EXP" comment="Default Mapping for UDR" />
                    <KeyValue key="1" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 1" />
                    <KeyValue key="2" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 2" />
                    <KeyValue key="3" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 3" />
                    <KeyValue key="4" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 4" />
                    <KeyValue key="5" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 5" />
                    <KeyValue key="6" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 6" />
                    <KeyValue key="7" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 7" />
                    <KeyValue key="8" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 8" />
                    <KeyValue key="9" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 9" />
                    <KeyValue key="10" type="String" value="UDR_EXP" comment="Mapping for UDR_SUBS_TAG == 10" />
                </Node>

                <!-- Key Value 'key="BIR"' is used to define a Mapping for BIR records.     --> 
                <!-- If this key value is missing , in other word, if this line is missing, -->
                <!-- no mapping will take place for BIR records.                            -->
                <KeyValue key="BIR" type="String" value="BIR_EXP" comment="Mapping for BIR" />

                <!-- Key Value 'key="PAR"' is used to define a Mapping for PAR records.     --> 
                <!-- If this key value is missing , in other word, if this line is missing, -->
                <!-- no mapping will take place for PAR records.                            -->
                <KeyValue key="PAR" type="String" value="PAR_EXP" comment="Mapping for PAR" />

                <!-- Key Value 'key="CAR"' is used to define a Mapping for CAR records.     --> 
                <!-- If this key value is missing , in other word, if this line is missing, -->
                <!-- no mapping will take place for CAR records.                            -->
                <KeyValue key="CAR" type="String" value="CAR_EXP" comment="Mapping for CAR" />

                <!-- PN 00284759                                                            -->
                            <!-- Key Value 'key="DRR"' is used to define a Mapping for DRR records.     -->
                            <!-- If this key value is missing , in other word, if this line is missing, -->
                            <!-- no mapping will take place for DRR records.                            -->
                            <KeyValue key="DRR" type="String" value="DRR_EXP" comment="Mapping for DRR" />
                <!-- PN 00284306                                                            -->

                <!-- Key Value 'key="CIR"' is used to define a Mapping for CIR records.     -->
                <!-- If this key value is missing , in other word, if this line is missing, -->
                <!-- no mapping will take place for CIR records.                            -->
                <KeyValue key="CIR" type="String" value="CIR_EXP" comment="Mapping for CIR" /> 

            </Node>

            <Node name="STORAGE">
            <!-- Node "STORAGE" is used to define storage contexts for UDR variants                -->
            <!-- The following entries are for example purpose only and have to be adapted in an   -->
            <!-- actual environment                                                                -->
            <!-- Possible keys are "UDR", "BIR", "PAR", "CAR"                                      -->
            <!-- For possible values see table UDS_CONTEXT, column UDS_CONTEXT_ID. To identify     -->
            <!-- the variant of the storage context see table UDS_STORAGE, column UDS_VARIANT_CODE -->
            <!-- The following entries are for example purpose only and have to be adapted in an   -->
            <!-- actual environment                                                                -->

                <!-- Key Value 'key="UDR"' is used to define a Storage Context for UDR records. -->
                <!-- If this key value is missing , in other word, if this line is missing,     -->
                <!-- no storage context will be used for UDR records.                           -->
                <KeyValue key="UDR" type="String" value="1" comment="Storage Context for UDR variant" />

                <!-- Key Value 'key="BIR"' is used to define a Storage Context for BIR records. --> 
                <!-- If this key value is missing , in other word, if this line is missing,     -->
                <!-- no storage context will be used for BIR records.                           -->            
                <KeyValue key="BIR" type="String" value="7" comment="Storage Context for BIR variant" />            
            </Node>        
        </Node>
        <Node name="EOH_ONL">
                    <!-- Node "EOH_ONL" is used to configure EOH instances started in 'online' mode.       -->
                    <!-- For the time being, only UDR records are foreseen to be mapped by an EOH running  -->
                    <!-- in 'online' mode. Only one mapping key is used.                                   -->
            <Node name="MAPPING">
                        <KeyValue key="UDR" type="String" value={{ .Values.EohRegistry.udrOnline | quote }} comment="Mapping for UDR" /> 
            </Node>        
        </Node>
        <Node name="EOH_ICP_EXPORT">
                    <!-- Node "EOH_ICP_EXPORT" is used to configure EOH instances started in 'export' (-E) mode. -->
                    <KeyValue key="EXPORT_DIR" type="String" value={{ .Values.EohRegistry.exportDir | quote }} comment="target directory for ICP export" /> 
        </Node>
    </ComponentRegistry>
