apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-allow-data-client
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-network-data-client: 'true'
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-data-server: 'true'
      ports:
        #Note: If TLS connection is enabled DaTA uses dataPort+2
        - protocol: TCP
          port: {{ required "A valid .Values.global.dataClusterPort entry is required!" .Values.global.dataClusterPort }}
        - protocol: TCP
          port: {{ add .Values.global.dataClusterPort 2 }}
