apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-allow-gmd
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-network-gmd: 'true'
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-vmd: 'true'
  {{- range $externalVMD := .Values.externalVMDs }}
    - from:
        - ipBlock:
            cidr: {{ $externalVMD.cidr }}
      ports:
        - protocol: TCP
          port: {{ $externalVMD.port }}
  {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-vmd: 'true'
  {{- range $externalVMD := .Values.externalVMDs }}
    - to:
        - ipBlock:
            cidr: {{ $externalVMD.cidr }}
      ports:
        - protocol: TCP
          port: {{ $externalVMD.port }}
  {{- end }}