{{ if $.Values.global.secretManager.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-pwdmgr-allow-vault-client
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-pwdmgr-network-vault-client: 'true'
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: {{.Values.vault.cidr }}
      ports:
        - protocol: TCP
          port: {{.Values.vault.port }}
{{- end -}}