apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-dmfjob-standard-res.xml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  standard_1_res.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <!--

           Origins: LHS Telekom GmbH & Co KG

            Author: R&D Database Team, Dreieich

              Date: 12-Jul-2004

           Version: "@(#) lhsj_main/bscs/container/helm/ericssonBillingChart/charts/dmfChart/templates/configmap-standard-res-xml.yaml, , 22.15.12, 22.15.12 @@22.15.12 28-Nov-2022"

           Purpose: Resource list file


      Copyright (c) 2004 LHS Telekom GmbH & Co. KG

      The copyright in this work is vested in LHS.
      The information contained in this work (either in whole or in part)
      is confidential and must not be modified, reproduced, disclosed or
      disseminated to others or used for purposes other than that for which
      it is supplied, without the prior written permission of LHS.
      If this work or any part hereof is furnished to a third party by
      virtue of a contract with that party, use of this work by such party
      shall be governed by the express contractual terms between LHS, which
      is party to that contract and the said party.

      The information in this document is subject to change without notice
      and should not be construed as a commitment by LHS. LHS assumes no
      responsibility for any errors that may appear in this document. With
      the appearance of a new version of this document all older versions
      become invalid.

      All rights reserved
    -->

    <DMF_RESOURCE_LIST xmlns="BSS:Telco:Main:DataMigrationFramework" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="BSS:Telco:Main:DataMigrationFramework DMF_Resource.xsd">
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ADMINISTRATOR">
          <DB_NAME> bscsdb_admin </DB_NAME>
    <!--      <DB_SCHEMA> BDR_RO </DB_SCHEMA>  -->
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ACCOUNT_MANAGER">
          <DB_NAME> bscsdb_admin </DB_NAME>
    <!--      <DB_SCHEMA> BDR_ACCTMGR </DB_SCHEMA> -->
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ACCOUNT_MANAGER_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
    <!--      <DB_SCHEMA> BDR_ACCTMGR </DB_SCHEMA> -->
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="DATA_VAULT_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
    <!--      <DB_SCHEMA> BDR_ADM </DB_SCHEMA> -->
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="DATA_VAULT_ADMIN_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
    <!--      <DB_SCHEMA> BDR_ADM </DB_SCHEMA> -->
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="SYSTEM_ADMINISTRATOR_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
    <!--      <DB_SCHEMA> BDR_RO </DB_SCHEMA>  -->
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="REPOSITORY">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> DMF </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="DMF_REPOSITORY">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA>DMFADM</DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="DMF_REPOSITORY_R">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA>DMFADM</DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BSCS">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> SYSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="GEN_DDL_BSCS">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD>  </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA> SYSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="GEN_DDL_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD>  </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="ORA_APP">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> ORA_APP_USR </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="ORA_FIS">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> FIS </DB_SCHEMA>
          <DB_PASSWORD>  </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="ORA_FIS_ORA">
          <DB_NAME> ora_app_database_name </DB_NAME>
          <DB_SCHEMA> BSCS </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BIS_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> BISADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BIS">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> BIS </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="WMS_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> WMSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="WMS">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> WMS </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="OMS_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> OMSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="JBPM">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> JBPM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="JBPM_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> JBPMADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="DCS_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> DCSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="DCS">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> DCS </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BSCS_USER_ADMIN">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> BSCS_USER_ADMIN </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BSCS_USER_ADMIN_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA> BSCS_USER_ADMIN </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="PWDMGR">
          <DB_NAME> bscsdb_admin </DB_NAME>
          <DB_SCHEMA> PWDMGR </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="PWDMGR_UDR">
          <DB_NAME> rtxdb_admin </DB_NAME>
          <DB_SCHEMA> PWDMGR </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
          <DB_ACCESS_METHOD> WALLET_PROXY </DB_ACCESS_METHOD>
       </RESOURCE>

       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BSCS_TO_RTX_LINK">
          <DB_NAME> {{ tpl .Values.bscsToRtxNetDescriptor . }} </DB_NAME>
          <DB_SCHEMA> SYSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="BSCS_ADMIN_TO_RTX_LINK">
          <DB_NAME> {{ tpl .Values.bscsToRtxNetDescriptor . }} </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
       </RESOURCE>

       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="RTX_TO_BSCS_LINK">
          <DB_NAME> {{ tpl .Values.rtxToBscsNetDescriptor . }} </DB_NAME>
          <DB_SCHEMA> SYSADM </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
       </RESOURCE>
       <RESOURCE xsi:type="DB_ORACLE" ResourceKey="RTX_ADMIN_TO_BSCS_LINK">
          <DB_NAME> {{ tpl .Values.rtxToBscsNetDescriptor . }} </DB_NAME>
          <DB_SCHEMA> {{ .Values.global.dbSystemUserName }} </DB_SCHEMA>
          <DB_PASSWORD> </DB_PASSWORD>
       </RESOURCE>

    </DMF_RESOURCE_LIST>
