{{- if .Values.global.rbac.sa_roles_create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
automountServiceAccountToken: false
{{- end -}}
