apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-soi-scs
data:
  SCS_4.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE SOI PUBLIC "SOIDefinition.dtd" "SOIDefinition.dtd">
    <SOI soiName="SCS" soiVersion="4">
        <COMMAND cmdVersion="CMD_1_0"   cmdName="SESSION.CHANGE"/>
        <COMMAND cmdVersion="CMD_2_0"     cmdName="SCHEDULED_JOB.READ"/>
        <COMMAND cmdVersion="CMD_1_0"    cmdName="SCHEDULED_JOB_RIGHTS.READ"/>
        <COMMAND cmdVersion="CMD_2_0"     cmdName="SCHEDULED_JOB.WRITE"/>
        <COMMAND cmdVersion="CMD_2_0"     cmdName="SCHEDULED_JOB.CREATE"/>
        <COMMAND cmdVersion="CMD_5_0"     cmdName="SCHEDULED_JOB.SEARCH"/>
        <COMMAND cmdVersion="CMD_2_0"     cmdName="SCHEDULED_JOB.START"/>
        <COMMAND cmdVersion="CMD_1_0"     cmdName="SCHEDULED_JOB.STOP"/>
        <COMMAND cmdVersion="CMD_2_0"     cmdName="SCHEDULED_JOB_TYPE.READ"/>
        <COMMAND cmdVersion="CMD_1_0"      cmdName="SCHEDULED_JOB_STATES.READ"/>
        <COMMAND cmdVersion="CMD_1_0"      cmdName="SCHEDULED_JOB_DEFINITION.READ"/>
    </SOI>

  SCS_5.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE SOI PUBLIC "SOIDefinition.dtd" "SOIDefinition.dtd">
    <SOI soiName="SCS" soiVersion="5">
        <COMMAND cmdVersion="CMD_1_0"   cmdName="SESSION.CHANGE"/>
        <COMMAND cmdVersion="CMD_2_0"   cmdName="SCHEDULED_JOB.READ" webService="yes"/>
        <COMMAND cmdVersion="CMD_1_0"  cmdName="SCHEDULED_JOB_RIGHTS.READ"/>
        <COMMAND cmdVersion="CMD_2_0"   cmdName="SCHEDULED_JOB.WRITE" webService="yes"/>
        <COMMAND cmdVersion="CMD_2_0"   cmdName="SCHEDULED_JOB.CREATE" webService="yes"/>
        <COMMAND cmdVersion="CMD_6_0"   cmdName="SCHEDULED_JOB.SEARCH" restService="yes"/>
        <COMMAND cmdVersion="CMD_2_0"   cmdName="SCHEDULED_JOB.START"/>
        <COMMAND cmdVersion="CMD_1_0"   cmdName="SCHEDULED_JOB.STOP"/>
        <COMMAND cmdVersion="CMD_2_0"   cmdName="SCHEDULED_JOB_TYPE.READ"/>
        <COMMAND cmdVersion="CMD_1_0"    cmdName="SCHEDULED_JOB_STATES.READ" webService="yes"/>
        <COMMAND cmdVersion="CMD_1_0"    cmdName="SCHEDULED_JOB_DEFINITION.READ"/>
    </SOI>
