apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-wms-workgroup.xml
data:
  Registry_WMS_Workgroup.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >
    <ComponentRegistry>

        <Node name="WMS Settings">
            <Node name="Workgroup Search">
                <KeyValue key="MaxResultSetSize" type="Integer" value="{{ .Values.debtColl.wmsSettings.WorkgroupSearch.MaxResultSetSize }}"/>
                <KeyValue key="DefaultResultSetSize" type="Integer" value="{{ .Values.debtColl.wmsSettings.WorkgroupSearch.DefaultResultSetSize }}"/>
                <KeyValue key="DefaultOutput" value="WG_ID, WG_ID_PUB, WG_DES, BU_ID"/>
                <KeyValue key="BaseTable" value="WORKGROUP_DEFINITION"/>
                <KeyValue key="BaseTableAlias" value="WG"/>
                <KeyValue key="DefaultNumberOfCharactersBeforeWildcard" type="Integer" value="{{ .Values.debtColl.wmsSettings.WorkgroupSearch.DefaultNumberOfCharactersBeforeWildcard }}"/>

                <Node name="Attributes">
                    <Node name="WG_ID">
                        <KeyValue key="SelectClause" value="WG.WORKGROUP_ID" />
                    </Node>

                    <Node name="WG_ID_PUB">
                        <KeyValue key="SelectClause" value="WG.SHORT_DES" />
                        <KeyValue key="ConditionWhereClause" type="String"    value="WG.SHORT_DES"/>
                        <KeyValue key="SupportsCaseInsensitiveSearch" type="Boolean" value="true"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true"/>
                    </Node>

                    <Node name="WG_DES">
                        <KeyValue key="SelectClause" value="WG.DES" />
                        <KeyValue key="ConditionWhereClause" type="String"    value="WG.DES"/>
                        <KeyValue key="SupportsCaseInsensitiveSearch" type="Boolean" value="true"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true"/>
                    </Node>

                    <Node name="BU_ID">
                           <KeyValue key="SelectClause" value="WG.BUSINESS_UNIT_ID" />
                           <KeyValue key="ConditionWhereClause" type="String"    value="WG.BUSINESS_UNIT_ID"/>
                    </Node>

                    <Node name="USERNAME">
                        <KeyValue key="ConditionWhereClause" value="UWM.USERNAME"/>
                        <KeyValue key="SupportsWildcardSearch" type="Boolean" value="true"/>
                           <Node name="FromClauses">
                               <KeyValue key="USER_WORKGROUP_MAP UWM" value=""/>
                           <!-- USC -why are the workqueue involved in the workgroup search??
                               <KeyValue key="USER_WORKQUEUE_MAP UWQM" value=""/>
                               <KeyValue key="WORKQUEUE_WORKGROUP_MAP WWM" value=""/>
                               -->
                           </Node>
                           <Node name="JoinWhereClauses">
                               <Node name="InputAttributes">
                                <KeyValue key="UWM.WORKGROUP_ID = WG.WORKGROUP_ID" value=""/>
                                <!-- USC -why are the workqueue involved in the workgroup search??
                                <KeyValue key="U.USERNAME = UWQM.USERNAME" value=""/>
                                <KeyValue key="UWQM.WORKQUEUE_ID = WWM.WORKQUEUE_ID" value=""/>
                                <KeyValue key="WWM.WORKGROUP_ID = WG.WORKGROUP_ID" value=""/>
                                -->
                            </Node>
                           </Node>
                    </Node>

                </Node>
            </Node>
        </Node>
    </ComponentRegistry>
