apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-eventadaptor-applicationcontext.xml
data:
  eventAdaptor-ApplicationContext.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:util="http://www.springframework.org/schema/util"
           xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
                               http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.3.xsd"
           default-lazy-init="true">

        <!-- CONFIGURABLE PART BEGIN - Connection Factories and Message Listener Containers -->
        <!--
            It's possible to configure how many connection factories and Message Listeners Containers as needed.

            - A connection factory holds information about how CEB will connect to DaTA
              (Application Name, Application Number, Child Number and sub-profile setup)
            - The Message Listener Container is the bean responsible to receive and handle each message.

            When setting new factories / containers, please consider the following rules:

            Connection Factories:
            =====================

            1) The first constructor-arg is the "Application Name". I.e: CEB
            2) The second constructor-arg is used to set the "Application Number"
            3) The third constructor-arg is used to set the "Child Number"
            4) The property "attributeValueMap" will set the DaTA sub-profile where it will be connected.

            Complete Bean Example:

            <bean id="eventConnectionFactory1" class="com.lhs.dxl.jms.DXLDaTAConnectionFactory">
                <constructor-arg value="CEB"></constructor-arg>
                <constructor-arg type="int" value="0"></constructor-arg>
                <constructor-arg type="int" value="0"></constructor-arg>
                <property name="attributeValueMap">
                    <map>
                        <entry key="30" value="2"/>
                        <entry key="127" value="E"/>
                        <entry key="16" value="0"/>
                    </map>
                </property>
            </bean>

            Message Listener Containers:
            ============================

            1) Each Message Listener Container beans should have its name starting with "eventContainer", otherwise the Event Adaptor will
               not initialize them. Example: eventContainer1, eventContainer2, etc.
            2) The property "messageListener" should always point to the "eventListener" bean.
            3) The property "destination" should always point to the "defaultDestination" bean:
            4) The property "sessionTransacted" should be always set to "true". This will ensure that CEB rollback the message to DaTA in case of
               crash before processing the message on DCS.
            5) The property "sessionAcknowledgeMode" should be always with: the constant value: javax.jms.Session.CLIENT_ACKNOWLEDGE. This complements
               the rollback configuration set in the previous step.
            6) Each Message Listener Container should have its own Connection Factory set in the "connectionFactory" property.
            7) The property "concurrentConsumers" indicates how many threads of this specific containers will be started to consume DaTA messages.

            Complete Bean Example:
            <bean id="eventContainer1" class="org.springframework.jms.listener.SimpleMessageListenerContainer">
               <property name="messageListener" ref="eventListener"/>
               <property name="destination" ref="defaultDestination"/>
               <property name="sessionTransacted" value="true"/>
               <property name="sessionAcknowledgeMode"><util:constant static-field="javax.jms.Session.CLIENT_ACKNOWLEDGE"/></property>
               <property name="connectionFactory" ref="eventConnectionFactory1"/>
               <property name="concurrentConsumers" value="1"/>
           </bean>
         -->

        <bean id="eventConnectionFactory1" class="com.lhs.dxl.jms.DXLDaTAConnectionFactory">
            <constructor-arg value="CEB"></constructor-arg>
            <constructor-arg type="int" value="0"></constructor-arg>
            <constructor-arg type="int" value="0"></constructor-arg>
            <property name="attributeValueMap">
                <map>
{{ .Values.debtColl.cebSettings.evenConnFactory1_map | indent 20 }}
                </map>
            </property>
        </bean>

        <bean id="eventContainer1" class="com.lhs.dxl.support.SimpleMessageListenerContainerInitializer">
            <property name="connectionFactory" ref="eventConnectionFactory1"/>
            <property name="destination" ref="defaultDestination"/>
            <property name="messageListener" ref="eventListener"/>
            <property name="concurrentConsumers" value="1"/>
            <property name="simpleMessageListenerContainerBeanName" value="eventListenerContainer1"/>
            <property name="retryWaitTime" value="5000"/>
            <property name="sessionTransacted" value="true"/>
            <property name="sessionAcknowledgeMode"><util:constant static-field="javax.jms.Session.CLIENT_ACKNOWLEDGE"/></property>
        </bean>
        <!-- CONFIGURABLE PART END - Connection Factories and Message Listener Containers -->

        <!-- NOT CONFIGURABLE PART - BEGIN : Event Adaptor Listener, Delegate and destination -->
        <!-- DO NOT CHANGE - Re-use these beans while creating Message Listener Containers -->
        <bean id="eventDelegateListener" class="com.lhs.ceb.event.EventMessageListener" destroy-method="end">
            <property name="cirMapping" ref="cirEventMapping"/>
            <property name="cebServiceAccessorPool" ref="cebServiceAccessorPool"/>
            <property name="rejectSender" ref="eventRejectSender" />
            <!-- Those retry values must be bellow 99 otherwise the CIR will never be filled with a reason code. -->
            <property name="maxNumberOfEventOrderRetries" value="5"/>
            <property name="maxNumberOfEventNotAllowedRetries" value="5"/>
            <property name="maxNumberOfCollectibleNotReadyRetries" value="5"/>
            <property name="maxNumberOfOptimistickRetries" value="5" />
        </bean>

        <bean id="cirEventMapping" class="com.lhs.ceb.CIREventMapping">
            <property name="eventIdentificationPart" value="204" />
            <property name="eventIdentificationMember" value="337" />
            <property name="eventIdentificationElement" value="623" />
        </bean>

        <bean id="eventListener" class="org.springframework.jms.listener.adapter.MessageListenerAdapter">
            <property name="delegate" ref="eventDelegateListener"/>
            <property name="defaultListenerMethod" value="processMessage"/>
        </bean>

        <bean id="eventRejectSender" class="org.springframework.jms.core.JmsTemplate">
            <property name="connectionFactory" ref="eventConnectionFactory1"/>
            <property name="defaultDestination" ref="defaultDestination"/>
        </bean>

        <!-- Beans used by all adaptors -->
        <import resource="classpath*:common-ApplicationContext.xml"/>
        <!-- NOT CONFIGURABLE PART END: Event Adaptor Listener, Delegate and destination -->
    </beans>
