apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-registry-wms-notehistory.xml
data:
  Registry_WMS_NoteHistory.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >
    <ComponentRegistry>

        <Node name="WMS Settings">
            <Node name="NoteHistory Search">
                <KeyValue key="MaxResultSetSize" type="Integer" value="{{ .Values.debtColl.wmsSettings.NoteHistorySearch.MaxResultSetSize }}" />
                <KeyValue key="DefaultResultSetSize" type="Integer" value="{{ .Values.debtColl.wmsSettings.NoteHistorySearch.DefaultResultSetSize }}" />
                <KeyValue key="DefaultOutput" type="String" value="NOTE, USERNAME, CREATE_DATE" />
                <KeyValue key="BaseTable" type="String" value="USER_WORK_NOTE" />
                <KeyValue key="BaseTableAlias" type="String" value="UWN" />
                <KeyValue key="DefaultNumberOfCharactersBeforeWildcard" type="Integer" value="{{ .Values.debtColl.wmsSettings.NoteHistorySearch.DefaultNumberOfCharactersBeforeWildcard }}" />

                <Node name="Attributes">
                    <Node name="WE_ID">
                        <KeyValue key="ConditionWhereClause" value="UWN.WE_ID" />
                    </Node>

                    <Node name="DATE_FROM">
                        <KeyValue key="ConditionWhereClause" value="UWN.CREATE_DATE" />
                        <KeyValue key="Operator" value="&gt;=" />
                    </Node>
                    <Node name="DATE_UNTIL">
                        <KeyValue key="ConditionWhereClause" value="UWN.CREATE_DATE" />
                        <KeyValue key="Operator" value="&lt;=" />
                    </Node>
                    <Node name="ONLY_MANUAL_NOTES">
                        <KeyValue key="ConditionWhereClause" value="UWN.GENERATION_TYPE" />
                    </Node>

                    <Node name="NOTE">
                        <KeyValue key="SelectClause" type="String" value="UWN.NOTE" />
                    </Node>

                    <Node name="USERNAME">
                        <KeyValue key="SelectClause" type="String" value="UWN.CREATE_USER" />
                    </Node>

                    <Node name="CREATE_DATE">
                        <KeyValue key="SelectClause" type="String" value="UWN.CREATE_DATE" />
                    </Node>

                </Node>
            </Node>
        </Node>
    </ComponentRegistry>
