apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-cms-log4j2.xml
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!-- The com.lhs.ccb.sfw.utilities package contains custom logging plugins that are loaded by Log4j2. -->
    <Configuration packages="com.lhs.ccb.sfw.utilities">

        <Properties>
            <!-- The log-path defines the location of the log files -->
            <Property name="log-path">${sys:java.io.tmpdir}</Property>
            <Property name="processId">${sys:processId}</Property>
        </Properties>

        <Appenders>
            <!-- The ConsoleAppender defines how the logs will be displayed in System.out. -->
            <Console name="ConsoleAppender" target="SYSTEM_OUT">
                <PatternLayout>
                    <pattern>
                        %slp
                    </pattern>
                </PatternLayout>
            </Console>
            <!-- The RollingFile defines the name of the log files as well as their rolling policies -->
            <RollingFile name="SystemLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.system.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.system_%d{yyyy-MM-dd}_%03i.log">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="1 GB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="FilteringSystemLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.filtered_system.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.filtered_system_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Filters>
                    <ThreadContextMapFilter onMatch="ACCEPT" onMismatch="DENY">
                        <KeyValuePair key="FilteredLogging" value="FilteredLogging"/>
                    </ThreadContextMapFilter>
                </Filters>
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="DatabaseLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.database.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.database_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="1 GB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="FilteringDatabaseLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.filtered_database.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.filtered_database_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Filters>
                    <ThreadContextMapFilter onMatch="ACCEPT" onMismatch="DENY">
                        <KeyValuePair key="FilteredLogging" value="FilteredLogging"/>
                    </ThreadContextMapFilter>
                </Filters>
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="WorkflowLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.workflow.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.workflow_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="1 GB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="FilteringWorkflowLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.filtered_workflow.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.filtered_workflow_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Filters>
                    <ThreadContextMapFilter onMatch="ACCEPT" onMismatch="DENY">
                        <KeyValuePair key="FilteredLogging" value="FilteredLogging"/>
                    </ThreadContextMapFilter>
                </Filters>
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="StackDumpLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.stackDump_${processId}.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.stackDump_${processId}_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="1 GB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="DBConnectionOwnerLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.dbConnection_${processId}.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.dbConnection_${processId}_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="1 GB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="JacorbFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.jacorb_${processId}.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.jacorb_${processId}_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="FilteringJacorbFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.filtered_jacorb.log"
                filePattern="${log-path}/CMS.{HOSTNAME}.filtered_jacorb_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Filters>
                    <ThreadContextMapFilter onMatch="ACCEPT" onMismatch="DENY">
                        <KeyValuePair key="FilteredLogging" value="FilteredLogging"/>
                    </ThreadContextMapFilter>
                </Filters>
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="PerformanceLogFileAppender"
                fileName="${log-path}/CMS.{HOSTNAME}.performance.csv"
                filePattern="${log-path}/CMS.{HOSTNAME}.performance_%d{yyyy-MM-dd}_%03i.csv"
                createOnDemand="true">
                <CsvParameterLayout header="commandName,timestamp,duration,consumedMemory,eventExecutionId,sqlDuration%n" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true" />
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax" />
            </RollingFile>
        </Appenders>

        <!-- Defines the Loggers with their names and logging levels. -->
        <Loggers>
            <Logger name="SystemLog" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
                <!--
                    ##########################################################
                    Settings for DTRules (used only in DTRules 3PP)
                    ##########################################################

                    OFF Turns DTRules trace logging off (= default)
                    ON  Turns DTRules trace logging on (read notes below, before turning on)

                    In general, the level of DTRules logging is mapped by the level of SystemLog tracing:
                    SystemLog level    DTRules log level
                    DEBUG or higher -> DTState.TRACE is activated (only if DTRules.trace=ON)
                    TRACE or higher -> DTState.DEBUG is activated
                    FINEST or ALL   -> DTState.VERBOSE is activated

                    If DTRules.trace = ON, DTState.TRACE logging is activated.
                    This leads to a logging of all chosen dtrule entities
                    and causes a constantly increasing heap space allocation.

                    DTRules logging with DTState.DEBUG and/or DTState.VERBOSE
                    is not affected by the setting of DTRules.trace.
                -->
                <Property name="DTRules.trace" value="OFF" />
            </Logger>
            <Logger name="DatabaseLog" level="off" additivity="false">
                <AppenderRef ref="ConsoleAppender" level="off"/>
                <AppenderRef ref="DatabaseLogFileAppender" level="off"/>
                <AppenderRef ref="FilteringDatabaseLogFileAppender" level="all"/>
            </Logger>
            <Logger name="WorkflowLog" level="info" additivity="false">
                <AppenderRef ref="WorkflowLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringWorkflowLogFileAppender" level="all"/>
            </Logger>
            <Logger name="StackDumpLog" level="off" additivity="false">
                <AppenderRef ref="StackDumpLogFileAppender" level="off"/>
                <!-- Stack dump generation interval in milliseconds -->
                <Property name="interval" value="60000" />
            </Logger>
            <Logger name="DBConnectionOwnerLog" level="off" additivity="false">
                <AppenderRef ref="DBConnectionOwnerLogFileAppender" level="off"/>
            </Logger>
            <Logger name="javax.enterprise.resource.corba" level="warn" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="warn"/>
                <AppenderRef ref="ConsoleAppender" level="warn"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="javax.enterprise.resource.corba._DEFAULT_.rpc.transport" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error" />
                <AppenderRef ref="ConsoleAppender" level="error" />
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.jgroups" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error"/>
                <AppenderRef ref="ConsoleAppender" level="error"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.apache.commons.httpclient" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="httpclient.wire.header" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="httpclient.wire.content" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.hibernate.sql" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.hibernate.engine.query" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.hibernate.persister" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.apache.http" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.apache.http.impl.conn" level="info" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="info"/>
                <AppenderRef ref="ConsoleAppender" level="info"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.apache.tomcat.util.scan.StandardJarScanner" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error"/>
                <AppenderRef ref="ConsoleAppender" level="error"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.apache.catalina.startup.TldConfig" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error"/>
                <AppenderRef ref="ConsoleAppender" level="error"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.springframework.batch.core.step.item.ChunkMonitor" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error"/>
                <AppenderRef ref="ConsoleAppender" level="error"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.springframework.batch" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error"/>
                <AppenderRef ref="ConsoleAppender" level="error"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.quartz" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="error"/>
                <AppenderRef ref="ConsoleAppender" level="error"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Logger>
            <Logger name="org.jacorb" level="warn" additivity="false">
                <AppenderRef ref="JacorbFileAppender" level="warn"/>
                <AppenderRef ref="ConsoleAppender" level="warn"/>
                <AppenderRef ref="FilteringJacorbFileAppender" level="all"/>
            </Logger>
            <Logger name="PerformanceLog" level="off" additivity="false">
                <AppenderRef ref="PerformanceLogFileAppender" level="off"/>
                <AppenderRef ref="ConsoleAppender" level="off"/>
            </Logger>
            <Root level="warn" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" level="warn"/>
                <AppenderRef ref="ConsoleAppender" level="warn"/>
                <AppenderRef ref="FilteringSystemLogFileAppender" level="all"/>
            </Root>
        </Loggers>
    </Configuration>
