apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-cah-pvc-archive
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.archive | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.archive }}
