apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-pvc-exchange-files-out
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.exchangeFilesOut | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.exchangeFilesOut }}
