apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-gmd-pvc-artifact
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.gmd | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.gmd }}
