apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-dih-pvc-input
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.dih | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.dih }}
