apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-tools-pvc-esh
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.esh | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.esh }}
