apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-pvc-data-1-workdir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName.data1workdir | default .Values.global.storageClassName.rwo | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.data1workdir }}
