apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-pvc-data-batch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName.databatch | default .Values.global.storageClassName.rwo | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.databatch }}
