apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-bss-eb-evh-pvc-output
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName.evhOutput | default .Values.global.storageClassName.rwm | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requestSize.evhOutput }}
