apiVersion: v1
kind: Service
metadata:
  name: eric-bss-eb-vmdrep
  labels:
    run: eric-bss-eb-vmdrep
    app: {{ template "eric-bss-eb-vmdrep.name" . }}
    chart: {{ template "eric-bss-eb-vmdrep.chart" . }}
    {{- include "eric-bss-eb-vmdrep.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- include "eric-bss-eb-vmdrep.productInfo" . | indent 4 }}
spec:
  ports:
    - name: vmdrep
      port: {{ .Values.service.clusterPort }}
      protocol: TCP
  selector:
    app: eric-bss-eb-vmdrep
    app.kubernetes.io/instance: {{ .Release.Name }}
