apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-ff-log4j2.xml
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!-- The com.lhs.ccb.sfw.utilities package contains custom logging plugins that are loaded by Log4j2. -->
    <Configuration monitorInterval="10" packages="com.lhs.ccb.sfw.utilities">

        <Properties>
            <!-- The log-path defines the location of the log files -->
            <Property name="log-path">${sys:java.io.tmpdir}</Property>
        </Properties>

        <Appenders>
            <!-- The ConsoleAppender defines how the logs will be displayed in System.out. -->
            <Console name="ConsoleAppender" target="SYSTEM_OUT">
                <PatternLayout>
                    <pattern>
                        %slp
                    </pattern>
                </PatternLayout>
            </Console>
            <!-- The RollingFile defines the name of the log files as well as their rolling policies -->
            <RollingFile name="SystemLogFileAppender"
                fileName="${log-path}/fedfactory.{HOSTNAME}.log"
                filePattern="${log-path}/fedfactory.{HOSTNAME}.%d{yyyy-MM-dd}_%03i.log">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
            <RollingFile name="JacorbFileAppender"
                fileName="${log-path}/fedfactory.{HOSTNAME}.jacorb_${processId}.log"
                filePattern="${log-path}/fedfactory.{HOSTNAME}.jacorb_${processId}_%d{yyyy-MM-dd}_%03i.log"
                createOnDemand="true">
                <PatternLayout pattern="%slp" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="500 MB" />
                    <TimeBasedTriggeringPolicy modulate="true"/>
                </Policies>
                <DefaultRolloverStrategy fileindex="nomax"/>
            </RollingFile>
        </Appenders>

        <!-- Defines the Loggers with their names and logging levels. -->
        <Loggers>
            <Logger name="SystemLog" level="{{.Values.logging.systemLogLevel | default "info"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba" level="warn" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba._DEFAULT_.rpc.transport" level="{{.Values.logging.corbaDefaultRpcTransportLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="com.lhs.nscrawler.INSCrawler" level="{{.Values.logging.INSCrawlerLevel | default "warn"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba._DEFAULT_.rpc.transport" level="error" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba._DEFAULT_.rpc.protocol" level="{{.Values.logging.corbaDefaultRpcProtocolLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba._DEFAULT_.rpc.encoding" level="{{.Values.logging.corbaDefaultRpcEncodingLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba._CORBA_.rpc.presentation" level="{{.Values.logging.corbaCorbaRpcPresentationLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="javax.enterprise.resource.corba._CORBA_.rpc.protocol" level="{{.Values.logging.corbaDefaultRpcProtocolLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="sun.rmi.loader" level="{{.Values.logging.loaderLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="org.jgroups" level="{{.Values.logging.jgroupsLevel | default "error"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Logger name="org.jacorb" level="{{.Values.logging.jacorbLevel | default "warn"}}" additivity="false">
                <AppenderRef ref="JacorbFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Logger>
            <Root level="{{.Values.logging.level | default "warn"}}" additivity="false">
                <AppenderRef ref="SystemLogFileAppender" />
                <AppenderRef ref="ConsoleAppender" />
            </Root>
        </Loggers>
    </Configuration>

