apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-allow-lem-server
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-network-lem-server: 'true'
  ingress:
    - from:
        - podSelector:
            matchLabels:
              eric-bss-eb-network-lem-client: 'true'
  egress:
    - ports:
        - protocol: UDP
          port: 5093
  policyTypes:
    - Ingress
    - Egress
