# This policy controls internal (to the K8s Cluster) access to License Server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-allow-lem-client
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-network-lem-client: 'true'
  egress:
    - ports:
        - protocol: TCP
          port: 4322
        - protocol: TCP
          port: 43221
  policyTypes:
    - Egress
