# Default values for nsChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Allowed: 1
replicaCount: 1

imageCredentials:
  namingservice:
    repoPath:
    pullPolicy:
    registry:
      url:
  nsjob:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  namingservice:
    name: "eric-bss-eb-ns"
    tag: "22.15.12"
  nsjob:
    name: "eric-bss-eb-ns"
    tag: "22.15.12"

service:
  port: 2010

containerPorts:
  nsContainerPort: 2010

jacorb:
  log:
    logLevel: 2
    logFileAppend: "off"
    logFileMaxSize: 0
    dumpOutgoingMessages: "off"
    dumpIncomingMessages: "off"
  orbConnection:
    retries: 5
    retryInterval: 500
    clientIdleTimeout: 0
    clientConnectTimeout: 90000
    clientPendingReplyTimeout: 2000000
  poaConfig:
    threadPoolMax: 20
    threadPoolMin: 5

resources:
  limits:
    cpu: 1
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 16Mi

#A local nodeSelector definition has priority over the global definition.
nodeSelector: {}

# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b

#Example:
#nodeSelector:
#  kubernetes.io/hostname: "<hostname>"


suffix:
