apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-bgh-logging.properties
data:
  logging.properties: |
    # logging.properties
    # This file is provided as config map

    handlers = {{.Values.logging.handlers | default "ProcessIDFileHandler"}}

    # All Levels
    # Possible Levels in ascending order FINEST (lowest value), FINER, FINE, CONFIG, INFO, WARNING, SEVERE (highest value)
    .level = {{.Values.logging.level | default "SEVERE"}}

    # Possible Levels in ascending order FINEST (lowest value), FINER, FINE, CONFIG, INFO, WARNING, SEVERE (highest value)
    ProcessIDFileHandler.level = {{.Values.logging.processIDFileHandlerLevel | default "SEVERE"}}

    # ProcessIDFileHandler is a subclass of FileHandler and it is impossible to set the formatter in a different way
    java.util.logging.FileHandler.formatter = {{.Values.logging.fileHandlerFormatter | default "java.util.logging.SimpleFormatter"}}
    java.util.logging.FileHandler.append = {{.Values.logging.fileHandlerAppend | default false}}

    # Level of logger named "FOP" which is the FOUserAgent-Logger
    # Possible Levels in ascending order FINEST (lowest value), FINER, FINE, CONFIG, INFO, WARNING, SEVERE (highest value)
    FOP.level = {{.Values.logging.FOPLevel | default "SEVERE"}}
