apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eric-bss-eb-dmf-allow-database-client
spec:
  podSelector:
    matchLabels:
      eric-bss-eb-dmf-network-database-client: 'true'
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: {{ .Values.global.databaseServerPort }}
        - protocol: UDP
          port: {{ .Values.global.databaseServerPort }}
        {{- range $ports := $.Values.global.databaseServerAdditionalPorts }}
        - protocol: TCP
          port: {{ $ports.port }}
        - protocol: UDP
          port: {{ $ports.port }}
        {{ end }}
        - protocol: TCP
          port: {{ .Values.global.rtxDatabaseServerPort }}
        - protocol: UDP
          port: {{ .Values.global.rtxDatabaseServerPort }}
        {{- range $ports := $.Values.global.rtxDbAdditionalPorts }}
        - protocol: TCP
          port: {{ $ports.port }}
        - protocol: UDP
          port: {{ $ports.port }}
        {{ end }}
