# Default values for Volumes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#used to add suffix to volume names and claims, also to host path directory. Can be empty.
#used with dash upfront for better readability e.g. -ericssonBilling
global:
  suffix: -eb
  storageClassName:
    rwm: network-file
    rwo: network-block

pvc:
  requestSize:
    beeJobsInput: 1Gi
    beeJobsOutput: 1Gi
    docs: 1Gi
    cab: 1Gi
    nsShare: 1Gi
    print: 1Gi
    pwdmgrSecurity: 100Mi
    xref: 1Gi
    lem: 100Mi
    logs: 5Gi
    seclogs: 1Gi
    coredump: 5Gi
    pids: 1Mi
    dataworkdir: 1Gi
    data1workdir: 1Gi
    datafailinworkdir: 1Gi
    databatch: 1Gi
    dbscripts: 1Gi
    dmfjobLog: 1Gi
    dmfLog: 1Gi
    archive: 1Gi
    dih: 1Gi
    exchangeFilesOut: 1Gi
    fih: 1Gi
    gmd: 1Gi
    tools: 1Gi
    rlhBab: 1Gi
    eohOutput: 1Gi
    evhOutput: 1Gi
    esh: 1Gi
    workflows: 100Mi
  storageClassName:
    beeJobsInput: network-file
    beeJobsOutput: network-file
    docs: network-file
    cab: network-file
    nsShare: network-file
    print: network-file
    pwdmgrSecurity: network-file
    xref: network-file
    lem: network-file
    logs: network-file
    seclogs: network-file
    coredump: network-file
    pids: network-file
    dataworkdir: network-block
    data1workdir: network-block
    datafailinworkdir: network-block
    databatch: network-block
    dbscripts: network-file
    dmfjobLog: network-file
    dmfLog: network-file
    archive: network-file
    dih: network-file
    exchangeFilesOut: network-file
    fih: network-file
    gmd: network-file
    tools: network-file
    rlhBab: network-file
    eohOutput: network-file
    evhOutput: network-file
    esh: network-file
    workflows: network-file
