{{- if .Values.global.rbac.sa_roles_create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eric-bss-eb-lem-regular-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
{{- end -}}
