apiVersion: v2
appVersion: "1.0"
description: The root Helm chart for Database tools
name: eric-bss-eb-database
version: 22.15.12+0

dependencies:
- name: eric-bss-eb-dmf-networkpolicies
  version: 22.15.12+0
  repository: file://./charts/networkpoliciesChart
  condition: eric-bss-eb-dmf-networkpolicies.enabled

- name: eric-bss-eb-dmf-rbac
  version: 22.15.12+0
  repository: file://./charts/rbacDmfChart
  condition: eric-bss-eb-dmf-rbac.enabled

- name: eric-bss-eb-dmf
  version: 22.15.12+0
  repository: file://./charts/dmfChart
  condition: eric-bss-eb-dmf.enabled
