# Default values for rrmChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  eric-bss-eb-rrm:
    repoPath:
    pullPolicy:
    registry:
      url:
  init-wait-for-data:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  eric-bss-eb-rrm:
    name: "eric-bss-eb-rrm"
    tag: "22.15.12"
  init-wait-for-data:
    name: "eric-bss-eb-wait-for-condition"
    tag: "22.15.12"

# Grace period for POD termination, in which the POD can shut down gracefully.
# After that period, k8s will terminate the POD un-gracefully (SIGKILL).
# Adapt this value in case the POD needs more time to terminate gracefully,
#   e.g. in case the PID-file remains after POD termination.
# Note, after the POD has terminated gracefully, the terminationGracePeriodSeconds is stopped immediately.
#       So it does not harm to specify a big value here.
terminationGracePeriodSeconds: 60

#DATA_RETRY_TIME, DATA_RETRY_TIME_MAX
#By default, there is no definition for a time interval in which applications try to reconnect to DaTA.
#If you set the environment variable, the value represents the time interval an application waits
#until it tries to reconnect to DaTA.
#Subsequent connection retries are performed under the following conditions:
# - A double time interval has elapsed and has exceeded a maximum of 60 seconds.
# - A double time interval has elapsed and the value specified by DATA_RETRY_TIME_MAX has been exceeded
dataRetry:
  dataRetryTime:
  dataRetryTimeMax:

resources:
  limits:
    cpu: 1000m
    memory: 5Gi
  requests:
    cpu: 100m
    memory: 64Mi

rrmCronJobs:
  - name: "rerating-job"
    schedule: "30 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    startParameters: "-c 1"
    # To generate tracefiles, it is necessary set the tracefile name in the variables below.
    # These files will be stored in the log PVC.
    tracingAndLogging:
      bscsErrorTimestamp: ""
      # dtaTracefile: "dta.rerating-job.trc"
      dtaTracefile: ""
      # dxlTracefile: "dxl.rerating-job.trc"
      dxlTracefile: ""
      # udrTracefile: "udr.rerating-job.trc"
      udrTracefile: ""

#A local nodeSelector definition has priority over the global definition above.
#nodeSelector: {}

# To constrain pods with specific labels. (E.g. Availability zone)
# A local affinity definition has priority over the global definition.
# affinity: {}
# Example:
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1a
#     - weight: 50
#       preference:
#         matchExpressions:
#         - key: topology.kubernetes.io/zone
#           operator: In
#           values:
#           - us-east-1b

tnsnames:
  bscsdb: '{{ tpl .Values.global.tnsnames.bscsdb . }}'

sqlnet:
  ora: '{{ tpl .Values.global.sqlnet.ora . }}'
