# Default values for lemChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageCredentials:
  eric-bss-eb-lem:
    repoPath:
    pullPolicy:
    registry:
      url:

images:
  eric-bss-eb-lem:
    name: "eric-bss-eb-lem"
    tag: "22.15.12"

lemDeployments:

  # Configuration for the LEM deployment which connects to a dedicated instance Sentinel RMS License Manager.
  # To enable HA, multiple LEM deployments with a different name and rmsServerHost can be configured below.
  # The name of the first LEM deployment with a dedicated Sentinel RMS, e.g. "rms1"
  - name: "rms1"
    # The replicaCount should be 1 or 0 for each lem deployment.
    replicaCount: 1
    # The IP address or hostname of the first machine where the Sentinel RMS License Manager is running
    rmsServerHost: ""
    # To constrain pods with specific labels. (E.g. Availability zone)
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - eric-bss-eb-lem
          topologyKey: kubernetes.io/hostname
    # On multi-AZ setups, consider restraining the LEM to the RMS server's AZ.
    # Example:
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: topology.kubernetes.io/zone
    #         operator: In
    #         values:
    #         - us-east-1a
    #     topologyKey: topology.kubernetes.io/zone

livenessProbe:
# Optional: Number of seconds after the container has started before liveness probe is initiated.
# Defaults to 0 seconds. Minimum value is 0.
  initialDelaySeconds: 60
# Optional: How often (in seconds) to perform the probe.
# Default to 10 seconds. Minimum value is 1.
  periodSeconds: 30
# Optional: Minimum consecutive successes for the probe to be considered successful after having failed.
# Defaults to 1. Must be 1 for liveness probe. Minimum value is 1.
  successThreshold: 1
# Optional: When a probe fails, Kubernetes will try failureThreshold times before giving up.
# Giving up in case of liveness probe means restarting the container.
# Defaults to 3. Minimum value is 1.
  failureThreshold: 10
# Optional: Number of seconds after which the probe times out.
# Defaults to 1 second. Minimum value is 1.
  timeoutSeconds: 5

readinessProbe:
# Optional: Number of seconds after the container has started before readiness probe is initiated.
# Defaults to 0 seconds. Minimum value is 0.
  initialDelaySeconds: 20
# Optional: How often (in seconds) to perform the probe.
# Default to 10 seconds. Minimum value is 1.
  periodSeconds: 5
# Optional: Minimum consecutive successes for the probe to be considered successful after having failed.
# Defaults to 1. Minimum value is 1.
  successThreshold: 5
# Optional: When a probe fails, Kubernetes will try failureThreshold times before giving up.
# In case of readiness probe the Pod will be marked Unready.
# Defaults to 3. Minimum value is 1.
  failureThreshold: 2
# Optional: Number of seconds after which the probe times out.
# Defaults to 1 second. Minimum value is 1.
  timeoutSeconds: 5

# Grace period for pod termination, which is used to shut down LEM gracefully.
terminationGracePeriodSeconds: "30"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

# Select the specific node to run the pod, e.g.
# kubernetes.io/hostname: "<hostname>"
#A local nodeSelector definition has priority over the global definition.
nodeSelector: {}

args:
  javaOpts: "-Xms128M \
             -Xmx512M \
             -XX:+UseG1GC \
             -XX:+HeapDumpOnOutOfMemoryError \
             -Xlog:safepoint=warning \
             -Xlog:gc=info"
  javaDebugOpts:

# When the Sentinel RMS is not available, LEM will start trying to reestablish the connection.
# When the number of connection retries exceeds the configured limit, LEM will be suspended.
# During suspension LEM will not respond to queries or updates on the license feature status.
# When RMS is running again and LEM could reestablish the connection, it will be reactivated
# and be responsive again.
rmsConnectionRetryLimit: 1

#
# The logging setting for logging.properties
#
logging:
  defaultLogger:
    logLevel: "INFO"
  lemIServant:
    logLevel: "INFO"
  featureHandler:
    logLevel: "FINE"
  defaultResult:
    logLevel: "INFO"
