{{- if .Values.global.rbac.sa_roles_create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eric-bss-eb-dmf-regular-role
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2000"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
{{- end -}}