{{- $startParameters := .Values.gmdlrdDeployment.startParameters -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eric-bss-eb-gmdlrd"
  labels:
    app: eric-bss-eb-gmdlrd
    chart: {{ template "eric-bss-eb-gmdlrd.chart" $ }}
    {{- include "eric-bss-eb-gmdlrd.kubernetesIoInfo" . | nindent 4 }}
    heritage: {{ $.Release.Service }}
  annotations:
  {{- include "eric-bss-eb-gmdlrd.productInfo" . | indent 4 }}
spec:
  {{ if gt (int $.Values.replicaCount) 1 }}
  replicas: 1
  {{ else }}
  replicas: {{ $.Values.replicaCount | default 1}}
  {{ end }}
  selector:
    matchLabels:
      app: eric-bss-eb-gmdlrd
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: eric-bss-eb-gmdlrd
        {{- include "eric-bss-eb-gmdlrd.kubernetesIoInfo" . | nindent 8 }}
        eric-bss-eb-network-database-client: 'true'
        eric-bss-eb-network-lem-client: 'true'
        eric-bss-eb-network-vault-client: 'true'
      annotations:
      {{- include "eric-bss-eb-gmdlrd.productInfo" . | indent 8 }}
    spec:
      securityContext:
        {{- include "eric-bss-eb-gmdlrd.checkPodUserLoginData" . | nindent 8 }}
      {{- if .Values.global.rbac.sa_roles_create }}
      serviceAccountName: {{ .Chart.Name }}-sa
      {{- end }}
      {{- if $.Values.global.imageCredentials.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.global.imageCredentials.pullSecret }}
      {{- end }}
      initContainers:
        - name: init-wait-for-xrefs
          # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
          {{ $templDict := dict "Values" .Values "containerKey" "init-wait-for-xrefs" }}
          image: "{{ template "eric-bss-eb-gmdlrd.registryUrl" $templDict }}/{{ template "eric-bss-eb-gmdlrd.repoPath" $templDict }}{{ index .Values "images" $templDict.containerKey "name" }}:{{ index .Values "images" $templDict.containerKey "tag" }}"
          imagePullPolicy: {{ template "eric-bss-eb-gmdlrd.pullPolicy" $templDict }}
          command: ["/bin/bash"]
          args: ["-c", "./waitForCondition.sh checkXref {{ $.Values.global.conditionCheckInterval }} -U "]
          env:
          - name: TZ
            value: "{{ $.Values.global.timezone }}"
          - name: BSCS_LOG_FULL
            value: "/log/gmd"
          volumeMounts:
          - mountPath: /workdir/XREF
            name: xref-volume
          - mountPath: /log
            name: logs-volume
      containers:
        - name: eric-bss-eb-gmdlrd
          # containerKey identifies the section inside .Values.images and .Values.imageCredentials to be used here
          {{ $templDict := dict "Values" .Values "containerKey" "eric-bss-eb-gmdlrd" }}
          image: "{{ template "eric-bss-eb-gmdlrd.registryUrl" $templDict }}/{{ template "eric-bss-eb-gmdlrd.repoPath" $templDict }}{{ index .Values "images" $templDict.containerKey "name" }}:{{ index .Values "images" $templDict.containerKey "tag" }}"
          imagePullPolicy: {{ template "eric-bss-eb-gmdlrd.pullPolicy" $templDict }}
          resources:
            limits:
              memory: "{{ .Values.resources.limits.memory}}"
              cpu: "{{ .Values.resources.limits.cpu}}"
            requests:
              memory: "{{ .Values.resources.requests.memory}}"
              cpu: "{{ .Values.resources.requests.cpu}}"
          env:
          - name: K8S_ENV
            value: "true"
          - name: NLS_LANG
            value: "{{ .Values.global.nlsLang }}"
          - name: DATABASE_SERVER_NAME
            value: "{{ .Values.global.databaseServerName }}"
          - name: DATABASE_SERVER_PORT
            value: "{{ .Values.global.databaseServerPort }}"
          - name: TZ
            value: "{{ .Values.global.timezone }}"
          {{ if $.Values.global.databaseTls.enable }}
          - name: ORA_SEC_WLT
            value: "/oratns/secret"
          {{ end }}
          - name: DXL_CONTINUE_AFTER_CORRUPT
            value: "{{ .Values.global.tracingAndLogging.dxlContinueAfterCorrupt }}"
          {{ if not $.Values.global.secretManager.enable }}
          - name: NO_SECRET_MANAGER
            value: "true"
          {{ end }}
          command: ["/bin/bash"]
          args: ["-c", "ulimit -c unlimited && mkdir -p {{ $.Values.global.coredumpDirectory }} && \
                  ./gmdlrd {{ $startParameters }}"]
          volumeMounts:
          - name: ctrl-volume
            mountPath: /workdir/CTRL
          - name: xref-volume
            mountPath: /workdir/XREF
          - name: pwdmgr-security-volume
            mountPath: /workdir/PWDMGR_SECURITY
          - name: logs-volume
            mountPath: /log
          - name: coredump-volume
            mountPath: "{{ .Values.global.coredumpDirectory }}"
          - name: tnsnames-ora-volume
            mountPath: /oratns/tnsnames.ora
            subPath: tnsnames.ora
          - name: sqlnet-ora-volume
            mountPath: /oratns/sqlnet.ora
            subPath: sqlnet.ora
          - name: rac-setup-volume
            mountPath: /ericssonbilling/resource/bat/RAC_Setup.xml
            subPath: RAC_Setup.xml
          {{ if .Values.global.securityTls.enable }}
          - name: tls-volume
            mountPath: "/tls/connect"
            readOnly: true
          {{ end }}
          {{ if $.Values.global.databaseTls.enable }}
          - name: wallet-volume
            mountPath: "/oratns/secret"
          {{ end }}
          {{ if and ($.Values.global.secretManager.enable) ($.Values.global.secretManager.vault.caSecretName) }}
          - name: secretmanager-tls-volume
            mountPath: "/tls/secretManager/vault"
            readOnly: true
          {{ end }}
          - name: vault-clientcfg-xml-volume
            mountPath: /ericssonbilling/resource/vault-clientcfg/vault-clientcfg.xml
            subPath: vault-clientcfg.xml
          - name: vault-clientcfg-dtd-volume
            mountPath: /ericssonbilling/resource/vault-clientcfg/vault-clientcfg.dtd
            subPath: vault-clientcfg.dtd
          lifecycle:
            preStop:
              exec:
                command: ["rm", "-f", "/workdir/CTRL/gmdrld*"]
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- else if $.Values.global.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $.Values.affinity }}
      affinity: {{ toYaml $.Values.affinity | nindent 8 }}
      {{- else if $.Values.global.affinity }}
      affinity: {{ toYaml $.Values.global.affinity | nindent 8 }}
      {{- end }}
      volumes:
      - name: ctrl-volume
        emptyDir: {}
      - name: pwdmgr-security-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-pwdmgr-security
      - name: xref-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-xref
      - name: logs-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-logs
      - name: coredump-volume
        persistentVolumeClaim:
          claimName: eric-bss-eb-pvc-coredump
      - name: tnsnames-ora-volume
        configMap:
          name: eric-bss-eb-gmdlrd-tnsnames.ora
      - name: sqlnet-ora-volume
        configMap:
          name: eric-bss-eb-gmdlrd-sqlnet.ora
      - name: rac-setup-volume
        configMap:
          name: eric-bss-eb-gmdlrd-rac-setup.xml
      - name: vault-clientcfg-xml-volume
        configMap:
          name: eric-bss-eb-gmdlrd-vault-clientcfg.xml
      - name: vault-clientcfg-dtd-volume
        configMap:
          name: eric-bss-eb-gmdlrd-vault-clientcfg.dtd
      {{ if and ($.Values.global.secretManager.enable) ($.Values.global.secretManager.vault.caSecretName) }}
      - name: secretmanager-tls-volume
        secret:
          secretName: "{{ $.Values.global.secretManager.vault.caSecretName }}"
          items:
          - key: {{ $.Values.global.secretManager.vault.caCertificate }}
            path: ca.pem
      {{ end }}
      {{ if .Values.global.securityTls.enable }}
      - name: tls-volume
        secret:
          secretName: "{{ .Values.global.securityTls.clientSecretName }}"
          items:
          - key: {{ .Values.global.securityTls.trustedCertificateKey }}
            path: certificate.pem
      {{ end }}
      {{ if $.Values.global.databaseTls.enable }}
      - name: wallet-volume
        secret:
          secretName: "{{ $.Values.global.databaseTls.clientSecretName }}"
      {{ end }}
