apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-pwdmgr-passwordmanager.properties
data:
  passwordManager.properties: |
    #####################################################################################
    # File Name: passwordManager.properties                                             #
    # Application: PWDMGR                                                               #
    # Description: File used to store all the configurations for PWDMGR application     #
    #####################################################################################

    # DATABASE CONFIGURATION
    # For multiple databases configuration, use the following configuration:
    # databaseConfiguration1.name=<name1>
    # databaseConfiguration1.databaseUrl=<databaseUrl1>

    # databaseConfiguration2.name=<name2>
    # databaseConfiguration2.databaseUrl=<databaseUrl2>

    # databaseConfigurationN.name=<nameN>
    # databaseConfigurationN.databaseUrl=<databaseUrlN>

    {{- $index := 0 -}}
    {{- range $databaseConfiguration := .Values.pwdmgrProperties.databaseConfig.databaseConfigurationRange }}
    {{ if tpl $databaseConfiguration.id $ }}
    {{ $index = add1 $index }}
    databaseConfiguration{{ $index }}.name={{ tpl $databaseConfiguration.name $ }}
    {{ if $.Values.global.databaseTls.enable }}
    databaseConfiguration{{ $index }}.databaseUrl={{ tpl $databaseConfiguration.databaseSecureUrl $ }}
    {{ else }}
    databaseConfiguration{{ $index }}.databaseUrl={{ tpl $databaseConfiguration.databaseUrl $ }}
    {{ end }}
    {{ end }}
    {{- end }}

    # Examples for databaseUrl
    # databaseConfiguration1.databaseUrl=jdbc:oracle:thin:@serverNameDummy:portNumberDummy:sidDummy
    # In case of using RAC installation
    # databaseConfiguration1.databaseUrl=jdbc:oracle:thin:@serverNameDummy:portNumberDummy/serviceNamedummy
    # In case of secure databases by using TNS entry name
    # databaseConfiguration1.databaseUrl=jdbc:oracle:thin:@TNSEntryDummy.world

    databasePwdMaxLength={{ .Values.pwdmgrProperties.databaseConfig.databasePwdMaxLength }}

    # LDAP CONFIGURATION
    # For multiple ldap directories, use the following configuration:
    # ldapConfiguration1.ldapBase=<ldapBase1>
    # ldapConfiguration1.userBase=<userBase1>

    # ldapConfiguration2.ldapBase=<ldapBase2>
    # ldapConfiguration2.userBase=<userBase2>

    # ldapConfigurationN.ldapBase=<ldapBaseN>
    # ldapConfigurationN.userBase=<userBaseN>

    ldapUrl={{ tpl .Values.pwdmgrProperties.ldapConfig.ldapUrl . }}

    {{- range $index, $ldapConfiguration := .Values.pwdmgrProperties.ldapConfig.ldapConfigurationRange }}
    {{ if $ldapConfiguration.userBase }}
    ldapConfiguration{{ add1 $index }}.ldapBase={{ $ldapConfiguration.ldapBase }}
    ldapConfiguration{{ add1 $index }}.userBase={{ $ldapConfiguration.userBase }}
    {{- end }}
    {{- end }}

    ldapPwdMaxLength={{ .Values.pwdmgrProperties.ldapConfig.ldapPwdMaxLength }}

    # Properties related to the secure database connection using a wallet.
    #
    # This property is used to specify the location of the wallet.
    #
    # walletLocation=
    #
    {{ if .Values.global.databaseTls.enable }}
    walletLocation={{ .Values.pwdmgrProperties.databaseConfig.walletLocation }}/{{ .Values.global.databaseTls.trustedCertificateKey }}
    {{ end }}

    # This property is used to specify cipher suites that will be used by the TSL connection.
    #
    # To enable a subset of the cipher suites available by default for Oracle 12.1:
    # sslCipherSuites=(TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA)
    #
    # For Oracle 12.2, 18.3 and 19.0, the following cipher suites are supported:
    # TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA and TLS_RSA_WITH_AES_256_CBC_SHA
    {{ if .Values.global.databaseTls.enable }}
    sslCipherSuites={{.Values.global.databaseTls.cipherSuites}}
    {{ end }}
