apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-bss-eb-pwdmgr-registry-pwdmgr-passwordmanager.xml
data:
  Registry_PWDMGR_PasswordManager.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

    <ComponentRegistry>
        <Node name="PWDMGR">
            <KeyValue key="ExplicitPasswordAllowed" type="Boolean" value="{{ .Values.pwdmgrRegistry.explicitPasswordAllowed }}" comment="This key defines if passwords can be set explicitly or not. Valid values: true OR false"/>
            <KeyValue key="ClientSessionTimeout" type="Integer" value="{{ .Values.pwdmgrRegistry.clientSessionTimeout }}" comment="Timeout for client interface session in seconds."/>
            <KeyValue key="enableLegalNotice" type="Boolean" value="{{ .Values.pwdmgrRegistry.enableLegalNotice }}" comment="If true, the legal notice will be shown."/>
            <KeyValue key="LegalNoticeText" type="String" value="{{ .Values.pwdmgrRegistry.legalNoticeText }}" comment="The legal notice text to be shown. If not set the default text will be shown."/>
        </Node>
    </ComponentRegistry>
