apiVersion: v1
kind: Secret
metadata:
  name: eric-bss-eb-secret-pwdmgrjob-log4j2.xml
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1020"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
      <Properties>
        <!-- System properties baseSecurityLogDir and processId are set by application and must not be set by operator. -->
        <Property name="basePath">/seclog</Property>
        <Property name="processId">${sys:processId}</Property>
      </Properties>
      <Appenders>
        <RollingFile name="PwdMgrChangePasswordFile" fileName="${basePath}/PWDMGR.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/PWDMGR.${hostName}.${processId}.SecLog%i.log" append="true" immediateFlush="true">
          <RFC5424Layout facility="AUTH" newLine="true" messageId="PWDCHP" appName="PWDMGR" />
          <Policies>
            <SizeBasedTriggeringPolicy size="10 MB" />
          </Policies>
          <DefaultRolloverStrategy fileindex="nomax" max="10" />
        </RollingFile>
        <RollingFile name="PwdMgrChangeEncryptionKeyFile" fileName="${basePath}/PWDMGR.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/PWDMGR.${hostName}.${processId}.SecLog%i.log" append="true" immediateFlush="true">
          <RFC5424Layout facility="AUTH" newLine="true" messageId="PWDCHK" appName="PWDMGR" />
          <Policies>
            <SizeBasedTriggeringPolicy size="10 MB" />
          </Policies>
          <DefaultRolloverStrategy fileindex="nomax" max="10" />
        </RollingFile>
         <RollingFile name="PwdMgrGenericSecurityFile" fileName="${basePath}/PWDMGR.${hostName}.${processId}.SecLog.log" filePattern="${basePath}/PWDMGR.${hostName}.${processId}.SecLog%i.log" append="true" immediateFlush="true">
          <RFC5424Layout facility="AUTH" newLine="true" messageId="PWDGEN" appName="PWDMGR" />
          <Policies>
            <SizeBasedTriggeringPolicy size="10 MB" />
          </Policies>
          <DefaultRolloverStrategy fileindex="nomax" max="10" />
        </RollingFile>
        <!-- The Syslog Appender is used to send messages to a remote syslog daemon.
             This is an example of configuration of this appender. The values must be set accordingly, such as host, port etc.
             For SSL, the location and the password of both TrustStore and KeyStore can be set using environment variables.
             You can configure more than one Syslog as you need. If it is necessary to distinguish the messages according to its message Id, it is possible
             to configure one Syslog for each logger, as the examples: PwdMgrChangePasswordSyslog, PwdMgrChangeEncryptionKeySyslog and PwdMgrGenericSecuritySyslog
        <Syslog name="PwdMgrChangePasswordSyslog" host="{{ .Values.global.SyslogAppenderSecurityTls.hostSyslogAppender }}" port="{{ .Values.global.SyslogAppenderSecurityTls.portSyslogAppender }}" format="RFC5424" newLine="true" messageId="PWDCHP" appName="PWDMGR">
            <SSL>
                <TrustStore location="${env:SYSLOG_TRUSTSTORE}" passwordFile="${env:SYSLOG_TRUSTSTORE_PASSWORD_FILE}"/>
                <KeyStore location="${env:SYSLOG_KEYSTORE}" passwordFile="${env:SYSLOG_KEYSTORE_PASSWORD_FILE}" />
            </SSL>
         </Syslog>
        <Syslog name="PwdMgrChangeEncryptionKeySyslog" host="{{ .Values.global.SyslogAppenderSecurityTls.hostSyslogAppender }}" port="{{ .Values.global.SyslogAppenderSecurityTls.portSyslogAppender }}" format="RFC5424" newLine="true" messageId="PWDCHK" appName="PWDMGR">
            <SSL>
                <TrustStore location="${env:SYSLOG_TRUSTSTORE}" passwordFile="${env:SYSLOG_TRUSTSTORE_PASSWORD_FILE}"/>
                <KeyStore location="${env:SYSLOG_KEYSTORE}" passwordFile="${env:SYSLOG_KEYSTORE_PASSWORD_FILE}" />
            </SSL>
         </Syslog>
        <Syslog name="PwdMgrGenericSecuritySyslog" host="{{ .Values.global.SyslogAppenderSecurityTls.hostSyslogAppender }}" port="{{ .Values.global.SyslogAppenderSecurityTls.portSyslogAppender }}" format="RFC5424" newLine="true" messageId="PWDGEN" appName="PWDMGR">
            <SSL>
                <TrustStore location="${env:SYSLOG_TRUSTSTORE}" passwordFile="${env:SYSLOG_TRUSTSTORE_PASSWORD_FILE}"/>
                <KeyStore location="${env:SYSLOG_KEYSTORE}" passwordFile="${env:SYSLOG_KEYSTORE_PASSWORD_FILE}" />
            </SSL>
         </Syslog>
         -->
      </Appenders>
      <Loggers>
        <Logger name="PwdMgrChangePasswordLog" level="INFO">
          <AppenderRef ref="PwdMgrChangePasswordFile" />
          <!-- This is an example how to use the Syslog Appender to log messages to a remote syslog server.
          <AppenderRef ref="PwdMgrChangePasswordSyslog" />  -->
        </Logger>
        <Logger name="PwdMgrChangeEncryptionKeyLog" level="INFO">
          <AppenderRef ref="PwdMgrChangeEncryptionKeyFile" />
          <!-- This is an example how to use the Syslog Appender to log messages to a remote syslog server.
          <AppenderRef ref="PwdMgrChangeEncryptionKeySyslog" />  -->
        </Logger>
         <Logger name="PwdMgrGenericLog" level="INFO">
          <AppenderRef ref="PwdMgrGenericSecurityFile" />
          <!-- This is an example how to use the Syslog Appender to log messages to a remote syslog server.
          <AppenderRef ref="PwdMgrGenericSecuritySyslog" />  -->
        </Logger>
        <Root level="OFF" />
      </Loggers>
    </Configuration>
