# Default values for Network Policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# CIDR (containing ip adress and network mask) and port of the LDAP server used by EB
# Example cidr: "10.0.0.0/32"
ldap:
  cidr: ""
  port: ""

vault:
  # Conditional, if vault is used:
  # CIDR (containing IP address and network mask) of the vault server
  # cidr: "10.0.0.0/32"  # example value
  cidr: ""
  # Port of the vault server
  # port: "8200"  # example value
  port: ""
