{{ if and .Values.global.ingress.ingressClass.OAM .Values.global.ingress.enabled }}
{{ if or (index .Values "eric-bss-eb-admx" "enabled") (index .Values "eric-bss-eb-wex" "enabled") .Values.ingress.customHttpproxy.OAM}}

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: eric-bss-eb-oam-root-httpproxy
  annotations:
    projectcontour.io/ingress.class: {{.Values.global.ingress.ingressClass.OAM}}
spec:
  virtualhost:
    fqdn: {{.Values.global.ingress.fqdn.OAM}}
    {{- if .Values.global.ingress.tlsSecretName.OAM }}
    tls:
      secretName: {{.Values.global.ingress.tlsSecretName.OAM}}
    {{- end }}
  includes:
{{ if index .Values "eric-bss-eb-admx" "enabled"}}
    - name: eric-bss-eb-admx-httpproxy
      conditions:
        - prefix: /admx_full
{{ end }}
{{ if index .Values "eric-bss-eb-wex" "enabled"}}
    - name: eric-bss-eb-wex-httpproxy
      conditions:
        - prefix: /wex
{{ end }}
{{ range $ind, $custProxy := .Values.ingress.customHttpproxy.OAM }}
    - name: {{ $custProxy.httpproxyName }}
      conditions:
        - prefix: {{ $custProxy.httpproxyPrefix }}
{{ end }}
{{ end }}
{{ end }}
